Issue 1014
aristanetworks/ansible-avd pull request #1017
Opened 2021-06-09 14:03 UTC by c-po

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #1014

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

```yml
group:
  interface:
    < group_name >:
      interfaces:
        - < interface_or_interface_range >
      maintenance_profile:
        bgp: < bgp_maintenance_profile_name >
        interface: < interface_maintenance_profile_name >
```

## How to test

## Checklist:

- [ ] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-06-09 16:40 UTC, ClausHolbechArista requested changes, later dismissed
Some changes to the data model after all (sorry about that). Also you are missing documentation for this feature. I think it would make sense to have "group" and "maintenance" under a common heading like "maintenance mode".

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/group.yml
> +    SFP+_Interface_Group:
The `+` is not accepted by EOS. Please use valid data for tests.

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/group.yml
> +        - Ethernet11/-28/1
Interface range is not valid

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +      - [BGP](#group-bgp)
heading should match TOC.
Group BGP
Group Interface

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +#### Group Interfaces
Use singular to match the data model

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +#### BGP Interfaces
Wrong heading. (Also reorder to BGP comes first)

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/group.j2
> +{% if group.bgp is arista.avd.defined %}
This test is covered by `arista.avd.natural_sort` so it can be removed.

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +      neighbor:
Use plural in data model (sorry if I missed this on your issue)

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +        bgp: < bgp_maintenance_profile_name >
It is possible to configure more than one maintenance profile bgp per group (same for interface):
```eos
group interface test
   interface Et10-20,30-40
   maintenance profile bgp test2
   maintenance profile bgp test
   exit
```
So we should make these into lists.

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/group.j2
> +{% if group.interface is arista.avd.defined %}
This test is covered by arista.avd.natural_sort so it can be removed.

2021-06-09 16:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/group.j2
> +{%       for interface in group.interface[group_name].interfaces %}
you can consider using `arista.avd.natural_sort` to simplify the template, since it covers the test above.

2021-06-10 07:04 UTC, c-po commented
Adjusted to requested changes

2021-06-10 09:18 UTC, ClausHolbechArista commented
> Adjusted to requested changes.
> 
> > I think it would make sense to have "group" and "maintenance" under a common heading like "maintenance mode".
> 
> Well it can be adjusted to:
> 
> ```yaml
> maintenance_mode:
>   group:
>     bgp:
>       < group_name >:
>         vrf: "< vrf_name >"
>         neighbors:
>           - "< ip_address >"
>           - "< ipv6_address >"
>           - "< peer_group_name >"
>         maintenance_profile:
>           bgp:
>             - < profile_name >
>    interface:
>       < group_name >:
>         interfaces:
>           - "< interface_or_interface_range >"
>         maintenance_profile:
>           bgp:
>             - < profile_name >
>           interface:
>             - < profile_name >
> ```
> 
> I have no personal preference here and are open to whatever you prefer.

Sorry I was not clear. I meant only in the documentation, to have the two sections under a common main heading.

2021-06-10 09:37 UTC, c-po commented
Something like the following in README.md?

### Maintenance
#### Group

```yaml
group:
  bgp:
    < group_name >:
      vrf: "< vrf_name >"
      neighbors:
        - "< ip_address >"
        - "< ipv6_address >"
        - "< peer_group_name >"
      maintenance_profile:
        bgp:
          - < profile_name >
  interface:
    < group_name >:
      interfaces:
        - "< interface_or_interface_range >"
      maintenance_profile:
        bgp:
          - < profile_name >
        interface:
          - < profile_name >
```

2021-06-10 10:13 UTC, ClausHolbechArista commented
> Something like the following in README.md?

Once again I managed to be unclear. This PR has no template for `eos_cli_config_gen` auto generated device documentation. Before you spend time on it, we should sort out the two "competing" PRs covering this. (See comment on issue)

2021-06-10 12:44 UTC, c-po commented
Ah, now I got the point. Yes I did not spend any time on that documentation templating. I Guess you are referring to PR #1020 which also has a implementation for this topic with a slightly different datamodel. I also see a bunch of conflicting files.

It would be unhonest to not say "please use my PR" but I get your point - we should select the one which is best for all worlds. I still recommend to maybe split this in two PRs so we both can work on the maintenance implementation. Still happy to add some initial work of the documentation templating which can then later be referenced in the other PR.

Another solution would be to take this PR "as is" and then use the documentation part from #1020 to polish this one up.

2021-06-14 19:41 UTC, c-po commented
Somehpw GotHub thinks there are still changes requested - or am I missing something?

2021-06-15 08:19 UTC, ClausHolbechArista commented
No this is just waiting for us to decide on the data model. I hope to fint out by tomorrow.

2021-06-16 07:07 UTC, ClausHolbechArista commented
@c-po The maintainer group prefers the data model in this PR, so when you add the device documentation templates I can do a final review and merge it. Thank you for the patience :)

2021-06-16 13:11 UTC, daanvdsanden commented
I also left a comment in #1020, but I feel this model is not consistent with the rest of the models used, see for reasoning and examples my comments in #1020. I can live with both implementations, since they both work and give a working configuration.

2021-06-17 16:19 UTC, c-po commented
@ClausHolbechArista I hope this suits your expectations

2021-06-18 07:18 UTC, ClausHolbechArista commented
> @ClausHolbechArista I hope this suits your expectation.

Not entirely. We should not generate documentation if the feature is not set. Is it okay that I adjust the templates directly on your branch?

2021-06-18 11:36 UTC, c-po commented
Of course @ClausHolbechArista just go ahead. Thanks

2021-06-23 07:35 UTC, titom73 approved these changes
LGTM!

2021-06-23 19:58 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos-intended-config.j2
> +{# BGP Groups configuration #}
This is more cosmetic, but the ordered generate doesn't match what I tested on 4.25.4M DUT.

```shell
vrf instance MGMT
!
group bgp bar
   vrf red
   neighbor peer-group-baz
   maintenance profile bgp downlink-neighbors
   exit
!
group bgp foo
   neighbor fe80::1
   neighbor 169.254.1.1
   maintenance profile bgp uplink-neighbors
   maintenance profile bgp ixp
   exit
!
interface Port-Channel5
   description MLAG_PEER_CN-IT-BL1B_Po5
   switchport trunk allowed vlan 2-4094
   switchport mode trunk
   switchport trunk group LEAF_PEER_L3
   switchport trunk group MLAG
!
interface Ethernet1
   description P2P_LINK_TO_CN-SPINE1_Ethernet8
   no switchport
   ip address 172.30.254.25/31
!
interface Ethernet2
   description P2P_LINK_TO_CN-SPINE2_Ethernet8
   no switchport
   ip address 172.30.254.27/31
!
interface Ethernet3
   description P2P_LINK_TO_CN-SPINE3_Ethernet8
   no switchport
   ip address 172.30.254.29/31
!
interface Ethernet4
   description P2P_LINK_TO_CN-SPINE4_Ethernet8
   no switchport
   ip address 172.30.254.31/31
!
interface Ethernet5
   description MLAG_PEER_CN-IT-BL1B_Ethernet5
   channel-group 5 mode active
!
interface Ethernet6
   description MLAG_PEER_CN-IT-BL1B_Ethernet6
   channel-group 5 mode active
!
interface Ethernet7
!
interface Ethernet8
!
interface Ethernet9
!
interface Ethernet10
!
interface Ethernet11
!
interface Ethernet12
!
interface Ethernet13
!
interface Ethernet14
!
interface Ethernet15
!
interface Loopback0
   description EVPN_Overlay_Peering
   ip address 192.168.255.8/32
!
interface Loopback1
   description VTEP_VXLAN_Tunnel_Source
   ip address 192.168.254.8/32
!
interface Management1
   description oob_management
   vrf MGMT
   ip address 192.168.200.110/24
!
interface Vlan4093
   description MLAG_PEER_L3_PEERING
   ip address 10.255.251.6/31
!
interface Vlan4094
   description MLAG_PEER
   no autostate
   ip address 10.255.252.6/31
!
interface Vxlan1
   vxlan source-interface Loopback1
   vxlan virtual-router encapsulation mac-address mlag-system-id
   vxlan udp-port 4789
!
group interface QSFP_Interface_Group
   interface Et1,5
   maintenance profile interface uplink-interfaces
   exit
!
group interface SFP_Interface_Group
   maintenance profile interface ix-interfaces
   maintenance profile interface downlink-interfaces
   maintenance profile bgp local-ix
   maintenance profile bgp downlink-neighbors
   exit
!
```

2021-06-23 20:01 UTC, carlbuchmann approved these changes
LGTM!
I noted a cosmetic suggestion to adjust to CLI output order, but we can update this in another PR - I will merge!

2021-06-23 20:26 UTC, titom73 approved these changes
LGTM!

2021-06-24 01:04 UTC, merged