Added as-path-acl feature
aristanetworks/ansible-avd pull request #1063
Opened 2021-06-27 22:38 UTC by burnyd

## Change Summary

## Types of changes

- [X] New feature (non-breaking change which adds functionality)

## Related Issue(s)
https://github.com/aristanetworks/ansible-avd/issues/1042

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Adding feature for as-path-access-lists

## How to test

## Checklist:

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [X] My change requires a change to the documentation.
- [X ] I have updated the documentation accordingly.
- [X ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [X ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

#### I ran the molecule converge within the makefile hoping this is enough.  Feel free to decline if this was not done properly.

2021-06-28 13:03 UTC, ClausHolbechArista requested changes
There is still some work to do, but thank you for this contribution. Reach out if you need assistance or have questions on any of my comments.

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/as-path-access-lists.j2
> +{% if ip_as_path_access_lists is defined and ip_as_path_access_lists is not none %}
please use `is arista.avd.defined` instead since that includes both tests.

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/as-path-access-lists.j2
> +| Type | Permit | Deny  |
something looks wrong in this table. Not the same number of headings (3) as divider lines (2) as printed fields (1).

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/as-path-access-lists.j2
> +{%     endfor %}
Add space before next heading

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/as-path-access-lists.j2
> +{% include 'eos/as-path-access-lists.j2' %}
missing indentation.
also rename files to match the main key name (except `_` -> `-`).
so `ip-as-path-access-lists.j2`

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/hosts
> +as-path-access-lists
please use full name of main key so `ip-as-path-access-lists`

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/as_path_acls.md
> +# as_path_acls
this file must be from an earlier name. Please rerun molecule locally and commit the update artifacts.

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/as_path_acls.md
> +                      | NAME | Action | AS-Number or REGEX | any |
This doesn't look good :)

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/as_path_acls.md
> +# as_path_acls
Also there is no host_var file for this host in this branch.

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +#### IP as-path Access-Lists
Cap like `IP As-Path Access-Lists`

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/as-path-access-lists.j2
> +## AS Path access-listts
typo `tt`

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/as-path-access-lists.j2
> +{%             if access_lists[access_list].type is arista.avd.defined %}
`access_lists` should probably be `ip_as_path_access_lists`

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/as-path-access-lists.j2
> +{#ip_as_path_access_lists:
Please remove these notes when you are done.

2021-06-28 13:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos-device-documentation.j2
> +{# AS-Path access-lists #}
I think this section should be moved up under "IPv6 Extended Access-lists". Also include two `##` so it is clear that it is a subheading that goes under `# ACL`.

2021-06-28 13:03 UTC, ClausHolbechArista commented on development/requirements-dev.txt
> -../ansible_collections/arista/avd/requirements-dev.txt
This file should not be touched in this PR

2021-06-28 13:03 UTC, ClausHolbechArista commented on development/requirements-dev.txt
> -../ansible_collections/arista/avd/requirements-dev.txt
Also development/install.sh should not be touched in this PR.

2021-06-28 13:03 UTC, ClausHolbechArista commented on development/requirements.txt
> -../ansible_collections/arista/avd/requirements.txt
This file should not be touched in this PR

2021-07-06 14:40 UTC, burnyd commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/as-path-access-lists.j2
> +{% if ip_as_path_access_lists is defined and ip_as_path_access_lists is not none %}
Apologies I copied over access-lists.j2 which still has the previous j2 way.

2021-07-06 14:46 UTC, burnyd commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/as-path-access-lists.j2
> +{#ip_as_path_access_lists:
lols woops.

2021-07-06 17:01 UTC, ClausHolbechArista requested changes
Still a lot to do. The bad files are still there, so issues not resolved.

2021-07-06 17:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ip-as-path-access-lists.j2
> +{% if ip_as_path_access_lists is defined and ip_as_path_access_lists is  arista.avd.defined %}
change to `{% if ip_as_path_access_lists is arista.avd.defined %}

2021-07-06 17:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ip-as-path-access-lists.j2
> +## AS Path access-listts
typo. Double `t`

2021-07-06 17:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ip-as-path-access-lists.j2
> +| -------- | ------ |
Fix to three columns and align with heading. Also remove extra space after `Deny` in heading - keep one.

2021-07-06 17:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ip-as-path-access-lists.j2
> +{%         for action in ip_as_path_access_lists[ip_as_path_access_list].type | arista.avd.natural_sort %}
This looks wrong, and only one field below.

2021-07-06 17:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ip-as-path-access-lists.j2
> +{% include 'eos/ip-as-path-access-lists.j2' %}
missing indentation

2021-07-06 17:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos-device-documentation.j2
> +
Remove these 3 extra newlines

2021-07-06 17:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ip-as-path-access-lists.j2
> +{% endif %}
missing trailing newline

2021-09-17 14:53 UTC, carlbuchmann commented
@burnyd - closing PR as it's stale and the original fork/branch has been deleted - feel free to re-submit a new PR if you require this feature!

2021-09-17 14:53 UTC, closed without merging