Sort the ntp servers, but keep the first defined as preferred
aristanetworks/ansible-avd pull request #1111
Opened 2021-07-22 13:33 UTC by colinmacgiolla

## Change Summary

Generated CLI config doesn't match the switch running-config render, which has the ntp servers sorted by IP, then by name (if used)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #1091

## Component(s) name

`arista.avd.eos_cli_gen`

## Proposed changes
No change in the datamodel (for now).

The existing datamodel assumes a list of NTP servers, with the first one being preferred. The existing behaviour renders the servers in the order they are provided, which doesn't match the outcome once configured on the device.

This change preserves the existing behaviour (1st entry in the list is preserved), but sorts the list of ntp servers

## How to test
Updated molecule testing for NTP to catch this issue

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-07-23 00:21 UTC, carlbuchmann commented
@colinmacgiolla - as per the comment in the issue, I suggest we update the `eos_cli_config_gen` data model.

2021-07-27 12:40 UTC, titom73 requested changes
Thanks @colinmacgiolla for your PR.

Could you just fix opened comment and I will be happy to merge PR right away after you push the change.

2021-07-27 12:40 UTC, titom73 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ntp.j2
> +{%     for node in ntp_server.nodes | arista.avd.default([]) | arista.avd.natural_sort %}
This `ntp_server.nodes | arista.avd.default([]) | arista.avd.natural_sort` should be shorten with `ntp_server.nodes | arista.avd.natural_sort`

2021-08-03 10:12 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ntp-servers.j2
> +{% endif %}
missing newline at the end of the file

2021-08-04 08:31 UTC, colinmacgiolla commented
Based on the [conversation here](https://github.com/aristanetworks/ansible-avd/issues/1091) I've started a new branch with an updated schema, but its not ready for pull yet

2021-08-04 09:00 UTC, ClausHolbechArista commented
@colinmacgiolla should we move this PR to draft then until we know how the other one moves along? No need to clutter release notes etc with multiple overlapping changes.

2021-09-11 11:17 UTC, ClausHolbechArista commented
Closed, replaced by #1137

2021-09-11 11:17 UTC, closed without merging