update eos_validate_state role to make it more scalable
aristanetworks/ansible-avd pull request #1115
Opened 2021-07-22 22:03 UTC by ksator

## Change Summary

`eos_validate_state` current output is verbose if we have many devices.   

- Moved `Summary Totals Per Category` above `Summary Totals Devices Under Tests` in the test report. So when we have many devices we can read `Summary Totals Per Category` from the top of the file (no need anymore to scroll down)

- Introduced a new var (`eos_validate_output_level`) defined in the role `default` dir with the default value `default` 

- The default output is now less verbose as it doesn't include anymore the last section (`All Test Results`) which is the longest one and the less interesting.

- if the var `eos_validate_output_level` is set to `verbose`, the role includes the details about successful tests (in the section `All Test Results`)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #1113 

## Component(s) name

`eos_validate_state`

## Proposed changes

## How to test

Execute the role, and verify the output. 

`ansible-playbook playbooks/playbook_validate_states.yml -i inventories/inventory.yml`
should not include the section (`All Test Results`) 

`ansible-playbook playbooks/playbook_validate_states.yml -i inventories/inventory.yml --extra-vars eos_validate_output_level=default`
should not include the section (`All Test Results`) 

`ansible-playbook playbooks/playbook_validate_states.yml -i inventories/inventory.yml --extra-vars eos_validate_output_level=verbose`
should include the section (`All Test Results`) 

`ansible-playbook playbooks/playbook_validate_states.yml -i inventories/inventory.yml --extra-vars eos_validate_output_level=whatever_else`
should not include the section (`All Test Results`) 

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-07-27 12:46 UTC, titom73 commented
Hello @ksator 

Thanks for this PR. After reviewing your change, I am wondering if you expect to support more than 1 verbisoty level ?

If not, I would go with `eos_validate_output_verbose: < True | False>`

Any thought?

2021-07-27 12:50 UTC, ksator commented
@titom73 you right. I will update the PR with this.

2021-08-01 07:10 UTC, titom73 requested changes
Following behaviour will be implemented:

`eos_validate_output_verbose: < True | False>`

2021-09-10 08:32 UTC, titom73 commented
Will be re-opened later

2021-09-10 08:32 UTC, closed without merging