AAA accounting commands
aristanetworks/ansible-avd pull request #1132
Opened 2021-08-05 13:47 UTC by xaviramon

## Change Summary

EOS CLI config gen templates update to support AAA accounting console commands.
Includes molecule updated tests.
Refactoring of documentation template included.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #1100 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
aaa_accounting structure updated from:
```aaa_accounting:
  exec:
    default:
      type: < none | start-stop | stop-only >
      group: < group_name >
  commands:
    commands_default:
      - commands: < all | 0-15 >
        type: < none | start-stop | stop-only >
        group: < group_name >
        logging: < true | false >
      - commands: < all | 0-15 >
        type: < none | start-stop | stop-only >
        group: < group_name >
        logging: < true | false >
```
To
```aaa_accounting:
  exec:
    console:
      type: < none | start-stop | stop-only >
      group: < group_name >
    default:
      type: < none | start-stop | stop-only >
      group: < group_name >
  commands:
    commands_console:
      - commands: < all | 0-15 >
        type: < none | start-stop | stop-only >
        group: < group_name >
        logging: < true | false >
      - commands: < all | 0-15 >
        type: < none | start-stop | stop-only >
        group: < group_name >
        logging: < true | false >
    commands_default:
      - commands: < all | 0-15 >
        type: < none | start-stop | stop-only >
        group: < group_name >
        logging: < true | false >
      - commands: < all | 0-15 >
        type: < none | start-stop | stop-only >
        group: < group_name >
        logging: < true | false >
```

## How to test
Define variables in corresponding group or host vars:
```aaa_accounting:
  exec:
    console:
      type: start-stop
      group: TACACS
  commands:
    commands_console:
      - commands: all
        type: start-stop
        group: TACACS
        logging: true
      - commands: 0
        type: start-stop
        logging: true
```

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-08-17 08:28 UTC, onurgashi approved these changes
LGTM!

2021-08-17 18:25 UTC, ClausHolbechArista requested changes

2021-08-17 18:25 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/aaa.yml
> +    commands_console:
I would move change this to `console` since you already nested it under `commands` keys. Same for `default`.

Same for `eos_cli_config_gen`

2021-08-17 18:25 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/aaa-accounting.j2
> +{%     if aaa_accounting.exec.console.group is arista.avd.defined %}
missing variable check for `aaa_accounting.exec.console.type`
Also missing variable checks below

2021-08-17 18:25 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/aaa-accounting.j2
> +| Commands - Console | {{ command_console.commands }} | {{ command_console.type }} | {% if command_console.group is arista.avd.defined %}{{ command_console.group }} {% else %} - {% endif %} | {% if c
The inline `if` makes it very hard to read. I suggest to move the logic up above the output line and set some temporary variables to use in the output.
Same below

2021-08-17 18:25 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/aaa-accounting.j2
>  | Type | Sub-type | Record | Accounting Stores | Logging |
Try to align the headings to the variables.
Ex.
`Sub-Type` -> `Commands`
`Record` -> `Record type`
`Accounting Stores` -> `Group`

2021-08-17 18:25 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/aaa-accounting.j2
> +{%             set aaa_accounting_commands_commands_console_cli = "aaa accounting commands " ~ command_default.commands ~ " console " ~ command_default.type %}
Missing variable checks.

2021-09-14 08:35 UTC, ClausHolbechArista approved these changes
LGTM

2021-09-14 09:53 UTC, merged