Add support for non-default port and protocol under logging options
aristanetworks/ansible-avd pull request #1138
Opened 2021-08-09 22:14 UTC by xaviramon

## Change Summary

This PR allows configuration of non-default port and protocol for syslog services under all VRFs.

Also, updated style on template generation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #626 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Current structure:
```
logging:
  vrfs:
    < vrf_name >:
      source_interface: < source_interface_name >
      hosts:
        - < syslog_server_1>
        - < syslog_server_2>
```
Is changed to following:
```
logging:
    vrfs:
        < vrf_name >:
          source_interface: < source_interface_name >
          hosts:
        < syslog_server_1 >:
          protocol: < tcp | udp (default udp) >
          ports:
            < custom_port_1 >
            < custom_port_2 >
        < syslog_server_2 >:
          ports:
            < custom_port_1 >
```
## How to test
Definition/Molecule

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-08-17 08:18 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/logging.j2
> +| {{ vrf }} | {{ host }} | {% if logging.vrfs[vrf].hosts[host].ports is arista.avd.defined %}{% for port in logging.vrfs[vrf].hosts[host].ports %} {{ port }} {%endfor%}{%else%}Default{%endif%} | {{ l
Could you please add some spacing between `{%%}`

2021-08-17 08:20 UTC, onurgashi requested changes
LGTM with the small fix of syntax. Wondering what's the mixture with upgrade tools in the PR?

2021-08-28 08:00 UTC, titom73 approved these changes
LGTM!

2021-08-28 08:02 UTC, titom73 commented
> LGTM with the small fix of syntax. Wondering what's the mixture with upgrade tools in the PR?

We should create a new and specific migration template as the current upgrade tool covers `eos_designs` only.

2021-09-15 08:40 UTC, onurgashi approved these changes

2021-09-15 09:59 UTC, merged