Feat(eos_designs): Add support for reusing MLAG peer vlan for IBGP/IGP peering
aristanetworks/ansible-avd pull request #1142
Opened 2021-08-10 10:17 UTC by ClausHolbechArista

## Change Summary

Add support for reusing MLAG peer vlan for IBGP/IGP peering

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #1057 

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

```yaml
    # Underlay L3 peering SVI interface id
    # If set to false or the same vlan as mlag_peer_vlan the mlag_peer_vlan will be used for L3 peering.
    mlag_peer_l3_vlan: < 0-4094 | false | default -> 4093 >
```
## How to test

Used in DC1-POD1 in 5stage molecule scenario

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [X] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-08-17 08:16 UTC, onurgashi requested changes
I see that you have defined MLAG-PEERS on all your neighbours, but I don't see the peer-group. Could you please either create one or reuse the MLAG-IPv4-UNDERLAY-PEER?

Also regarding mlag_peer_vlan don't we use 4093 as default for such peering over peer-link?

2021-08-17 16:39 UTC, ClausHolbechArista commented
> I see that you have defined MLAG-PEERS on all your neighbours, but I don't see the peer-group. Could you please either create one or reuse the MLAG-IPv4-UNDERLAY-PEER?
> 
> Also regarding mlag_peer_vlan don't we use 4093 as default for such peering over peer-link?

@onurgashi I don't follow these comments. Note that GitHub removes a lot of the config (click on the blue sections).
Please comment directly on the files, so I know what you have in mind. Thanks

2021-08-17 16:58 UTC, onurgashi commented
> I see that you have defined MLAG-PEERS on all your neighbours, but I don't see the peer-group. Could you please either create one or reuse the MLAG-IPv4-UNDERLAY-PEER?

Never mind, you're right for both actually. Just realised now. Thanks for the PR.

2021-08-17 16:58 UTC, onurgashi approved these changes

2021-08-27 12:21 UTC, carlbuchmann approved these changes

2021-08-27 12:22 UTC, merged