Feat: Add support for VPN import prunning
aristanetworks/ansible-avd pull request #1173
Opened 2021-09-06 08:22 UTC by titom73

## Change Summary

Add support for VPN import prunning for EVPN deployments.

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_cli_config_gen`
`arista.avd.eos_designs`

## Proposed changes

__CLI Config Gen__

```yaml
router_bgp:
  address_family_evpn:
    route:
      import:
        match_failure:
          action: discard
```

__EOS Designs__

TBC

```yaml
...
```

## How to test

Refer to molecule

## Checklist

### User Checklist

- [x] eos_cli_config_gen implementation
- [x] eos_cli_config_gen molecule update
- [ ] eos_designs implementation
- [ ] eos_designs molecule update

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2021-09-07 12:20 UTC, ClausHolbechArista commented
Looks good. I took a look at the CLI, and we could flatten this a lot, since there are no alternative keywords:
```cli
ld001(config-router-bgp-af)#route ?
  import  Configure the importing of VPN routes
  type    NLRI route type

ld001(config-router-bgp-af)#route import ?
  match-failure  Configure how to handle VPN routes with no matching VRF import Route Targets

ld001(config-router-bgp-af)#route import match-failure ?
  action  Configure the action to perform

ld001(config-router-bgp-af)#route import match-failure action ?
  discard  Discard the route

ld001(config-router-bgp-af)#route import match-failure action discard ?
  <cr>  
```
So it _could_ be flattened to `route.import_match_failure_action: discard`.

2021-09-08 07:23 UTC, titom73 commented
Thanks for reviewing this PR. I have updated `eos_cli_config_gen` as per your comment

2021-09-09 05:40 UTC, ClausHolbechArista requested changes

2021-09-09 05:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/router-bgp.j2
> +- VPN import prunning is disbaled
There is a typo here, "disabled".

2021-09-09 05:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/router-bgp.j2
> +{%         if router_bgp.address_family_evpn.route.import_match_failure_action is arista.avd.defined('discard') %}
I don't think it is on purpose, that you enclose this `if` inside the `evpn_hostflap_detection`. So move this above the `if` in line 157, and then add a new `if` around this section (including 1 leading empty line) `if router_bgp.address_family_evpn.route.import_match_failure_action is arista.avd.defined`. 
This extra `if` serves the purpose of not changing documentation for all devices where this feature is not specifically enabled or disabled.

2021-09-11 11:11 UTC, ClausHolbechArista approved these changes
Updated a typo and refreshed artifacts.
LGTM!

2021-09-15 08:31 UTC, onurgashi approved these changes

2021-09-15 08:39 UTC, merged