Feat(eos_cli_config_gen): Add support for LDP IGP sync
aristanetworks/ansible-avd pull request #1224
Opened 2021-09-27 14:48 UTC by emilarista

## Change Summary

Adds support for mpls ldp igp sync command on Ethernet interfaces.

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

Adds key under interface to render mpls ldp igp sync command:
 
´´´
EthernetX:
    mpls:
      ip: true
      ldp:
        interface: true
        igp_sync: true
´´´

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2021-09-27 16:25 UTC, onurgashi approved these changes
LGTM!

2021-09-29 05:49 UTC, ClausHolbechArista reviewed
LGTM! I will change to draft until we are ready to merge for v3.1.

2021-10-30 10:10 UTC, ClausHolbechArista requested changes

2021-10-30 10:10 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +        ldp_igp_sync: < true | false >
typo. Should be `igp_sync`

2021-10-30 10:10 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mpls-interfaces.j2
> +| Interface | MPLS IP Enabled | LDP Enabled | LDP-IGP Sync Configured |
Change heading to `IGP Sync`

2021-11-01 08:19 UTC, emilarista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +        ldp_igp_sync: < true | false >
Fixed.

2021-11-01 08:19 UTC, emilarista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mpls-interfaces.j2
> +| Interface | MPLS IP Enabled | LDP Enabled | LDP-IGP Sync Configured |
Fixed.

2021-11-01 08:47 UTC, ClausHolbechArista requested changes

2021-11-01 08:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mpls-interfaces.j2
> +{%             set row_ldp_igp_sync = ethernet_interfaces[ethernet_interface].mpls.ldp.igp_sync | arista.avd.default(false) %}
default should be `-`.

2021-11-01 09:43 UTC, emilarista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mpls-interfaces.j2
> +{%             set row_ldp_igp_sync = ethernet_interfaces[ethernet_interface].mpls.ldp.igp_sync | arista.avd.default(false) %}
Fixed.

2021-11-01 13:36 UTC, ClausHolbechArista approved these changes
LGTM

2021-11-01 13:36 UTC, merged