Fix(eos_cli_config_gen): Jinja2 template on IPv6 standard ACL (#1242)
aristanetworks/ansible-avd pull request #1251
Opened 2021-10-09 06:49 UTC by c-po

## Change Summary

Remove superfluous `}` in Jinja2 template

## Related Issue(s)

Fixes #1242 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

## How to test

Buildin Molecule Tests

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2021-10-09 16:29 UTC, tgodaA approved these changes
LGTM! Thank you for submitting.

2021-10-09 16:42 UTC, tgodaA commented
I just found that no molecule scenarios was added for this. Please add molecule scenario for ipv6-standard-access-lists. I found that documentation was already done: https://avd.sh/en/releases-v3.x.x/roles/eos_cli_config_gen/index.html#ipv6-standard-access-lists

2021-10-09 16:58 UTC, c-po commented
Molecule is added in #1243

2021-10-09 18:54 UTC, tgodaA commented
#1243 is a Feature update. Currently we are only looking to fix bugs. So we need to fix this issue first before the new release. So please add molecule to this PR. That should fix the problem and then we can review the Feature update (as it is dependent on Fix). So please add the molecule to this Fix.

2021-10-11 06:39 UTC, c-po commented
Will rebase #1243 to devel after this one is merged to fix merge conflicts.

2021-10-11 14:37 UTC, tgodaA approved these changes
LGTM!

2021-10-12 08:24 UTC, emilarista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/ipv6-access-lists.yml
> +        action: "permit ip 2001:db8::/64"
permit/deny >ip< is not correct syntax for standard ACL. Remove the "ip" and it will work. Otherwise LGTM!

2021-10-12 08:38 UTC, c-po commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/ipv6-access-lists.yml
> +        action: "permit ip 2001:db8::/64"
Well - it was then incorrect from the days of the beginning. will fix it.

2021-10-12 08:57 UTC, emilarista approved these changes
LGTM!

2021-10-12 15:29 UTC, tgodaA commented
Thank you for the changes! Everything LGTM!

2021-10-15 01:34 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/ipv6-access-lists.yml
> +        action: "permit fe90::/64"
ipv6_access_lists test case produces invalid EOS output.
Please update to `action: "permit ipv6 fe90::/64 any"`

2021-10-15 01:35 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/ipv6-access-lists.yml
> +        action: "deny fe80::/64"
ipv6_access_lists test case produces invalid EOS output.
Please update to `action: "deny ipv6 fe80::/64 any"`

2021-10-15 01:36 UTC, carlbuchmann requested changes
Please correct test case to produce valid EOS output.

2021-10-15 05:33 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/ipv6-access-lists.yml
> +        action: "permit fe90::/64"
@c-po @carlbuchmann I will fix this now and merge the rest. The incorrect CLI was not part of your PR, but has been there for a while.

2021-10-15 05:56 UTC, merged