Doc(how-to): Update documentation
aristanetworks/ansible-avd pull request #1273
Opened 2021-10-21 14:15 UTC by ClausHolbechArista

## Change Summary

Update documentation

## Related Issue(s)

## Component(s) name

`arista.avd`

## Proposed changes

- [x] Update installation documentation
- [x] Update release-notes to reflect new requirements and constraints

## How to test

N/A

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2021-10-21 16:19 UTC, carlbuchmann approved these changes
LGTM

2021-10-21 21:03 UTC, tgodaA commented on ansible_collections/arista/avd/docs/installation/requirements.md
>  --8<--
May I know if this was a typo or it has some significance?

2021-10-21 21:21 UTC, tgodaA approved these changes
LGTM!

2021-10-22 06:15 UTC, titom73 requested changes

2021-10-22 06:15 UTC, titom73 commented on ansible_collections/arista/avd/docs/installation/collection-installation.md
> +!!! Warning: If you have an `ansible.cfg` file in the directory where you run `ansible-galaxy`, it may affect the directory under which the collection and dependencies will be installed.
Syntax for mkdoc admonition is not like that, you should update it with:

```
!!! warning "your optional title to replace warning"
	lorem ipsum ....
```

(https://squidfunk.github.io/mkdocs-material/reference/admonitions/#changing-the-title)

2021-10-22 06:15 UTC, titom73 commented on ansible_collections/arista/avd/docs/installation/requirements.md
>  --8<--
It is syntax to include content of a file, so in this situation, there is no need to update this section each time we change requirements.txt file.

2021-10-22 08:37 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/docs/installation/collection-installation.md
> +!!! Warning: If you have an `ansible.cfg` file in the directory where you run `ansible-galaxy`, it may affect the directory under which the collection and dependencies will be installed.
Fixed, same for note in the same file.

2021-10-22 09:17 UTC, merged