Feat(eos_cli_config_gen): Add AAA Authentication Policy Lockout
aristanetworks/ansible-avd pull request #1351
Opened 2021-11-22 19:57 UTC by ccsnw

## Change Summary

Added AAA Auth Policy Lockout option

## Related Issue(s)

Fixes #1345

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
added policy lockout options

```
aaa_authentication:
  login:
    default: < group group_name | local | none > < group group_name | local | none >
    console: < group group_name | local | none > < group group_name | local | none >
  enable:
    default: < group group_name | local | none > < group group_name | local | none >
  dot1x:
    default: < group group_name >
  policies:
    on_failure_log: < true | false >
    on_success_log: < true | false >
    local:
      allow_nopassword: < false | true >
    lockout:
      failure: < 1-255 >
      duration: < 1-4294967295 >
      window: < 1-4294967295 >
```

## How to test
molecule run

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2021-11-22 21:03 UTC, ClausHolbechArista requested changes
Almost there. Please adjust the config template a bit.

2021-11-22 21:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/aaa-authentication.j2
> +{%         set lockout_cli = "aaa authentication policy lockout failure " ~ aaa_authentication.policies.lockout.failure ~ " duration " ~ aaa_authentication.policies.lockout.duration %}
this code is not super clear. I would first add the common part. Then do the test for the optional window command and then add the duration last. This way you don't have the same stuff multiple times.

2021-11-23 07:40 UTC, ClausHolbechArista approved these changes
LGTM

2021-11-23 09:48 UTC, onurgashi approved these changes
LGTM!

2021-11-23 13:29 UTC, merged