Fix doc: Two small changes to documentation for eos_designs role
aristanetworks/ansible-avd pull request #1393
Opened 2021-12-07 17:32 UTC by PhirePhly

## Change Summary

Fix two typos in the eos_designs documentation:
* interface_descriptions variable is spelled incorrectly in node_types.md
* endpoint_ports is required to be defined in connected_endpoints.md

## Related Issue(s)

## Component(s) name

`arista.avd.eos_designs`

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2021-12-07 17:48 UTC, PhirePhly commented
Does the bot not like that I included an optional scope?

2021-12-07 19:28 UTC, PhirePhly commented
Goodness. Sorry about the title edit spam on the Title

2021-12-10 09:59 UTC, xaviramon commented on ansible_collections/arista/avd/roles/eos_designs/doc/connected-endpoints.md
>          # List of port(s) connected to switches
Could you please add the "| required" tag here and also in next variable, "switches"?

2021-12-10 10:05 UTC, xaviramon requested changes
Thank you for your PR, Kenneth!
That's a good catch, not all required variables are really marked with the required tag. I believe it was somehow assumed that defined a new server will require switches and ports, but it is much better if we explicitly say it.
Please, add the tag in the variables I mentioned. Otherwise, looks good to me and I will approve it after these changes.

2021-12-10 15:27 UTC, PhirePhly commented
So interestingly, while the switch and switch port are conceptually required, I couldn't find any syntactic requirement for them. The lack of the endpoint_ports caused a build failure, but you can define a batch of servers and not allocate them to a switch right away. I'll make your requested changes and fix both commit messages now that I better understand the title semantics.

Where I tripped on this is because I'm trying to use AVD to build an L2 EVPN fabric for an Internet Exchange Point. The endpoints are Internet edge peering and outside our autonomous system, so I have no idea what port on their device they're using. So ideally I think we should make the endpoint ports optional, but I'm trying to go one step at a time here.

2021-12-10 16:27 UTC, xaviramon commented
I took another look. If you don't have ``switches`` and ``switch_ports`` documentation is generated correctly. If ``switch_ports`` is missing you will face an error, so it is validated:
```
TASK [arista.avd.eos_designs : Generate device configuration in structured format] ***********************************************************************************************
Friday 10 December 2021  17:20:03 +0100 (0:00:00.768)       0:00:07.330 ******* 
Friday 10 December 2021  17:20:03 +0100 (0:00:00.768)       0:00:07.329 ******* 
ok: [POD1_SPINE01 -> localhost]
ok: [POD1_SPINE02 -> localhost]
fatal: [POD1_LEAF01A -> localhost]: FAILED! => {"msg": "'dict object' has no attribute 'switch_ports'"}
```

For your specific case, I might suggest they use as ``endpoint_ports`` whatever value helps them to identify the connection on the other peer, as this value is only used in the description field:
```
my_cool_server:
  cool_1:
    rack: RACK_TEST
    adapters:
      - speed: "10g auto"
        endpoint_ports: [ blah ]
        switch_ports: [ eth7 ]
        switches: [ POD1_LEAF01A ]
        mode: access
        vlans: "3"
```
Generated documentation:
```
#### L2

| Interface | Description | Mode | VLANs | Native VLAN | Trunk Group | Channel-Group |
| --------- | ----------- | ---- | ----- | ----------- | ----------- | ------------- |
| eth7 |  cool_1_blah | access | 3 | - | - | - |
```
Generated config:
```
interface eth7
   description cool_1_blah
   no shutdown
   speed 10g auto
   switchport
   switchport access vlan 3
   switchport mode access
!
```

2021-12-10 19:03 UTC, PhirePhly commented
Good point. Once the switch is assigned and the endpoint gets pulling into the switches state, the lack of the port assignment is a problem.

I've force pushed over my previous branch with your requested changes.

2021-12-10 20:17 UTC, tgodaA commented
To add up to your discussion. I just found that ```server_ports``` or ```endpoint_ports``` is required. Because if we don't define ```endpoint_ports``` then the default value is taken from ```server_ports```. But this looks good to me to set *endpoint_ports* to required.

2021-12-10 20:24 UTC, tgodaA commented
Also, change your PR title to Fix documentation rather than saying two or three suggestions.

I found one more typo in the same connected-endpoints. 
![image](https://user-images.githubusercontent.com/88734745/145636388-becacc7f-fbf3-4d83-bc7c-0ca440e358ed.png)
I don't think we need:
```yaml
< port_profile_2 >:
  mode: < access | dot1q-tunnel | trunk >
  vlans: < vlans as string >
```

This is a port_profile_2 which should be defined under port_profiles knob but accidentally sitting under adapters settings.

2021-12-10 23:11 UTC, PhirePhly commented
I've changed the pull request title. 

`port_profile_2` is outside the scope of what I'm working on.

2021-12-13 12:04 UTC, ClausHolbechArista approved these changes
LGTM!
Thank you for this valuable contribution! It will save others the trouble you might have had.

2021-12-13 14:14 UTC, carlbuchmann approved these changes
LGTM!

2021-12-13 14:15 UTC, merged