Doc(eos_designs): Minor documentation fixes
aristanetworks/ansible-avd pull request #1454
Opened 2022-01-25 02:14 UTC by PhirePhly

## Change Summary

A few doc fixes I've collected while reading things.

Only behavior change is the removal of peer_interface being a required connected endpoint parameter, since this *really* isn't playing nice with my use case.

## Component(s) name

`arista.avd.eos_designs`
`arista.avd.eos_cli_config_gen`

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-01-25 07:24 UTC, ClausHolbechArista requested changes
You are mixing many types of changes in this PR. 
- Some documentation changes
- Rendering of `access_lists` in `eos_cli_config_gen`
- Making `endpoint_ports` optional in `eos_designs`
Please split them into separate PRs. 
Also please add molecule coverage for the optional endpoint_ports (just remove the endpoint_ports from some existing connected_endpoint).

2022-01-25 07:24 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/doc/connected-endpoints.md
> +    enabled: < true | false >
From the heading above:
```yaml
# Each profile can support all or some of the following keys according to your own needs.
# Keys are the same used under endpoints adapters. Keys defined under endpoints adapters take precedence.
```
I don't think we need to maintain the full list of keys in two places. Maybe we could even cut down the port_profile to  `< endpoint_adapter_config >` or something.

2022-01-25 07:24 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/templates/connected_endpoints/ethernet-interfaces.j2
> +{%                     set peer_interface = endpoint_ports[loop.index0] | arista.avd.default('N/A') %}
This will show up in description as well, so I suggest just using an empty string as the default value.

2022-01-27 14:20 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_designs/doc/connected-endpoints.md
> +        # Interface names of the connected endpoint for documentation | optional
This is not optional. If you don't specify this the playbook will stop proceeding further. Either we need to specify ```endpoint_ports``` or ```server_ports```. I think ```server_ports``` is a old knob which we are supporting for backward compatibility.

2022-01-27 14:31 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_designs/doc/connected-endpoints.md
> +        storm_control:
This is already present in ```<port_profile>```

2022-01-27 14:41 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
>        < tx-queue-id >:
I think it's better to remove the lines 2301-2303. This is duplicating the same data.

Let's see what others will say. Same for above <tx-queue-id>.

We should try to minimize the duplication from now. Anyway, by specifying ```<tx-queue-id>``` the user might know the parent knob is supporting dictionaries.

2022-02-02 17:47 UTC, PhirePhly commented
Thanks for the input folks. I shouldn't have dumped these together; I knew better than that and this was inappropriate. I'll break this apart, and feel free to ignore me while working on the new release.

2022-02-03 08:25 UTC, ClausHolbechArista commented
> Thanks for the input folks. I shouldn't have dumped these together; I knew better than that and this was inappropriate. I'll break this apart, and feel free to ignore me while working on the new release.

At least your commits look well structured, so you can just cherry pick these to separate PRs and fix the comments from there.

2022-02-10 21:51 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_designs/doc/connected-endpoints.md
> +        # Interface names of the connected endpoint for documentation | optional
You can set this comment to ```# Local endpoint port(s) | required if server_ports is not set```

2022-03-25 22:51 UTC, closed without merging