Feat(eos_cli_config_gen): Add support for bgp neighbor peer filter
aristanetworks/ansible-avd pull request #1558
Opened 2022-03-02 14:13 UTC by danieltudares

## Change Summary

Adding support for BGP neighbor interface peer-filter

## Related Issue(s)

Fixes #1553 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

1. Add support for BGP neighbor interface peer filter.
2. Make `peer_filter` a dependency of `peer_group` (can't add peer_filter without adding peer_group) 
3. Make 'remote_as` a dependency of `peer_group` (can't add remote_as without adding peer_group)
4. Remove `description` field from `README.md` as this feature is not available (not supported on CLI).
5. Adding molecule test (bgp neighbor interfaces was not being tested with molecule before).

Current model: 

```yaml
  neighbor_interfaces:
    < interface >:
      peer_group: < peer_group_name >
      remote_as: < bgp_as >
      description: "< description as string >"
```

Proposed model: 

```yaml
  neighbor_interfaces:
    < interface >:
      peer_group: < peer_group_name >
      remote_as: < bgp_as >
      peer_filter: <peer_filter>
```

## How to test

```yaml
router_bgp:
  as: 65101
  neighbor_interfaces:
    Ethernet2:
      peer_group: PG-FOO-v4
      remote_as: 65102
    Ethernet3:
      peer_group: PG-FOO-v4
      peer_filter: PF-BAR-v4
```

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-03-03 10:15 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/router-bgp.j2
> +{%         if router_bgp.neighbor_interfaces[neighbor_interface].peer_group is arista.avd.defined and router_bgp.neighbor_interfaces[neighbor_interface].remote_as is arista.avd.defined %}
you are changing the logic here, so peer-group is no longer optional. Is that on prupose?
A simpler change to do what you want, was just to add and `elif` after the old line 128 and check for `peer_filter`.

2022-03-03 10:18 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/router-bgp.j2
> +{%         if router_bgp.neighbor_interfaces[neighbor_interface].peer_group is arista.avd.defined and router_bgp.neighbor_interfaces[neighbor_interface].remote_as is arista.avd.defined %}
Nevermind. I can see that the old logic was not correct.
From EOS CLI:
`[no|default] neighbor interface INTFS peer-group PG ( ( remote-as ( AS_PLAIN_NUM | AS_DOT_NUM ) ) | ( peer-filter PEER_FILTER ) )`
`

2022-03-03 10:20 UTC, ClausHolbechArista approved these changes
LGTM

2022-03-03 15:44 UTC, emilarista requested changes

2022-03-03 15:44 UTC, emilarista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/router-bgp-base.md
> +   neighbor interface Ethernet3 peer-group PG-FOO-v4 peer_filter PF-BAR-v4
This cli doesn't work. See comment in template.

2022-03-03 15:44 UTC, emilarista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/router-bgp.j2
> +   neighbor interface {{ neighbor_interface }} peer-group {{ router_bgp.neighbor_interfaces[neighbor_interface].peer_group }} peer_filter {{ router_bgp.neighbor_interfaces[neighbor_interface].peer_fi
peer_filter cli item needs to change to peer-filter.

2022-03-03 17:34 UTC, danieltudares commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/router-bgp.j2
> +   neighbor interface {{ neighbor_interface }} peer-group {{ router_bgp.neighbor_interfaces[neighbor_interface].peer_group }} peer_filter {{ router_bgp.neighbor_interfaces[neighbor_interface].peer_fi
good catch, thanks! fixed now

2022-03-04 12:34 UTC, emilarista approved these changes
LGTM!

2022-03-04 18:26 UTC, merged

2022-03-04 18:26 UTC, carlbuchmann reviewed
LGTM!