Feat(eos_cli_config_gen): vlan_int virt ip order
aristanetworks/ansible-avd pull request #1579
Opened 2022-03-10 21:49 UTC by ryanmerolle

## Change Summary

Part of the various changes for getting output config to reflect config order on box.

## Related Issue(s)

Fixes #1572

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

Reorder `ip address virtual` and 'ip virtual-router address` lines under vlan_interfaces.

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-03-11 01:36 UTC, ryanmerolle commented
The only failure seems like a docker image pull failure.  If you wait for this one to be reviewed/merged as one of the last, I can fetch upstream which should trigger another ci job run.

2022-03-11 07:09 UTC, ClausHolbechArista requested changes

2022-03-11 07:09 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/vlan-interfaces.j2
>  {%     if vlan_interfaces[vlan_interface].eos_cli is arista.avd.defined %}
eos_cli should come last, since it can contain _any_ config, and the user must be able to override any of the generated config.

2022-03-11 14:31 UTC, ryanmerolle commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/vlan-interfaces.j2
>  {%     if vlan_interfaces[vlan_interface].eos_cli is arista.avd.defined %}
Ah my mistake.  Not intentional.  Fixed now.

2022-03-11 19:04 UTC, ryanmerolle commented
This should be ready to review now.

2022-03-14 06:55 UTC, ClausHolbechArista approved these changes
LGTM

2022-03-15 10:56 UTC, emilarista approved these changes
LGTM!

2022-03-15 11:05 UTC, ryanmerolle commented
Can we merge this please

2022-03-15 11:46 UTC, merged