Interface Validation Improvements
aristanetworks/ansible-avd pull request #1585
Opened 2022-03-14 17:59 UTC by perimore

## Change Summary

Changes to check interface state against the intended state. Today the validation code will simply check if a defined interface is up and fail if it is down. 

This change will take into account if the interface has been set to "enabled: false" and check accordingly.

## Related Issue(s)

none

## Component(s) name

`arista.avd.eos_validate_state`

## Proposed changes
If an interface is set to "enabled: true", the assert will check that an interface is up/up.

If an interface is set to "enabled: false", the assert will check that an interface is adminDown/down.

Otherwise the assert will fail.

This applies to ethernet, vlan and port-channel interfaces but here is an example from ethernet:

```
- name: Validate Ethernet interfaces state
  assert:
    that: |
      ( interfaces_state.stdout[0].interfaceDescriptions[ethernet_interface.key].interfaceStatus == 'up' and
      interfaces_state.stdout[0].interfaceDescriptions[ethernet_interface.key].lineProtocolStatus == 'up' and
      not ethernet_interfaces[ethernet_interface.key].shutdown
      ) or
      ( interfaces_state.stdout[0].interfaceDescriptions[ethernet_interface.key].interfaceStatus == 'adminDown' and
      interfaces_state.stdout[0].interfaceDescriptions[ethernet_interface.key].lineProtocolStatus == 'down' and
      ethernet_interfaces[ethernet_interface.key].shutdown
      )
    fail_msg: "interface shutdown: {{ ethernet_interfaces[ethernet_interface.key].shutdown }}
      - interface status: {{ interfaces_state.stdout[0].interfaceDescriptions[ethernet_interface.key].interfaceStatus }}
      - line protocol status: {{ interfaces_state.stdout[0].interfaceDescriptions[ethernet_interface.key].lineProtocolStatus }}"
```

## How to test
Code was tested with interfaces that are enabled but shutdown via the CLI, disabled but "no shut" in the CLI to test a fail. And enabled and "no shut" as expected in the CLI for a pass.

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-03-14 18:30 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_validate_state/tasks/interface_state.yml
> +    that: |
I don't think you need the pipe here, since it is not a multi-line string. As long as you indent you should be good.

2022-03-14 18:33 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_validate_state/tasks/interface_state.yml
> +    fail_msg: "interface shutdown: {{ port_channel_interfaces[port_channel_interface.key].shutdown }}
you are combining a string and a list into the same variable. I doubt this will work as intended.

2022-03-17 11:05 UTC, perimore commented on ansible_collections/arista/avd/roles/eos_validate_state/tasks/interface_state.yml
> +    that: |
fixed in the latest commit. Also moved the hyphens to the end of line in the fail_msg variable to avoid any confusion that it might be a list.

2022-03-22 00:24 UTC, carlbuchmann approved these changes
Noticed an issue in the fail result not outputting correctly example:
![image](https://user-images.githubusercontent.com/20460062/159384457-0f2ab87d-31c7-4d19-8d53-52990ef651eb.png)

@[perimore](https://github.com/perimore) I will try and resolve it tomorrow.

2022-03-22 00:32 UTC, carlbuchmann requested changes
Need to correct fail message in `generate_state_report_results.j2`

2022-03-24 14:13 UTC, perimore commented
> Noticed an issue in the fail result not outputting correctly example: ![image](https://user-images.githubusercontent.com/20460062/159384457-0f2ab87d-31c7-4d19-8d53-52990ef651eb.png)
> 
> @[perimore](https://github.com/perimore) I will try and resolve it tomorrow.

I believe that's the description of the test, i.e. the expected test pass. So if interface = enabled, status should be up and up. Or if interface = disabled, status should be adminDown and protocol not up. "Not up" as state can be "down" or "notPresent" if a txcr is not present.

2022-03-25 01:39 UTC, carlbuchmann commented
> ` [740998d](/aristanetworks/ansible-avd/pull/1585/commits/740998d9aa7c2703409577ffc3aeba17e8107c53)`

@perimore - I think I mislead you in my comment! I just improve to comment to be more concise about the test! see commit: 
740998d

2022-03-25 01:43 UTC, carlbuchmann approved these changes
LGTM!

2022-03-25 13:11 UTC, ClausHolbechArista approved these changes
LGTM

2022-03-25 13:12 UTC, merged