Feat(eos_cli_config_gen): BGP VRF IPv4 RM support
aristanetworks/ansible-avd pull request #1759
Opened 2022-05-03 17:20 UTC by danieltudares

## Change Summary

Support AVD data model for BGP VRF address-family IPv4 Route-maps

## Related Issue(s)

Fixes #1756 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

Support for knob to apply route maps (in/out) under `router_bgp > vrfs > address_families > neighbor` :

```yaml
router_bgp:
  vrfs:
    <vrf>:
      address_families:
        < address_family >:
          neighbors:
            < neighbor_ip_address >:
              route_map_out: < route-map name >
              route_map_in: < route-map name >
```

## How to test

molecule

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-05-04 10:46 UTC, ClausHolbechArista approved these changes
LGTM

2022-05-05 13:23 UTC, ClausHolbechArista requested changes

2022-05-05 13:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_v4.0/documentation/devices/router-bgp-v4-evpn.md
> +<<<<<<< HEAD
this looks like a bad rebase / merge.

2022-05-05 13:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_v4.0/intended/configs/router-bgp-v4-evpn.cfg
> +<<<<<<< HEAD
this looks like a bad rebase / merge.

2022-05-05 13:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/router-bgp.j2
> +{%                 if router_bgp.vrfs[vrf].address_families[address_family].neighbors[neighbor].route_map_in is arista.avd.defined %}
code is duplicated here. I think your rebase went wrong.

2022-05-05 13:27 UTC, danieltudares commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_v4.0/documentation/devices/router-bgp-v4-evpn.md
> +<<<<<<< HEAD
yeah I saw it. Looks like change #1746 affected this change and I need to make some other changes. I will convert this PR into a draft while I sort this.

2022-05-05 14:33 UTC, closed without merging

2022-05-05 15:07 UTC, danieltudares commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_v4.0/documentation/devices/router-bgp-v4-evpn.md
> +<<<<<<< HEAD
End up messing up this PR pretty bad. I decided to reopen a clean new one #1763 . Sorry for making you review the same code twice Claus!

2022-05-05 15:08 UTC, danieltudares commented
Closing this issue and reopening a new clean one #1763 to solve the merge conflicts and some jinja code improvements.