Implement full JSON support for group_vars
aristanetworks/ansible-avd pull request #181
Opened 2020-07-02 07:15 UTC by titom73

## Description

Update AVD to support JSON as input structure as it is fully supported by Ansible.

Fix issue #180

## Changes

- Update VLANS and SVI templating engine to force
- Add a testing scenario to validate futur changes

2020-07-03 15:04 UTC, carlbuchmann commented
@titom73 & @ankudinov - I agree with the proposed changes, this is also related to issue #140 raised by @ankudinov , is there other changes required?

2020-07-03 15:38 UTC, titom73 commented
PR only provides a fix by protecting group_vars value and force type for everything coming from JSON data: Keys from dictionary where `int` is expected.

I think #140 would require more work as we have to go through all templates to cast all variables to `int` when required.

2020-07-06 18:09 UTC, carlbuchmann requested changes

2020-07-06 18:09 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/evpn-fabric-l3leaf-yml.j2
> +{% include 'base/management-api-http.j2' %} #}
@titom73 please remove "#}"

2020-07-06 18:24 UTC, carlbuchmann approved these changes
LGTM and tested with AVD Example

2020-07-06 18:38 UTC, merged