Feat(eos_designs): Only configure vlans in use by connected endpoints or downstream L2 switches
aristanetworks/ansible-avd pull request #1821
Opened 2022-05-24 13:58 UTC by ClausHolbechArista

## Change Summary

Only configure vlans in use by connected endpoints or downstream L2 switches

## Related Issue(s)

@perimore does this address #1575 ?

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

```
< node_type_key >:
  defaults:
    filter:
      # Only configure VLANs in use by connected endpoints
      # or by connected endpoints on downstream L2 switches.
      only_vlans_in_use: < true | false | default -> false >
```

## How to test

Added molecule coverage:
- L2 switch (verifying that upstream switch still keeps all vlans used by local ports)
- L3 switch with downstream L2 switch (not pruning since all vlans in use on other downstream l2 switch)
- L3 switch with only some vlans deployed based on locally connected endpoints (verifying that some vlans are removed)

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-06-01 08:28 UTC, perimore commented
This partially addresses #1575 with respect to L2 filtering but #1575 also calls for the pruning of VLANs and VRFs from L3 device if there are no endpoints requiring the services.

2022-07-14 09:00 UTC, ClausHolbechArista commented
> This partially addresses #1575 with respect to L2 filtering but #1575 also calls for the pruning of VLANs and VRFs from an L3 device if there are no endpoints requiring the services.

@perimore re. #1575 I believe this PR addresses all of those points. It works on all devices that support "connected_endpoints" so `l3leaf` and `l2leaf` by default. It will both filter on the device's own `connected_endpoints` as well as any downstream devices.
See [this example](https://github.com/aristanetworks/ansible-avd/pull/1821/files#diff-b5119ecbc315e6623102a1674a7308141cd3dbd87d88d2fcc58965406b485327), where only two server vlans are configured, and all other vlans+vrfs+vnis are pruned away.

I would appreciate if you could find time to test this out.

2022-07-15 13:34 UTC, jonxstill requested changes, later dismissed
Other than the type issue, this looks good to me.

2022-07-15 13:34 UTC, jonxstill commented on ansible_collections/arista/avd/plugins/module_utils/eos_designs_facts.py
> +                        vlans.extend(map(int, self._range_expand(adapter_settings["vlans"])))
One of my topologies failed here due to `vlans` in my combined adapter settings being an int, not a string or list, which caused range_expand to choke on it.
```
ansible.errors.AnsibleFilterError: value must be of type list or str, got <class 'int'>
```
Easy fix would be:

```suggestion
                        vlans.extend(map(int, self._range_expand(str(adapter_settings["vlans"]))))
```
But I'm not sure if want to support lists of ranges in something as simple as a VLAN range.

2022-07-19 10:04 UTC, lermilov commented
Hi Claus! Cool PR. I have tested it with my own repos.
Few observations:
- SVIs are also removed from L3LEAF if they are not configured in the connected endpoints. I assume this is intentional, but better to document it.
- Interfaces/VLANs configured with structured_configuration at hostvar level are ignored (Carl calls it "Port-centric" approach =)). I think it is intentional too, but let's also document it.

2022-07-22 18:57 UTC, carlbuchmann commented
@lermilov - re: "Interfaces/VLANs configured with structured_configuration at hostvar level are ignored (Carl calls it "Port-centric" approach =)). I think it is intentional too, but let's also document it."

I refer to port-centric when configuring network ports i.e `custom_structured_configuration_ethernet_interfaces`.

And yes, let's document this behavior and mention that custom_structured_configuration for VLANs will be ignored.

2022-08-01 09:19 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/doc/fabric-topology.md
> +      # or downstream L2 switches.
```suggestion
      # Only configure VLANs, SVIs, VRFs in use by connected endpoints
      # or downstream L2 switches.
```

2022-08-01 09:28 UTC, ClausHolbechArista commented
> @lermilov - re: "Interfaces/VLANs configured with structured_configuration at hostvar level are ignored (Carl calls it "Port-centric" approach =)). I think it is intentional too, but let's also document it."
> 
> I refer to port-centric when configuring network ports i.e `custom_structured_configuration_ethernet_interfaces`.
> 
> And yes, let's document this behavior and mention that custom_structured_configuration for interfaces and VLANs will be ignored.

Anything implemented with custom_structured_configuration is not available to eos_designs. That goes for all features and is described under custom_structured_configuration.
I will add a general note about this only considering configuration managed by eos_designs. So excluding structured_config, custom_structured_config, raw_eos_cli, eos_cli and other custom configurations.

2022-08-01 09:30 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/doc/fabric-topology.md
> +      # or downstream L2 switches.
```suggestion
      # Only configure VLANs, SVIs, VRFs in use by connected endpoints or downstream L2 switches.
      # Note! This feature only considers configuration managed by eos_designs.
      # This excludes structured_config, custom_structured_config, raw_eos_cli, eos_cli, custom tempaltes, configlets etc.
```

2022-08-10 12:32 UTC, nielsjlarsen approved these changes
LGTM!

2022-08-11 12:17 UTC, carlbuchmann approved these changes
LGTM - tested with customer scenario.

2022-08-11 12:28 UTC, merged