Feat(eos_cli_config_gen): Support for MCS client commands
aristanetworks/ansible-avd pull request #1999
Opened 2022-08-15 22:45 UTC by sugetha24

## Change Summary

Add support for MCS client on CVX

```
mcs client
   no shutdown
   !
   cvx secondary blue
      server host 172.24.86.56
```

## Related Issue(s)

Fixes #1963

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Data Model:

```
mcs_client:
  shutdown: < true|false >
  cvx_secondary:
    name: blue
    server_host:
       - < IPv4_address >
       - < IPv4_address >
```

Eg:
```
mcs_client:
  shutdown: true
  cvx_secondary:
    name: blue
    server_host:
       - 172.24.86.56
```
## How to test
`molecule converge --scenario-name eos_cli_config_gen -- --limit mcs-client`

## Checklist

### User Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-08-17 05:26 UTC, ClausHolbechArista requested changes

2022-08-17 05:26 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +### MCS client
please fix this section to show the syntax. Not an example. More or less what you have in the PR description.

2022-08-17 05:26 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mcs-client.j2
> +MCS client is running
```suggestion
{%     elif mcs_client.shutdown is arista.avd.defined(false) %}

MCS client is enabled
{%     endif %}
```

2022-08-17 05:26 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mcs-client.j2
> +MCS client is shutdown
there is no variable `shut`. Should probably be `mcs_client.shutdown.
Also missing a blank line between the if and the text.
```suggestion
{%     if mcs_client.shutdown is arista.avd.defined(true) %}

MCS client is shutdown
```

2022-08-17 05:26 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mcs-client.j2
> +{%         set servers = mcs_client.cvx_secondary.server_hosts | arista.avd.default('-') | join(',') %}
```suggestion
{%         set servers = mcs_client.cvx_secondary.server_hosts | arista.avd.default('-') | join(', ') %}
```

2022-08-17 05:26 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/mcs-client.j2
> +{%         endif %}
No need for nested if checks.
```suggestion
{%     if mcs_client.cvx_secondary.name is arista.avd.defined %}
{%         set name = mcs_client.cvx_secondary.name %}
    !
    cvx secondary {{ name }}
{%         for server_host in mcs_client.cvx_secondary.server_hosts | arista.avd.natural_sort %}
        server host {{ server_host }}
{%         endfor %}
```

2022-08-18 07:24 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mcs-client.j2
> +MCS client is running
```suggestion
MCS client is enabled
```

2022-08-18 07:24 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mcs-client.j2
> +-
Typo
```suggestion

```

2022-08-18 17:03 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mcs-client.j2
> +MCS client is enabled
```suggestion
{%     elif mcs_client.shutdown is arista.avd.defined(false) %}

MCS client is enabled
{%     endif %}
```

2022-08-18 23:29 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/mcs-client.j2
> +{%         endfor %}
For my understanding (because I couldn't test it elsewhere). Would it be possible to share a screenshot of the output configured with multiple hosts.

2022-08-18 23:36 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/mcs-client.j2
> +{% endif %}
Two things here:
1) The indentation of the commands should be 3 spaces (it is 4 spaces)
2) Although it looks good (line 11-13). We don't need to save it in a var. If you believe, it will be used another time in this template, then save it in a var. (Optional)
```suggestion
{# MCS client #}
{% if mcs_client is arista.avd.defined %}
!
mcs client
{%     if mcs_client.shutdown is arista.avd.defined(true) %}
   shutdown
{%     elif mcs_client.shutdown is arista.avd.defined(false) %}
   no shutdown
{%     endif %}
{%     if mcs_client.cvx_secondary.name is arista.avd.defined %}
   !
   cvx secondary {{ mcs_client.cvx_secondary.name }}
{%         for server_host in mcs_client.cvx_secondary.server_hosts | arista.avd.natural_sort %}
      server host {{ server_host }}
{%         endfor %}
{%     endif %}
{% endif %}
```

2022-08-18 23:36 UTC, tgodaA commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/mcs-client.cfg
> +        server host leaf2.atd.lab
I commented regarding the command indentation in the template.

2022-08-18 23:38 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +        - < IP | hostname >
Please make sure to keep same increase in indentation for every level.
```suggestion
mcs_client:
  shutdown: < true | false >
  cvx_secondary:
    name: < name >
    server_hosts:
      - < IP | hostname >
      - < IP | hostname >
```

2022-08-19 17:57 UTC, sugetha24 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/mcs-client.j2
> +{%         endfor %}
![Screen Shot 2022-08-19 at 10 57 31 AM](https://user-images.githubusercontent.com/4846759/185679141-2426e99a-6a9b-495c-ab47-1b7e1a3e3423.png)

2022-08-22 05:52 UTC, ClausHolbechArista approved these changes
LGTM

2022-08-22 12:58 UTC, tgodaA approved these changes
LGTM

2022-08-22 14:56 UTC, merged