Feat(eos_cli_config_gen): Add schema for local_users
aristanetworks/ansible-avd pull request #2020
Opened 2022-08-30 08:07 UTC by KonikaChaurasiya-GSLab

## Add schema for data model

## Checklist

### Contributor Checklist

- [ ] Create schema fragment matching data model described in README.md and README_v4.0.md
  - README.md is most complete with all keys. README_v4.0 includes partial data models after conversion to lists.
  - Schema fragment path is `roles/eos_cli_config_gen/schemas/schema_fragments/<data_model_key>.schema.yml`.
  - Copy line 1-5 from another schema (comments and outer type:dict).
  - Refer to [schema documentation](https://avd.sh/en/devel/docs/input-variable-validation-BETA.html) for syntax and/or use YAML Lint plugin from Redhat in VSCode.
  - Use `convert_types` on value that could be mixed type or misinterpreted like integers and numeric strings.
- [ ] If the data model has been converted from wildcard dicts:
  - Add `convert_types: ['dict']` to the schema.
  - Remove `convert_dicts` from the `templates/eos/<>.j2` and `templates/documentation/<>.j2` templates.
- [ ] Run `molecule converge -s build_schemas_and_docs` to update schema and documentation.
- [ ] Test by running `molecule converge -s eos_cli_config_gen` and verify no errors or changes to generated configs/docs.

### Reviewer Checklist

- Reviewer 1:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

- Reviewer 2:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

2022-08-30 08:44 UTC, ClausHolbechArista requested changes

2022-08-30 08:44 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/local_users.schema.yml
> +type: dict
I don't think all the keys are required. Please check the templates if it is not documented in the old data model.

2022-08-30 08:44 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/local_users.schema.yml
> +          display_name: Privilege
Display_name is only needed if the name is different than the output of `key.replace('_',' ').title()`.

2022-08-30 08:44 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/local_users.schema.yml
> +          display_name: SSH-Key
```suggestion
  local_users:
    type: list
    display_name: Local Users
    required: true
    primary_key: name
    items:
      type: dict
      keys:
        name:
          type: str
          required: true
          display_name: Username
        privilege:
          type: int
          min: 1
          max: 15
          description: Initial privilege level with local EXEC authorization.
        role:
          type: str
          description: EOS RBAC Role to be assigned to the user such as "network-admin" or "network-operator"
        no_password:
          type: bool
          description: If set a password will not be configured for this user. "sha512_password" MUST not be defined for this user.
        sha512_password:
          display_name: SHA512 Hash of Password
          type: str
          description: Must be the hash of the password. By default EOS salts the password with the username, so the simplest is to generate the hash on an EOS device using the same username.
        ssh_key:
          display_name: SSH Key
          type: str
```

2022-09-16 17:58 UTC, ClausHolbechArista approved these changes
LGTM

2022-09-18 19:20 UTC, carlbuchmann approved these changes
LGTM!

2022-09-18 19:21 UTC, merged