Feat(eos_cli_config_gen): Add schema for maintenance
aristanetworks/ansible-avd pull request #2028
Opened 2022-09-05 06:18 UTC by KonikaChaurasiya-GSLab

## Add schema for data model

## Checklist

### Contributor Checklist

- [ ] Create schema fragment matching data model described in README.md and README_v4.0.md
  - README.md is most complete with all keys. README_v4.0 includes partial data models after conversion to lists.
  - Schema fragment path is `roles/eos_cli_config_gen/schemas/schema_fragments/<data_model_key>.schema.yml`.
  - Copy line 1-5 from another schema (comments and outer type:dict).
  - Refer to [schema documentation](https://avd.sh/en/devel/docs/input-variable-validation-BETA.html) for syntax and/or use YAML Lint plugin from Redhat in VSCode.
  - Use `convert_types` on value that could be mixed type or misinterpreted like integers and numeric strings.
- [ ] If the data model has been converted from wildcard dicts:
  - Add `convert_types: ['dict']` to the schema.
  - Remove `convert_dicts` from the `templates/eos/<>.j2` and `templates/documentation/<>.j2` templates.
- [ ] Run `molecule converge -s build_schemas_and_docs` to update schema and documentation.
- [ ] Test by running `molecule converge -s eos_cli_config_gen` and verify no errors or changes to generated configs/docs.

### Reviewer Checklist

- Reviewer 1:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

- Reviewer 2:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

2022-09-05 06:47 UTC, ClausHolbechArista requested changes

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +        type: str
```suggestion
        type: str
        description: Name of default Interface Profile
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +        type: str
```suggestion
        type: str
        description: Name of default BGP Profile
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +        type: str
```suggestion
        type: str
        description: Name of default Unit Profile
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +        display_name: Interface Profile Names
This is strictly speaking not a list of names but a list of the full profiles. So we can just keep the key name alone.
```suggestion
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +                  type: int
```suggestion
                  type: int
                  description: Load Interval in Seconds
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +                  type: int
```suggestion
                  type: int
                  description: Threshold in kbps
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +                  type: int
```suggestion
                  type: int
                  description: Max delay in seconds
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +        display_name: BGP Profile Names
```suggestion
        display_name: BGP Profile
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +        display_name: Unit Profile Names
```suggestion
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +                  type: int
```suggestion
                  type: int
                  min: 300
                  max: 3600
                  description: On-boot in seconds
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +        display_name: Units
Not needed since it is the same as `<key>.title()`
```suggestion
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +              display_name: Unit Name
copy/paste error
```suggestion
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +              display_name: Unit Profile
```suggestion
              description: Name of Unit Profile
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +                    type: str
```suggestion
                    type: str
                    description: Name of BGP Group
```

2022-09-05 06:47 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +                    type: str
```suggestion
                    type: str
                    description: Name of Interface Group
```

2022-09-05 12:13 UTC, ClausHolbechArista requested changes
LGTM

2022-09-05 12:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/eos_cli_config_gen.schema.yml
> +    display_name: Profiles and units
```suggestion
    display_name: Maintenance Mode
```

2022-09-05 12:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/eos_cli_config_gen.schema.yml
> +      bgp_profiles:
Because of acronym, we still want the display name here
```suggestion
      bgp_profiles:
        display_name: BGP Profiles
```

2022-09-05 12:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/eos_cli_config_gen.schema.yml
> +                bgp_groups:
```suggestion
                bgp_groups:
                  display_name: BGP Groups
```

2022-09-13 07:57 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +                  type: int
still relevant

2022-09-13 07:58 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +                  type: int
Still relevant

2022-09-13 07:58 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/maintenance.schema.yml
> +                  type: int
Still relevant

2022-09-16 13:42 UTC, ClausHolbechArista approved these changes
LGTM

2022-09-18 19:34 UTC, carlbuchmann approved these changes
LGTM!

2022-09-18 19:48 UTC, merged