Feat(eos_cli_config_gen): Add schema for management-api-http
aristanetworks/ansible-avd pull request #2062
Opened 2022-09-14 16:41 UTC by KonikaChaurasiya-GSLab

## Add schema for data model

## Checklist

### Contributor Checklist

- [ ] Create schema fragment matching data model described in README.md and README_v4.0.md
  - README.md is most complete with all keys. README_v4.0 includes partial data models after conversion to lists.
  - Schema fragment path is `roles/eos_cli_config_gen/schemas/schema_fragments/<data_model_key>.schema.yml`.
  - Copy line 1-5 from another schema (comments and outer type:dict).
  - Refer to [schema documentation](https://avd.sh/en/devel/docs/input-variable-validation-BETA.html) for syntax and/or use YAML Lint plugin from Redhat in VSCode.
  - Use `convert_types` on value that could be mixed type or misinterpreted like integers and numeric strings.
- [ ] If the data model has been converted from wildcard dicts:
  - Add `convert_types: ['dict']` to the schema.
  - Remove `convert_dicts` from the `templates/eos/<>.j2` and `templates/documentation/<>.j2` templates.
- [ ] Run `molecule converge -s build_schemas_and_docs` to update schema and documentation.
- [ ] Test by running `molecule converge -s eos_cli_config_gen` and verify no errors or changes to generated configs/docs.

### Reviewer Checklist

- Reviewer 1:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

- Reviewer 2:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

2022-09-15 10:48 UTC, jonxstill requested changes, later dismissed
Just needs some descriptions of some of the keys as suggested.

2022-09-15 10:48 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/management_api_http.schema.yml
> +            type: str
```suggestion
            display_name: Name of private key; certificate must also be specified
            type: str
```

2022-09-15 10:48 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/management_api_http.schema.yml
> +            type: str
```suggestion
            display_name: Name of certificate; private_key must also be specified
            type: str
```

2022-09-15 10:48 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/management_api_http.schema.yml
> +        type: bool
```suggestion
        display_name: Enable default services
        type: bool
```

2022-09-15 10:48 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/management_api_http.schema.yml
> +        type: str
```suggestion
        display_name: Name of SSL Profile
        type: str
```

2022-09-19 01:45 UTC, carlbuchmann approved these changes
LGTM!

2022-09-20 08:37 UTC, jonxstill approved these changes
LGTM

2022-09-20 15:37 UTC, merged