Feat(eos_cli_config_gen): Add schema for logging
aristanetworks/ansible-avd pull request #2085
Opened 2022-09-20 19:12 UTC by KonikaChaurasiya-GSLab

## Add schema for data model

## Checklist

### Contributor Checklist

- [ ] Create schema fragment matching data model described in README.md and README_v4.0.md
  - README.md is most complete with all keys. README_v4.0 includes partial data models after conversion to lists.
  - Schema fragment path is `roles/eos_cli_config_gen/schemas/schema_fragments/<data_model_key>.schema.yml`.
  - Copy line 1-5 from another schema (comments and outer type:dict).
  - Refer to [schema documentation](https://avd.sh/en/devel/docs/input-variable-validation-BETA.html) for syntax and/or use YAML Lint plugin from Redhat in VSCode.
  - Use `convert_types` on value that could be mixed type or misinterpreted like integers and numeric strings.
- [ ] If the data model has been converted from wildcard dicts:
  - Add `convert_types: ['dict']` to the schema.
  - Remove `convert_dicts` from the `templates/eos/<>.j2` and `templates/documentation/<>.j2` templates.
- [ ] Run `molecule converge -s build_schemas_and_docs` to update schema and documentation.
- [ ] Test by running `molecule converge -s eos_cli_config_gen` and verify no errors or changes to generated configs/docs.

### Reviewer Checklist

- Reviewer 1:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

- Reviewer 2:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

2022-09-22 10:32 UTC, jonxstill requested changes, later dismissed
Added valid values for items where there is a choice of items

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +          e.g. console: error
```suggestion
      console:
        type: str
        valid_values:
        - debugging
        - informational
        - notifications
        - warnings
        - errors
        - critical
        - alerts
        - emergencies
        - disabled
        description: Console logging severity level
```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +          e.g. monitor: debugging
```suggestion
      monitor:
        type: str
        valid_values:
        - debugging
        - informational
        - notifications
        - warnings
        - errors
        - critical
        - alerts
        - emergencies
        - disabled
        description: Monitor logging severity level
```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +            min: 10
```suggestion
            min: 10
            max: 2147483647
```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +              e.g. monitor: warnings
```suggestion
            type: str
            valid_values:
            - debugging
            - informational
            - notifications
            - warnings
            - errors
            - critical
            - alerts
            - emergencies
            - disabled
            description: Buffer logging severity level
```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +          e.g. trap: disabled
```suggestion
        type: str
        valid_values:
        - debugging
        - informational
        - notifications
        - warnings
        - errors
        - critical
        - alerts
        - emergencies
        - disabled
        description: Trap logging severity level```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +              "<severity_level>" | "disabled"
```suggestion
            type: str
            valid_values:
            - debugging
            - informational
            - notifications
            - warnings
            - errors
            - critical
            - alerts
            - emergencies
            - disabled
            description: Synchronous logging severity level
```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +              < high-resolution | traditional >
```suggestion
          timestamp:
            type: str
            valid_values: ["high-resolution", "traditional"]
            display_name: Timestamp format
```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +              < fqdn | ipv4 >
```suggestion
          hostname:
            type: str
            valid_values: ["fqdn", "ipv4"]
            display_name: Hostname format
```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +            type: bool
```suggestion
            type: bool
            description: Add sequence numbers to log messages
```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +        type: str
```suggestion
      facility:
        type: str
        valid_values:
        - auth
        - cron
        - daemon
        - kern
        - local0
        - local1
        - local2
        - local3
        - local4
        - local5
        - local6
        - local7
        - lpr
        - mail
        - news
        - sys10
        - sys11
        - sys12
        - sys13
        - sys14
        - sys9
        - syslog
        - user
        - uucp        
```

2022-09-22 10:32 UTC, jonxstill commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +                      type: str
```suggestion
                    action:
                      type: str
                      valid_values: ["discard"]
```

2022-10-31 13:57 UTC, carlbuchmann approved these changes
LGTM

2022-10-31 13:57 UTC, ClausHolbechArista approved these changes

2022-10-31 14:23 UTC, merged