Feat(eos_cli_config_gen): Add schema for ntp
aristanetworks/ansible-avd pull request #2151
Opened 2022-10-04 06:18 UTC by KonikaChaurasiya-GSLab

## Add schema for data model

## Checklist

### Contributor Checklist

- [ ] Create schema fragment matching data model described in README.md and README_v4.0.md
  - README.md is most complete with all keys. README_v4.0 includes partial data models after conversion to lists.
  - Schema fragment path is `roles/eos_cli_config_gen/schemas/schema_fragments/<data_model_key>.schema.yml`.
  - Copy line 1-5 from another schema (comments and outer type:dict).
  - Refer to [schema documentation](https://avd.sh/en/devel/docs/input-variable-validation-BETA.html) for syntax and/or use YAML Lint plugin from Redhat in VSCode.
  - Use `convert_types` on value that could be mixed type or misinterpreted like integers and numeric strings.
- [ ] If the data model has been converted from wildcard dicts:
  - Add `convert_types: ['dict']` to the schema.
  - Remove `convert_dicts` from the `templates/eos/<>.j2` and `templates/documentation/<>.j2` templates.
- [ ] Run `molecule converge -s build_schemas_and_docs` to update schema and documentation.
- [ ] Test by running `molecule converge -s eos_cli_config_gen` and verify no errors or changes to generated configs/docs.

### Reviewer Checklist

- Reviewer 1:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

- Reviewer 2:
  - [ ] Verify that data model is fully covered in the described schema. Easiest by looking at the generated documentation.
  - [ ] Verify that `convert_dicts` has been removed from templates as applicable.
  - [ ] Verify no changes to configs/docs on any molecule scenario
  - [ ] Verify that CI pass

2022-11-15 12:31 UTC, ClausHolbechArista requested changes
Please improve the schema and also add `ntp` to the wordlist in `ansible_collections/arista/avd/plugins/plugin_utils/schema/key_to_display_name.py`

2022-11-15 12:31 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/ntp.schema.yml
> +        convert_types:
missing `primary_key: id`

2022-11-15 12:31 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/ntp.schema.yml
> +type: dict
Please ensure that we don't loose useful information from the current documentation:
https://avd.sh/en/devel/roles/eos_cli_config_gen/index.html#ntp

Example valid_values for key_type but also some descriptions that could help.

2022-11-23 06:50 UTC, ClausHolbechArista approved these changes

2022-11-23 12:29 UTC, gmuloc requested changes, later dismissed

2022-11-23 12:29 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/ntp.schema.yml
> +              description: IP or hostname ex-2.2.2.55, ie.pool.ntp.org
```suggestion
              description: IP or hostname e.g., 2.2.2.55, ie.pool.ntp.org
```

2022-11-23 12:29 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/ntp.schema.yml
> +              description: Value of maxpoll betweeen 3 - 17 (Logarithmic)
```suggestion
              description: Value of maxpoll between 3 - 17 (Logarithmic)
```

2022-11-23 12:29 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/ntp.schema.yml
> +              description: Value of minpoll betweeen 3 - 17 (Logarithmic)
```suggestion
              description: Value of minpoll between 3 - 17 (Logarithmic)
```

2022-11-24 01:03 UTC, carlbuchmann approved these changes
LGTM

2022-11-24 01:05 UTC, merged