Feat: Add peer hosts to CVX
aristanetworks/ansible-avd pull request #2281
Opened 2022-11-14 18:08 UTC by sugetha24

## Change Summary

Added `peer host` knob to CVX

## Related Issue(s)

Fixes #2074 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Data Model
```
cvx:
  shutdown: false
  peer_hosts:
  - 1.1.1.1
  - 2.2.2.2
  services:
    mcs:
      redis:
        password: 070E334ddD1D18
        password_type: 7
      shutdown: false
```

Config:
```
cvx
   no shutdown
   peer host 1.1.1.1
   peer host 2.2.2.2
   service mcs
      redis password 7 070E334ddD1D18
      no shutdown
```

## How to test
`molecule converge --scenario-name eos_cli_config_gen -- --limit cvx`

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2022-11-30 14:25 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/cvx.j2
> +{%     endfor %}
Keep it singular, for ease of review and for others to understand that this is 1 item

```suggestion
{%     for peer_host in cvx.peer_hosts | arista.avd.natural_sort %}
   peer host {{ peer_host }}
{%     endfor %}
```

2022-11-30 14:28 UTC, tgodaA commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/cvx.j2
> +{%     for peer_hosts in cvx.peer_hosts | arista.avd.natural_sort %}
Please Add this to README.md because it is currently used until AVD 4.0 version.

2022-12-05 08:08 UTC, ClausHolbechArista requested changes

2022-12-05 08:08 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/cvx.j2
> +| Peer Hosts |
```suggestion

| Peer Hosts |
```

2022-12-05 08:08 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/cvx.md
> +| Peer Hosts |
```suggestion

| Peer Hosts |
```

2022-12-05 08:09 UTC, ClausHolbechArista approved these changes

2022-12-05 09:47 UTC, onurgashi approved these changes

2022-12-05 12:12 UTC, merged