Refactor: Refactoring network_services/router_ospf python_module
aristanetworks/ansible-avd pull request #2559
Opened 2023-02-22 10:20 UTC by Vibhu-gslab

## Change Summary

Refactoring network_services/router_ospf python_module as per eos_cli_config_gen

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2023-02-22 13:25 UTC, ClausHolbechArista requested changes

2023-02-22 13:25 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/router_ospf.py
> +                process["id"] = process_id
just set this as part of the definition of `process` in line 56

2023-02-22 13:25 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/router_ospf.py
> +            ospf_processes.append(dict({"redistribute": {"static": {}}}, id=int(self._underlay_ospf_process_id)))
```suggestion
            ospf_processes.append({"id": self._underlay_ospf_process_id, "redistribute": {"static": {}}})
```

2023-02-28 14:51 UTC, emilarista approved these changes
LGTM!

2023-02-28 15:04 UTC, tgodaA approved these changes
LGTM

2023-03-02 14:43 UTC, gmuloc approved these changes
LGTM

2023-03-06 08:01 UTC, ClausHolbechArista approved these changes

2023-03-06 08:02 UTC, merged