Refactor(eos_designs): ethernet_interfaces python module as per eos_cli_config_gen
aristanetworks/ansible-avd pull request #2627
Opened 2023-03-16 07:36 UTC by Vibhu-gslab

Refactor ethernet_interfaces python module as per eos_cli_config_gen

2023-03-24 07:01 UTC, ClausHolbechArista requested changes

2023-03-24 07:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/core_interfaces/ethernet_interfaces.py
> +            for eth_name, eth_val in ethernet_interfaces.items():
please refactor the code above instead of just converting at the end.
Notice the code in l3_edge and core_interfaces are almost the same, so please solve it in the same way.

2023-03-24 07:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/l3_edge/ethernet_interfaces.py
> +                ethernet_interfaces.append({"name": interface_name, **ethernet_interface})
I think we could refactor the `_get_common_interface_cfg`, to take an argument with the interface name. This way we could clean up both this and the port-channel area.

2023-03-24 07:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/connected_endpoints/ethernet_interfaces.py
> +                    ethernet_interface = self._get_ethernet_interface_cfg(adapter, node_index, connected_endpoint)
I think we could refactor the `_get_ethernet_interface_cfg`, to extract the name inside that function instead of here and in line 51.

2023-03-24 07:01 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/ethernet_interfaces.py
> +            for eth_name, eth_val in ethernet_interfaces.items():
please refactor the code above instead of just converting at the end.

2023-04-01 13:44 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/core_interfaces/ethernet_interfaces.py
> +                if p2p_link["data"]["interface"] in interface_names:
So as I read this, you are replacing duplicate interfaces to keep the old behavior. We should not. If ppl have duplicate interfaces, we should trigger an error like we have implemented under network services for vrfs, vlans and vnis.
The same should be done below (use the name list of interface names) and also in l3_edge.

2023-04-01 13:44 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/ethernet_interfaces.py
> +                                for idx, eth_int in enumerate(ethernet_interfaces):
Same here and below for subinterfaces, raise an error instead of just overwriting.

2023-04-01 13:44 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/underlay/ethernet_interfaces.py
> +            if link["interface"] in interface_names:
and here :)

2023-04-10 17:29 UTC, ClausHolbechArista reviewed
There is a lot of repeated code in the new error handling. It would be good if we could put all that in a helper function, but since you need it across multiple modules, we will postpone that until we hare `shared_utils`.
Please look into my comments, and ensure that descriptions are correctly worded for the context.

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/connected_endpoints/ethernet_interfaces.py
> +                            f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Duplicate interface name of description:"
```suggestion
                            f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Description on duplicate interface:"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/connected_endpoints/ethernet_interfaces.py
> +                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Duplicate interface name of description:"
```suggestion
                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Description on duplicate interface:"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/core_interfaces/ethernet_interfaces.py
> +                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Duplicate interface name of description:"
```suggestion
                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Description on duplicate interface:"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/core_interfaces/ethernet_interfaces.py
> +                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Duplicate interface name of description:"
```suggestion
                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Description on duplicate interface:"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/l3_edge/ethernet_interfaces.py
> +                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Duplicate interface name of description:"
```suggestion
                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Description on duplicate interface:"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/l3_edge/ethernet_interfaces.py
> +                        f"Duplicate interface name {ethernet_interface['name']} found while generating ethernet_interfaces for connected_endpoints peer:"
Please also fix this the remaining places, so it properly guides the user to know where to look for the duplicate.

```suggestion
                        f"Duplicate interface name {ethernet_interface['name']} found while generating ethernet_interfaces for l3_edge peer:"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/l3_edge/ethernet_interfaces.py
> +                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Duplicate interface name of description:"
```suggestion
                        f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Description on duplicate interface:"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/ethernet_interfaces.py
> +                                    f"Duplicate interface_name {interface['name']} found while generating ethernet_interfaces for network_services vrf:"
```suggestion
                                    f"Duplicate interface_name {interface['name']} found while generating ethernet_interfaces for network_services vrf:"
```
```suggestion
                                    f"Duplicate interface_name {interface['name']} found while generating l3_interfaces under network_services vrf:"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/ethernet_interfaces.py
> +                                    f" {interface['vrf']}. Duplicate interface_name of description: {found_eth_interface['description']}"
```suggestion
                                    f" {interface['vrf']}. Description on duplicate interface: {found_eth_interface['description']}"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/ethernet_interfaces.py
> +                                        f"Duplicate interface_name {ethernet_interface['name']} found while generating ethernet_interfaces for network_services"
```suggestion
                                        f"Duplicate interface_name {ethernet_interface['name']} found while generating subinterfaces under port_to_point_services"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/ethernet_interfaces.py
> +                                        " subinterface"
```suggestion
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/ethernet_interfaces.py
> +                                        f"Duplicate interface_name {interface['name']} found while generating ethernet_interfaces for network_services"
```suggestion
                                        f"Duplicate interface_name {interface['name']} found while generating ethernet_interfaces for network_services"
```
```suggestion
                                        f"Duplicate interface_name {interface['name']} found while generating ethernet_interfaces for point_to_point_services"
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/ethernet_interfaces.py
> +                                        " subinterface"
```suggestion
```

2023-04-10 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/underlay/ethernet_interfaces.py
> +                    f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Duplicate interface name of description:"
```suggestion
                    f" {ethernet_interface['peer']}, peer_interface: {ethernet_interface['peer_interface']}. Description on duplicate interface name:"
```

2023-04-21 07:44 UTC, ClausHolbechArista approved these changes

2023-04-21 08:02 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/connected_endpoints/ethernet_interfaces.py
> +                        )
Looks like exactly the same as line 62 to 74 for network_ports -> maybe a method instead?

2023-04-21 08:02 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/connected_endpoints/ethernet_interfaces.py
> +                        )
@ClausHolbechArista could this be in shared_utils maybe as this is in connected endpoints and core_interfaces and l3edge?

2023-04-21 08:02 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/connected_endpoints/ethernet_interfaces.py
> +                        )
Please also add molecule tests in `eos_designs_negative_unit_tests` that triggers these error messages

2023-04-21 08:20 UTC, gmuloc commented
So following discussion over chat here is the agreement to move forward:

The PR is merged as is and then two extra PRs should be opened:

1. to add negative tests for duplicate detection
2. to refactor all occurences of duplicate detection into a generic function in shared_utils and replace it

2023-04-21 08:22 UTC, gmuloc approved these changes

2023-04-21 08:23 UTC, merged