Topology source code and required structured configs
aristanetworks/ansible-avd pull request #2694
Opened 2023-04-04 08:56 UTC by mayurgs34

Topology source code and required structured configs

2023-04-04 09:09 UTC, gmuloc reviewed
Please move the tests to the tests folder (e.g. integration tests)

2023-04-04 09:39 UTC, gmuloc requested changes
* use snake_case
* do not use abstract variable names (ol, ld,)
* Add typing to your functions
* Fix docstrings
* Make sure pre-commit passes on your file
* Move tests to test folder
* Do you really need a role ? is the module not enough?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/modules/topology_generator.py
> +version_added: "1.0.0"
```suggestion
version_added: "4.0.0"
```

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/modules/topology_generator.py
> +short_description: Generate topology diagram from structure config
```suggestion
short_description: Generate topology diagram from structured configurations
```

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/modules/topology_generator.py
> +  - Generate topology diagram from structure config
same

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/modules/topology_generator.py
> +  structured_config:
let's call it `structured_config_dir` as it is a directory

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/modules/topology_generator.py
> +    structured_config: "base/main.j2"
that example looks wrong - it should be a directory not a jinja2 template

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +EDGETYPES = ["server"]
Should we find a way to make these configurable via variables? Maybe some kind of module input

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +import drawSvg as draw
These libraries should be added to requirements

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +import math
is isort happy with this ordering?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +def read_yaml_file(filename):
please add typing

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +            print(exc)
don't use `print` for ansible modules rather import display as in `verify_requirements` and use `display.error`

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +                if "peer_interface" not in value:
Use convert_dict if it is not a directory to be consistent with the rest of the AVD repo

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +        if type(file_data["ethernet_interfaces"]) == dict:
use `isinstance`

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +                    continue
Add some `display.vvv` message when skipping an interface

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +                neighbor_dict["neighborDevice"] = value["peer"]
please use `neighbor_device` rather than `neighborDevice` to be consistent in case. Same for other keys

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +        ol: Original input dictionary with nested "name", "nodes" and "groups" keys
give a better name than `ol`

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    Convert structure config file data to topology input data by creating a nested dictionary
```suggestion
    Convert structured config file data to topology input data by creating a nested dictionary
```

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +       ol: List of dictionary with nested "name", "nodes" and "groups" keys
is it the same as the input `ol`? if so indicates that the method modifies in place

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +            ol.append(new_dict)
if `ol` is `None` this will raise. please fix it

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +                if diagram_group_var == entry["name"]:
use `getitem` from `plugin_utils.utils`

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +                       ex- {'0': ['super-spine1', 'super-spine2']}
What is current_dict?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +        current_dict["nodes"].append(node_dict)
What if current_dict is `None` as the default argument shows?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +                        ex- {'0': ['super-spine1', 'super-spine2']}
wrong docstring

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +def find_edge_distance(currentNode, nodes, seen):
```suggestion
def find_edge_distance(current_node, nodes, seen):
```

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    Create a dictionary of rank/levels and it's corresponding node list
```suggestion
    Create a dictionary of rank/levels and its corresponding node list
```

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +       node_neighbor_dict: Dictionary of node and its corresponding neighbors
This is not at all the return value!

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +        return 1
What does this mean - what is this integer?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    return 1 + min(links)
why `min`?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +        data: Dictinary with nested keys "nodes" and "groups"
typo + missing argument

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    psuedo = False
pseudo ?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    Create a dictionary of rank/levels and it's corresponding node list
```suggestion
    Create a dictionary of rank/levels and its corresponding node list
```

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +def create_graph_dict(ol, inventory_group, nodes=None, node_neighbor_dict=None):
change `ol`

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +        if "nodes" in list(group.keys()) and group["nodes"]:
have a look at `get` from `plugin_utils.utils`

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    que = queue.Queue()
change name from que to `node_queue` or something meaningful

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +        if start_node in graph:  #key checking
formating should fail on the comment - should be (if inline comments are accepted):

```suggestion
        if start_node in graph:  # key checking
```

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +                neighbor = i["neighborDevice"]
```suggestion
                neighbor = i["neighbor_device"] 
```

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +            level_dict[level].append(node)
You should be able to condense this with `dict.setdefault`

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    # Remove psuedo 0'th element
pseudo

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    # Make a level loopup dict
lookup

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    GROUPOFFSET = LVLSPACING
why is `GROUPOFFSET` capitalized? Please keep capitalized variable names for globals

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +def subgroup_inventor_recursive(ld, ol):
```suggestion
def subgroup_inventor_recursive(level_dict, graph_dict):
```

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/plugins/plugin_utils/topology_generator_utils.py
> +    Create a dictionary of clusters and it's corresponding node
Does it really Create a dictionary or does it update in place the `ol` dict given as input?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/base/avdstructuredconfig.py
> +    def diagram_groups(self) -> list:
missing new line?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/roles/topology_generator/README.md
> +# topology_generator
do you really need a role ? is the module not enough?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/roles/topology_generator/tasks/generate_all.yml
> +      register: folders
is this the role for production?

2023-04-04 09:39 UTC, gmuloc commented on ansible_collections/arista/avd/roles/topology_generator/tasks/generate_all.yml
> +      loop: "{{ folders.files|flatten(levels=1) }}"
Looks like the module is enough and you could add simply a task in eos_designs calling the module with a tag maybe?

2023-10-06 10:26 UTC, ClausHolbechArista commented
Closing stale PR. Linked this from internal task issue.

2023-10-06 10:26 UTC, closed without merging