Description key not considered with connected endpoints
aristanetworks/ansible-avd pull request #2745
Opened 2023-04-19 20:43 UTC by pvinci-arista

## Change Summary

description key under connected endpoints not used.

## Related Issue(s)

Fixes #2744

## Component(s) name

`arista.avd.<role-name>`

## Proposed changes

## How to test

molecule test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2023-04-20 10:20 UTC, gmuloc reviewed
Great catch - could you also please implement the same for Port-channels?

2023-04-20 10:20 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/connected_endpoints/ethernet_interfaces.py
> +            "description": adapter.get("description") or self.shared_utils.interface_descriptions.connected_endpoints_ethernet_interfaces(peer, peer_interface),
```suggestion
            "description": default(adapter.get("description"), self.shared_utils.interface_descriptions.connected_endpoints_ethernet_interfaces(peer, peer_interface)),
```

2023-04-20 10:20 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/host_vars/connected_endpoints.yml
> +          !! VoIP/PC
can you limit even further the test?

2023-04-20 15:33 UTC, ClausHolbechArista commented
It was implemented as part of network_ports, where we want a more generic description, but makes perfect sense to include here as well. I would prefer to move the logic to the description module, so anyone customizing those keep full control. Similar to how it is done with port_channel_description.

2023-04-20 15:49 UTC, gmuloc commented
> It was implemented as part of network_ports, where we want a more generic description, but makes perfect sense to include here as well. I would prefer to move the logic to the description module, so anyone customizing those keep full control. Similar to how it is done with port_channel_description.

On this topic @ClausHolbechArista - should port-channel description also take into account this special description at the adapter level as currently it is doing `<adapter_description>_<oprtional_port_channel_description>`

2023-04-20 16:18 UTC, ClausHolbechArista commented
> > It was implemented as part of network_ports, where we want a more generic description, but makes perfect sense to include here as well. I would prefer to move the logic to the description module, so anyone customizing those keep full control. Similar to how it is done with port_channel_description.
> 
> On this topic @ClausHolbechArista - should port-channel description also take into account this special description at the adapter level as currently it is doing `<adapter_description>_<oprtional_port_channel_description>`

That would be good

2023-04-21 13:18 UTC, pvinci-arista commented
> I would prefer to move the logic to the description module, so anyone customizing those keep full control. Similar to how it is done with port_channel_description.

If I follow, won't we need to modify the method signature in the base class and all the subclasses?

2023-04-21 13:29 UTC, gmuloc commented
>

2023-04-27 16:13 UTC, gmuloc approved these changes

2023-04-27 19:59 UTC, carlbuchmann requested changes
The fix looks good - As mentioned in one of the comments, we should add an explanation of how the descriptions are built for physical ports and port-channels.

2023-04-27 20:04 UTC, pvinci-arista commented
> we should add an explanation of how the descriptions are built for physical ports and port-channels.

Docstrings were added to the methods.  Do you want something additional?  See, as an example: https://github.com/aristanetworks/ansible-avd/pull/2745/files#diff-bbfc03125089c9310eb2bebb44079e7849bbf1e5031bae6df3024d280c0f306dR94

2023-04-28 13:19 UTC, carlbuchmann commented
> > we should add an explanation of how the descriptions are built for physical ports and port-channels.
> 
> Docstrings were added to the methods. Do you want something additional? See, as an example: https://github.com/aristanetworks/ansible-avd/pull/2745/files#diff-bbfc03125089c9310eb2bebb44079e7849bbf1e5031bae6df3024d280c0f306dR94

We have added addition information in schema/documentation.

2023-04-28 13:20 UTC, carlbuchmann approved these changes
LGTM

2023-04-28 13:53 UTC, merged