Feat(eos_designs)!: Remove default value from mlag_peer_link_allowed_vlans
aristanetworks/ansible-avd pull request #2845
Opened 2023-05-16 15:36 UTC by carlbuchmann

## Change Summary

Remove default value from `mlag_peer_link_allowed_vlans` of "2-4094".

## Related Issue(s)

Fixes #aristanetworks/avd-internal#102

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

- [x] Remove default value from `mlag_peer_link_allowed_vlans`
- [x] Update release notes and porting guide
- [x] Update molecule scenarios

## How to test

See molecule results

2023-05-16 16:51 UTC, ClausHolbechArista approved these changes

2023-05-16 16:53 UTC, ClausHolbechArista requested changes

2023-05-16 16:53 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/docs/porting-guides/4.x.x.md
> +mlag_peer_link_allowed_vlans: "2-4094"
This example is misleading by not presenting that the var is set under the node type
```suggestion
l3leaf:
  defaults:
    mlag_peer_link_allowed_vlans: "2-4094"
```

2023-05-16 16:54 UTC, ClausHolbechArista approved these changes

2023-05-17 08:54 UTC, chetryan approved these changes
LGTM! - Would be nice to add a comment or update the PR description with **why** it is a good idea to remove this default value.

2023-05-17 13:59 UTC, merged