Feat(eos_cli_config_gen): add support for password complexity policies
aristanetworks/ansible-avd pull request #2991
Opened 2023-06-16 16:37 UTC by hamptonmoore

## Change Summary

Add support for the password complexity policies introduced into EOS 4.29.2F (https://www.arista.com/en/support/toi/eos-4-29-2f/17208-support-for-password-complexity-policies)

## Related Issue(s)

Fixes #2972

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Add policy list key to management_security.password

## How to test
- run molecule test -s eos_cli_config_gen
## Checklist
### User Checklist
- [x] Review the new Documentation

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2023-06-16 20:38 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/management_security.schema.yml
> +                      type: int
add convert type dict

2023-06-16 20:39 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/management_security.schema.yml
> +          policy:
update to policies

2023-06-19 14:50 UTC, carlbuchmann approved these changes, later dismissed
LGTM

2023-06-19 14:55 UTC, carlbuchmann requested changes

2023-06-19 14:55 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/management_security.schema.yml
> +                name:
This should be set as the primary key

2023-06-20 18:57 UTC, carlbuchmann approved these changes
LGTM

2023-06-23 08:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/management-security.md
> +#### Policy AVD_POLICY
Missing blank line between headings

2023-06-23 08:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/management-security.md
> +- Digits: 1
missing blank line above list

2023-06-23 08:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/management-security.md
> +### Password Policies
Could we build this as a table of policies instead of these lists? Like a "repetitive" column with `>6, <20`.

2023-06-23 08:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/management_security.schema.yml
> +                maximum:
Minimum values are 1  for maximum limits according to EOS. Also please set maximum values to 65535 everywhere

2023-06-23 08:40 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/management-security.j2
> +
Always place the blank line after the `if` and avoid blanks at the end of a section. This will ensure consistent spacing.

2023-07-03 06:55 UTC, ClausHolbechArista commented
Moving this to draft until, review comments have been addressed.

2023-07-21 17:07 UTC, JulioPDX approved these changes
LGTM, thank you

2023-07-21 17:08 UTC, merged