Feat(eos)cli_config_gen): Add support for OSPF Process Defaults
aristanetworks/ansible-avd pull request #3035
Opened 2023-07-11 19:05 UTC by KyleMui

## Change Summary

Add eos cli to router ospf process ids

## Related Issue(s)

Fixes #3009  

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Added the below to the eos_cli_config_gen `router_ospf` data model
```
router_ospf:
  process_ids:
    - id: <int>
      eos_cli:
        - <eos-cli-command-1>
        - <eos-cli-command-2>

## How to test

```
eos_cli:
        - area 5 not-so-stubby lsa type-7 convert type-5
        - network 3.2.4.1 0.255.255.255 area 3.2.4.1
```

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2023-07-13 15:13 UTC, jrecchia1029 commented
So it looks like the type of `eos_cli` should be a string just like the other `eos_cli` keys in the **eos_cli_config_gen** role.  The description for the key should match those descriptions too.

2023-07-13 15:14 UTC, jrecchia1029 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/eos_cli_config_gen.schema.yml
> +                description: The eos cli command
Make this description for this the same as the other `eos_cli` keys.

i.e. 

```
Multiline string with EOS CLI rendered under the ospf process id
```

2023-07-14 15:11 UTC, jrecchia1029 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/router_ospf.schema.yml
> +              description: Multiline EOS CLI rendered directly on the router ospf in the final EOS configuration
It's under a process id which is under router ospf. So I would just clarify in comment `Multiline EOS CLI rendered directly on the router ospf process id in the final EOS configuration`

2023-07-17 09:25 UTC, gmuloc requested changes
One little change in the description in the schema.

While this PR is a correct addition and it _can_ make sense to add an escape hatch `eos_cli` in this place, this **should** not replace implementing proper model for missing OSPF commands in `eos_cli_config_gen`.

In this PR the following lines are being used for the test:
```
   area 5 not-so-stubby lsa type-7 convert type-5
   network 3.2.4.1 0.255.255.255 area 3.2.4.1
```

Please note that `network` is already supported using `network_prefixes` which is anyway what will appear in the rendered configuration. What is the reason to use the CLI that will be converted instead?

```
Spine1(config-router-ospf)#network 3.2.4.1 0.255.255.255 area 3.2.4.1
Spine1(config-router-ospf)#!
Spine1(config-router-ospf)#show active
router ospf 666
   network 3.0.0.0/8 area 3.2.4.1
```

It seems what is really missing today in `eos_cli_config_gen` is the `not-so-stuby` type of areas - is this a correct statement?

Could you please open an issue with your intended configuration to add the missing key properly to `eos_cli_config_gen` as well?


> The issue being referenced has been closed by @ClausHolbechArista with the same kind of comments as mine: https://github.com/aristanetworks/ansible-avd/issues/3009#issuecomment-1607705472
He is suggesting adding `eos_cli` only as a fix for missing model.

2023-07-17 09:25 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/router_ospf.schema.yml
> +              description: Multiline EOS CLI rendered directly on the router ospf process id in the final EOS configuration
```suggestion
              description: Multiline EOS CLI rendered directly on the Router OSPF process ID in the final EOS configuration
```

2023-07-17 09:25 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/router-ospf.yml
> +        network 3.2.4.1 0.255.255.255 area 3.2.4.1
This is what will appear in the config on the device (EOS 4.27)
```suggestion
        network 3.0.0.0/8 area 3.2.4.1
```

Though, yes the configuration supplied will be accepted by the device.

2023-07-18 13:43 UTC, jrecchia1029 reviewed
LGTM

2023-07-18 14:10 UTC, jrecchia1029 commented
> One little change in the description in the schema.
> 
> While this PR is a correct addition and it _can_ make sense to add an escape hatch `eos_cli` in this place, this **should** not replace implementing proper model for missing OSPF commands in `eos_cli_config_gen`.
> 
> In this PR the following lines are being used for the test:
> 
> ```
>    area 5 not-so-stubby lsa type-7 convert type-5
>    network 3.2.4.1 0.255.255.255 area 3.2.4.1
> ```
> 
> Please note that `network` is already supported using `network_prefixes` which is anyway what will appear in the rendered configuration. What is the reason to use the CLI that will be converted instead?
> 
> ```
> Spine1(config-router-ospf)#network 3.2.4.1 0.255.255.255 area 3.2.4.1
> Spine1(config-router-ospf)#!
> Spine1(config-router-ospf)#show active
> router ospf 666
>    network 3.0.0.0/8 area 3.2.4.1
> ```
> 
> It seems what is really missing today in `eos_cli_config_gen` is the `not-so-stuby` type of areas - is this a correct statement?
> 
> Could you please open an issue with your intended configuration to add the missing key properly to `eos_cli_config_gen` as well?
> 
> > The issue being referenced has been closed by @ClausHolbechArista with the same kind of comments as mine: [#3009 (comment)](https://github.com/aristanetworks/ansible-avd/issues/3009#issuecomment-1607705472)
> > He is suggesting adding `eos_cli` only as a fix for missing model.

The commands used in the test were chosen arbitrarily.  This PR is less about a specific set of commands not covered by `eos_cli_config_gen` and more about offering that escape hatch you mentioned.  I believe the issue which Claus closed already mentions being open to using the `eos_cli` key instead of `ospf_defaults`

2023-07-18 14:11 UTC, jrecchia1029 approved these changes

2023-07-24 13:25 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/router-ospf.yml
> +        network 3.2.4.1/8 area 3.2.4.1
let's change this example as it is not really a good one

2023-07-24 16:21 UTC, ClausHolbechArista commented
Please update the PR description to reflect the data model being implemented.

2023-07-25 09:07 UTC, gmuloc approved these changes

2023-07-25 09:07 UTC, merged

2023-07-25 09:07 UTC, gmuloc commented
Thanks @KyleMui for this contribution