Feat(eos_designs): Add default_interface_mtu and feature_support.per_interface_mtu
aristanetworks/ansible-avd pull request #3128
Opened 2023-09-07 15:58 UTC by ClausHolbechArista

## Change Summary

Add default_interface_mtu and feature_support.per_interface_mtu

## Related Issue(s)

Related to #3123 but not changing the default settings.

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

```yaml
platform_settings:
  - ...
    default_interface_mtu: <int>
    feature_support:
      per_interface_mtu: <bool>
```

## How to test

Added molecule coverage.

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2023-09-08 14:30 UTC, ClausHolbechArista commented
Thank you to @kmueller68 for testing this. See #3123 for details.

2023-09-09 01:01 UTC, carlbuchmann approved these changes
LGTM

2023-09-11 08:02 UTC, gmuloc requested changes

2023-09-11 08:02 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_designs/schemas/schema_fragments/platform_settings.schema.yml
> +                Platforms without support for per interface MTU can use a single default interface MTU setting. Set this via "interface_default_mtu"
The name of the is incorrect here:

```suggestion
                Platforms without support for per interface MTU can use a single default interface MTU setting. Set this via "default_interface_mtu"
```

2023-09-12 07:30 UTC, gmuloc approved these changes

2023-09-12 07:30 UTC, merged