Feat(eos_cli_config_gen): Add knob to define port in GNMI transport grpc
aristanetworks/ansible-avd pull request #3245
Opened 2023-10-16 14:40 UTC by philippebureau

## Change Summary

Add the capacity to define a custom port in management api gnmi for transport grpc

## Related Issue(s)

N/A

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

## How to test
see molecule tests :
    management-gnmi.yml
    management-gnmi-new-flags.yml

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2023-10-16 14:46 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/management-gnmi-new-flags.md
>        notification timestamp send-time
please verify the order on EOS.

2023-10-16 16:17 UTC, philippebureau commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/management-gnmi-new-flags.md
>        notification timestamp send-time
Yes it is in order

2023-10-16 16:37 UTC, noredistribution commented
should we update the documentation? changing the gRPC Port might require update to the control-plane ACL

2023-10-16 16:45 UTC, philippebureau commented
I can add a note to the description for sure, give me 1 h

On Mon, Oct 16, 2023, 12:37 p.m. Tamas Plugor ***@***.***>
wrote:

> should we update the documentation? changing the gRPC Port might require
> update to the control-plane ACL
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/aristanetworks/ansible-avd/pull/3245#issuecomment-1764864978>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACEBMWKPPQYPRZJWJXFZRATX7VPFLAVCNFSM6AAAAAA6CKA3NWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRUHA3DIOJXHA>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-10-16 17:17 UTC, noredistribution reviewed
tested and works fine for me, I'd just add that note about the CP ACL and then it's good to go

2023-10-16 17:46 UTC, philippebureau commented
> should we update the documentation? changing the gRPC Port might require update to the control-plane ACL

updated schema fragment description with your recommendation. Thank you

2023-10-17 10:03 UTC, gmuloc approved these changes
LGTM

2023-10-17 10:03 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/management_api_gnmi.schema.yml
> +                  description: GNMI port.  Make sure to update the control-plane ACL accordingly in order for the service to be reachable by external applications.
Cosmetic:

```suggestion
                  description: |
                      GNMI port. 
                      Make sure to update the control-plane ACL accordingly in order for the service to be reachable by external applications.
```

2023-10-18 11:13 UTC, ClausHolbechArista requested changes

2023-10-18 11:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/management-gnmi-new-flags.md
> +| mytransport | - | - | send-time | acl1 | 6032
```suggestion
| MGMT | gnmi | MGMT | send-time | acl1 | 6030 |
| mytransport | - | - | send-time | acl1 | 6032 |
```

2023-10-18 11:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/management-gnmi.md
> +| MONITORING | - | MONITORING | last-change-time | - | 6031
```suggestion
| MGMT | - | MGMT | last-change-time | ACL-GNMI | 6030 |
| MONITORING | - | MONITORING | last-change-time | - | 6031 |
```

2023-10-18 11:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/management-api-gnmi.j2
> +| {{ transport_name }} | {{ ssl_profile }} | {{ vrf }} | {{ notif }} | {{ acl }} | {{ port }}
```suggestion
| {{ transport_name }} | {{ ssl_profile }} | {{ vrf }} | {{ notif }} | {{ acl }} | {{ port }} |
```

2023-10-19 07:49 UTC, ClausHolbechArista approved these changes

2023-10-19 07:49 UTC, merged