Feat(eos_designs): Add cv_settings to replace cvp_* and terminattr_*
aristanetworks/ansible-avd pull request #3301
Opened 2023-10-27 05:25 UTC by ClausHolbechArista

## Change Summary

Add cv_settings to replace cvp_* and terminattr_*

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

Settings for configuring CloudVision telemetry streaming and provisioning.

`cv_settings` replaces the following deprecated keys, which are ignored when `cv_settings` is set:
- `cvp_ingestauth_key`
- `cvp_instance_ip`
- `cvp_instance_ips`
- `cvp_token_file`
- `terminattr_disable_aaa`
- `terminattr_ingestexclude`
- `terminattr_ingestgrpcurl_port`
- `terminattr_smashexcludes`

New data model:
```yaml
cv_settings:
  cvaas_clusters:
    - name: <str>
      server: <str>
      vrf: <str>
      token_file: <str>
  onprem_clusters:
    - name: <str>
      servers:
        - name: <str>
          port: <int>
      vrf: <str>
      key: <str>
      token_file: <str>
  terminattr_ingestexclude: <str>
  terminattr_smashexcludes: <str>
  terminattr_disable_aaa: <bool>
```

## How to test

- Updated all existing molecule scenarios and examples to use the new data model
- Added the deprecated vars to `eos_designs_deprecated_vars`
- Added new unit test for `cv_settings` utilizing all options.

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2023-12-17 19:37 UTC, jrecchia1029 commented
I think we want to add `source_interface` to the data model to be even more deterministic than `vrf` in inband scenarios.

So data model would be:
```
cv_settings:
  cvaas_clusters:
    - name: <str>
      server: <str>
      vrf: <str>
      source_interface: <str>
      token_file: <str>
  onprem_clusters:
    - name: <str>
      servers:
        - name: <str>
          port: <int>
      vrf: <str>
      source_interface: <str>
      key: <str>
      token_file: <str>
  terminattr_ingestexclude: <str>
  terminattr_smashexcludes: <str>
  terminattr_disable_aaa: <bool>
```

2023-12-17 20:05 UTC, jrecchia1029 commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/base/daemon_terminattr.py
> +                raise AristaAvdError("'ntp_settings.server_vrf' is set to 'use_inband_mgmt_vrf' but this node is missing configuration for inband management")
I believe `ntp_settings.server_vrf` should be `{org_var}`

2025-06-24 10:52 UTC, ankudinov requested changes
Tested on Codespaces and CVaaS with the following settings:

```yaml
cv_settings:
  terminattr_disable_aaa: true
  cvaas:
    - name: test
      vrf: MGMT
      fqdn: "apiserver.cv-staging.corp.arista.io"
      token_file: "/mnt/flash/cv-onboarding-token"
  terminattr_ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
  terminattr_smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
```

Also tested different excludes. Not tested the on-prem case.

2025-06-24 10:52 UTC, ankudinov commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +# Copyright (c) 2023-2025 Arista Networks, Inc.
I'd also add somewhere in the docs, that `daemon_terminattr` is not supposed to be used directly any more. This is the case for all my inventories. =) I was never using any of the keys we are deprecating.

2025-06-24 10:52 UTC, ankudinov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                Short name for the CVaaS cluster. Used when configuring multiple clusters.
The description "Used when configuring multiple clusters" is a bit misleading, as it creates impression that this key is optional for single CVaaS/on-prem instance. However it's required and used as primary key. I'd also stress the fact that it must be unique. (If it's not unique - the error is raised, but adding that to the description is nice to have)
On a side note, I'd also consider an alternative way of implementing it:
1) I'd expect `fqdn` to be always unique and in that case it's feasible to use it as a primary key. Right now we can specify same fqdn in the same VRF multiple times by using unique names. If we can imagine a real case with the same fqdn in different VRFs (I can't) - I'd keep name as primary key, but it would be great to check that vrf/fqdn combination is unique.
2) Can we make name optional for single cluster cases? It's not too hard to add it, but single cluster will be the majority and less input is good.

2025-06-24 10:52 UTC, ankudinov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +      terminattr_disable_aaa:
Honestly, I'd make it a dict and replicate terminattr data model inside. But current way also works for me.

```yaml
cv_settings:
  daemon_terminattr:
    smashexcludes:
    ingestexclude:
    disable_aaa:
```

The only reason is to keep the original data model as it's the same thing in essence.

2025-06-24 10:52 UTC, ankudinov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +              pattern: "^[a-z1-9\\.-]+\\.arista\\.io$"
daemon_terminattr > cvaddrs was allowing patterns like: `apiserver.cv-staging.corp.arista.io:443`. TBH, I was never using anything except 443, but should be keep an option to specify the port just in case? I'm OK to skip this though as worst case we can always use daemon_terminattr for corner cases.

2025-06-24 10:52 UTC, ankudinov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +            fqdn:
daemon_terminattr also had an option to stream to multiple nodes using the same token, which we are loosing in this case. Not sure it's critical, but can be helpful in case of DNS setup challenges.

2025-06-24 11:30 UTC, ankudinov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                Short name for the CVaaS cluster. Used when configuring multiple clusters.
As discussed internally - disregard the comment about unique vrf/fqdn.

2025-06-24 11:34 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +              pattern: "^[a-z1-9\\.-]+\\.arista\\.io$"
cvaas only supports 443. We can add a port knob if it ever becomes relevant.

2025-06-24 11:35 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +            fqdn:
Right, you cannot enter more than one url per cluster, but is that really something people do? I would like to avoid adding a list level if possible.

2025-06-24 11:36 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +# Copyright (c) 2023-2025 Arista Networks, Inc.
We are not changing anything about that. Using cli_gen models will work as long as you don't try to _also_ set eos_designs inputs. If you wish to combine you need the `custom_structured_configuration_daemon_terminattr` variant.

2025-06-24 11:37 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +              pattern: "^[a-z1-9\\.-]+\\.arista\\.io$"
People can also just override with structured config

2025-06-24 11:42 UTC, ankudinov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +            fqdn:
Agreed. We can always use daemon_terminattr for that.

2025-06-24 11:46 UTC, ankudinov approved these changes
LGTM

2025-06-25 14:26 UTC, dgonzalez85 commented
Summary of the testing:

Config on-prem:
```
cv_settings:
  onprem_clusters:
    - name: act
      servers:
        - name: 192.168.0.5
```
Renders:
```
-cvauth=token,/tmp/token
-cvaddr=192.168.0.5:9910

L2LS with OOB: -cvvrf=MGMT -cvsourceintf=Management1
L2LS Inband: -cvvrf=default  -cvsourceintf=Vlan4092
L2LS Inband non-default VRF: -cvvrf=InbandMGMT -cvsourceintf=Vlan4092
L3LS with OOB: -cvvrf=MGMT -cvsourceintf=Management1
L3LS with Inband: -cvvrf=default -cvsourceintf=Loopback0
```

Config cvaas:
```
cv_settings:
  cvaas:
    enabled: true
    clusters:
      - name: cvaas
        region: auto
  terminattr_disable_aaa: true
```
Renders:
```
-cvaddr=apiserver.arista.io:443
-cvauth=token-secure,/tmp/cv-onboarding-token
-disableaaa

L2LS with OOB: -cvvrf=MGMT -cvsourceintf=Management1
L2LS Inband: -cvvrf=default -cvsourceintf=Vlan4092
L2LS Inband non-default VRF: -cvvrf=InbandMGMT -cvsourceintf=Vlan4092
L3LS with OOB: -cvvrf=MGMT -cvsourceintf=Management1
L3LS with Inband: -cvvrf=default -cvsourceintf=Loopback0
```

LGTM!

2025-06-25 15:28 UTC, gmuloc commented on ansible_collections/arista/avd/examples/cv-pathfinder/group_vars/WAN/management.yml
> -# **edit the cvp_instance_ips to match your CVaaS region**
you should probably keep this in the example as it is then rendered in the doc: https://avd.arista.com/5.4/ansible_collections/arista/avd/examples/cv-pathfinder/index.html#management

2025-06-25 20:33 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cvp_token_file.schema.yml
> +      new_key: cv_settings.onprem_clusters[].token_file or cv_settings.cvaas.token_file
```suggestion
      new_key: cv_settings.onprem_clusters[].token_file or cv_settings.cvaas.clusters[].token_file
```

2025-06-25 20:33 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +        default: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
CV/EoS documentation does not mention this key in default/suggested config. CV's ZTP and TA Studio logic do not render this key with it's default values as well (since late 2022). AVD should as well not render these default values.

2025-06-25 20:33 UTC, alexeygorbunov commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-settings.cfg
> +   exec /usr/bin/TerminAttr -cvopt cvaas-oob.addr=apiserver.arista.io:443 -cvopt cvaas-oob.auth=token-secure,/tmp/cv-onboarding-token -cvopt cvaas-oob.vrf=MGMT -cvopt cvaas-oob.sourceintf=Management1
Order of TA keys/settings rendered by AVD/cli_config_gen seem to not match the order of the default config in CV documentation and order of rendering keys/settings by CV's `Streaming Telemetry Agent` and ZTP logic.
This may create additional diff (sometimes just false-positive as keys are simply reordered without being changed) between DC and RC when user switches between different config approaches (ZTP/AVD/Studio). It would be helpful to use the same rendering order across all configuration approaches to make sure user can get to the same final result by using any config option.

2025-06-25 20:33 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                    - play
Should we put a note here to the customers that these clusters are for internal Arista purposes only and can not be used by the customers?

2025-06-25 20:33 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/structured_config/underlay/dhcp_servers.py
> +            return next(iter(self.inputs.cv_settings.onprem_clusters)).name
Name of the on-prem cluster here may not be DNS-resolvable, routable or responding to HTTP(s). Option 67 should be instead pointing to the FQDN/IP of the first node of the cluster
```suggestion
            return next(iter(next(iter(self.inputs.cv_settings.onprem_clusters)).servers)).name
```

2025-06-25 20:33 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +            source_interface:
TA binary has quite many configuration parameters. If we eventually need to add them here - we'll be duplicating them for both cvaas and on-prem. Is there a way to define them in one place and reuse?

There is also another approach (used by TA studio) which treats CVaaS just as a single-node cluster with port 443 instead of 9910. This would simplify schema a bit and would resolve any need for key duplication

2025-06-25 20:33 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                  pattern: "^[a-zA-Z1-9-_]+$"
Is this patterns enforced anywhere on TA side? It seems like TA is accepting any non-empty string and i would assume some customers would want to name their clusters using FQDNs (containing dots) as this would be matching on-prem clusters HTTPS LB VIPs

2025-06-25 20:33 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        )
```yaml
cv_settings:
  cvaas:
    enabled: false
```

produces TA config without any targeted clusters. Maybe we should not set `self.structured_config.daemon_terminattr` unless there is at least one cvaas or on-prem cluster present in the input?

2025-06-25 20:33 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                    If not set, the source interface may be set automatically set when VRF is set to `use_mgmt_interface_vrf` and `use_inband_mgmt_vrf`.
```suggestion
                    If not set, the source interface may be set automatically when VRF is set to `use_mgmt_interface_vrf` and `use_inband_mgmt_vrf`.
```

2025-06-25 20:33 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +            Unless `key` is set, TerminAttr will be configured with certificate based authentication.
Which `key`?

2025-06-25 20:33 UTC, alexeygorbunov commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-settings.cfg
> +   exec /usr/bin/TerminAttr -cvopt cvaas-oob.addr=apiserver.arista.io:443 -cvopt cvaas-oob.auth=token-secure,/tmp/cv-onboarding-token -cvopt cvaas-oob.vrf=MGMT -cvopt cvaas-oob.sourceintf=Management1
`cvass.clusters.token_file` and `onprem_clusters.servers.token_file` need to all be unique keys. Config line above (generated with multiple clusters all falling back to the default token_file) produce TA config where multiple "clusters/tenants" are pointing to the same token file (which is supposed to contain onboarding token).
This config will be OK if such TA config is applied to the switch where onboarding tokens were already (somehow) exchanged to the client certs from each tenant (those client certs will be saved into unique paths on the /persist, based on the cluster name).
But if such TA config is applied to the devices which is supposed to go through the onboarding (exchange of multiple onboarding tokens for the client certs) - this will not work as onboarding tokens must be unique per CVaaS tenent / onprem_cluster

2025-06-26 08:55 UTC, gmuloc requested changes

2025-06-26 08:55 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                    If not set, the source interface may be set automatically set when VRF is set to `use_mgmt_interface_vrf` and `use_inband_mgmt_vrf`.
nitpicky but:
```suggestion
                    If not set, the source interface may be set automatically set when VRF is set to `use_mgmt_interface_vrf`, `use_inband_mgmt_vrf` or `use_default_mgmt_method_vrf`.
```

2025-06-26 08:55 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                If not set, the source interface may be set automatically set when VRF is set to `use_mgmt_interface_vrf` and `use_inband_mgmt_vrf`.
same as above:
```suggestion
                If not set, the source interface may be set automatically set when VRF is set to `use_mgmt_interface_vrf`, `use_inband_mgmt_vrf` or `use_default_mgmt_method_vrf`.
```

2025-06-26 08:55 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +           Automatically set source interface when VRF is set to `use_mgmt_interface_vrf` and `use_inband_mgmt_vrf`.
```suggestion
           Automatically set source interface when VRF is set to `use_mgmt_interface_vrf`, `use_inband_mgmt_vrf` or `use_default_mgmt_method_vrf`.
```

2025-06-26 08:55 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +        description: |-
```suggestion
        # TODO: AVD7.0 remove mention of `cv_instances` in description
        description: |-
```

2025-06-26 08:55 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/structured_config/base/utils.py
> +                return self.shared_utils.inband_mgmt_interface
is no tool complaining about missing an explicit return?

2025-06-26 08:55 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/structured_config/base/utils.py
> +        # source_interface may be overridden below if given in the 'vrfs'
I am not sure this comment makes sense anymore
```suggestion
        # if an override is provided return it
```

2025-06-26 08:55 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        The schema will enforce that we only use either new or old models.
The schema would block a conjunction of say 
```
cv_settings:
  cvaas:
    enabled: true
```
 and `terminattr_smashexcludes` 

given that `terminattr_smashexcludes` would complain only if the following was set

```
cv_settings:
  cvaas:
    enabled: true
  terminattr_smashexcludes: ...
```

so if I have

```
cv_settings:
  cvaas:
    enabled: true
terminattr_smashexcludes: BLAH
```

I end up with

```
+  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
```

in my structured_config which can be counter intuitive and hard to catch

2025-06-26 08:55 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        The schema will enforce that we only use either new or old models.
also the error message looks like:

```
The input data model 'terminattr_smashexcludes' is deprecated and cannot be used in conjunction with the new data model '.cv_settings.terminattr_smashexcludes'.
```

the `.` in front of `cv_settigns` could be confusing..

maybe we could add something that if the replacement key starts with `/` (for root) then we don't inject the statring `.`?

2025-06-26 11:18 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/examples/cv-pathfinder/group_vars/WAN/management.yml
> -# **edit the cvp_instance_ips to match your CVaaS region**
Probably better to not have the region set here at all then. Then we need to set it for our testing.

2025-06-26 11:18 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/examples/cv-pathfinder/group_vars/WAN/management.yml
> +        region: staging
```suggestion
```

2025-06-26 11:19 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +        default: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
agreed. I will remove it. Thanks!

2025-06-26 11:20 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-settings.cfg
> +   exec /usr/bin/TerminAttr -cvopt cvaas-oob.addr=apiserver.arista.io:443 -cvopt cvaas-oob.auth=token-secure,/tmp/cv-onboarding-token -cvopt cvaas-oob.vrf=MGMT -cvopt cvaas-oob.sourceintf=Management1
I am not touching eos_cli_config_gen in this PR, so cannot influence that.

2025-06-26 11:21 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                    - play
They will find out :) I'd rather not attract extra attention on these.

2025-06-26 11:21 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/underlay/dhcp_servers.py
> +            return next(iter(self.inputs.cv_settings.onprem_clusters)).name
absolutely. Thank you for catching.

2025-06-26 11:23 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +            source_interface:
We can use $ref if it becomes important. But note these settings are only added per cluster, where we have fewer available settings. The rest are added under the common settings with exclude, disable_aaa etc.

2025-06-26 11:25 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-settings.cfg
> +   exec /usr/bin/TerminAttr -cvopt cvaas-oob.addr=apiserver.arista.io:443 -cvopt cvaas-oob.auth=token-secure,/tmp/cv-onboarding-token -cvopt cvaas-oob.vrf=MGMT -cvopt cvaas-oob.sourceintf=Management1
They may be onboarded one-by-one where it _will_ work with the same token file. But that is probably too confusing. But since we have a default value, I cannot also do unique_keys. And I prefer the default value :)

2025-06-26 11:26 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                    If not set, the source interface may be set automatically set when VRF is set to `use_mgmt_interface_vrf` and `use_inband_mgmt_vrf`.
I used the same as we have on the others, but sure.

2025-06-26 11:30 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-settings.cfg
> +   exec /usr/bin/TerminAttr -cvopt cvaas-oob.addr=apiserver.arista.io:443 -cvopt cvaas-oob.auth=token-secure,/tmp/cv-onboarding-token -cvopt cvaas-oob.vrf=MGMT -cvopt cvaas-oob.sourceintf=Management1
Once CV team has standardized on one config in all cases we can rework ours to match.

2025-06-26 11:31 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +            Unless `key` is set, TerminAttr will be configured with certificate based authentication.
legacy stuff (this PR started two years ago). Removed :)

2025-06-26 11:33 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        The schema will enforce that we only use either new or old models.
yes a fix for another PR :)

2025-06-26 11:34 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        The schema will enforce that we only use either new or old models.
I can change the new_key to cv_settings on all of them if that is better?

2025-06-26 11:36 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        )
fixed

2025-06-26 11:37 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/base/utils.py
> +                return self.shared_utils.inband_mgmt_interface
no because the type checker knows we cover all cases. Aparently ruff does as well :)

2025-06-26 11:40 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                    - play
i added a comment after all

2025-06-26 11:42 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                  pattern: "^[a-zA-Z1-9-_]+$"
I did check various docs, but nothing is clearly stated. Since dot is used as separator on the terminattr commands, I doubt it is accepted as name. Ex. `-cvaddr=10.1.0.1:1234 -cvauth=none -cvopt foo.addr=1.2.3.4:5678 -cvopt foo.auth=none`

2025-06-26 11:58 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        The schema will enforce that we only use either new or old models.
I updated the new_key on all of them to just say `cv_settings`. We still need to fix the leading .

2025-06-26 12:13 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        The schema will enforce that we only use either new or old models.
Fixed:
```
ERROR! [pf1]: The input data model 'terminattr_smashexcludes' is deprecated and cannot be used in conjunction with the new data model 'cv_settings'. This usually happens when a data model has been updated and custom structured configuration still uses the old model. See the porting guide on https://avd.arista.com for details.
ERROR! [pf2]: The input data model 'terminattr_smashexcludes' is deprecated and cannot be used in conjunction with the new data model 'cv_settings'. This usually happens when a data model has been updated and custom structured configuration still uses the old model. See the porting guide on https://avd.arista.com for details.
ERROR! [site1-wan1]: The input data model 'terminattr_smashexcludes' is deprecated and cannot be used in conjunction with the new data model 'cv_settings'. This usually happens when a data model has been updated and custom structured configuration still uses the old model. See the porting guide on https://avd.arista.com for details.
ERROR! [site1-wan2]: The input data model 'terminattr_smashexcludes' is deprecated and cannot be used in conjunction with the new data model 'cv_settings'. This usually happens when a data model has been updated and custom structured configuration still uses the old model. See the porting guide on https://avd.arista.com for details.
```

2025-06-26 12:15 UTC, gmuloc commented on ansible_collections/arista/avd/examples/cv-pathfinder/group_vars/WAN/management.yml
> -# **edit the cvp_instance_ips to match your CVaaS region**
@joelbreton2 for information as this would break your pipeline

2025-06-26 12:18 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        The schema will enforce that we only use either new or old models.
this: ` See the porting guide on https://avd.arista.com for details.` may be problematic I suppose because there is nothing in the porting guide for it but ... not sure we can do anything except removing the suggestion

2025-06-26 12:29 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        The schema will enforce that we only use either new or old models.
yeah once we add it to the porting guide we also remove the keys, so this error would not show up.

2025-06-26 12:58 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/base/daemon_terminattr.py
> +        The schema will enforce that we only use either new or old models.
removed it

2025-06-26 14:48 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-settings.cfg
> +   exec /usr/bin/TerminAttr -cvopt cvaas-oob.addr=apiserver.arista.io:443 -cvopt cvaas-oob.auth=token-secure,/tmp/cv-onboarding-token -cvopt cvaas-oob.vrf=MGMT -cvopt cvaas-oob.sourceintf=Management1
Accepting current behavior to keep the default value.

2025-06-26 16:48 UTC, alexeygorbunov commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/cv_settings.schema.yml
> +                  pattern: "^[a-zA-Z1-9-_]+$"
true! tested with 4.33.0 (TA 1.35.0) and although CLI accepts dotted cluster names - TA later fails to parse arguments

```bash
invalid value "staging.cluster.addr=apiserver.cv-staging.corp.arista.io:443" for flag -cvopt: expected form is cluster.option=value, invalid option specified: cluster.addr
```

2025-06-26 22:19 UTC, alexeygorbunov commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-settings.cfg
> +   exec /usr/bin/TerminAttr -cvopt cvaas-oob.addr=apiserver.arista.io:443 -cvopt cvaas-oob.auth=token-secure,/tmp/cv-onboarding-token -cvopt cvaas-oob.vrf=MGMT -cvopt cvaas-oob.sourceintf=Management1
I guess this also may become a problem later when switch with such TA config needs to be re-onboarded to one of the CV/CVaaS cluster/tenant. Pasting new onboarding token to the file shared by multiple clusters in TA's config and restarting TA may lead to unexpected results

2025-06-27 06:11 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-settings.cfg
> +   exec /usr/bin/TerminAttr -cvopt cvaas-oob.addr=apiserver.arista.io:443 -cvopt cvaas-oob.auth=token-secure,/tmp/cv-onboarding-token -cvopt cvaas-oob.vrf=MGMT -cvopt cvaas-oob.sourceintf=Management1
I think it will just lead to it not working for one of the clusters :)

2025-06-27 06:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-settings.cfg
> +   exec /usr/bin/TerminAttr -cvopt cvaas-oob.addr=apiserver.arista.io:443 -cvopt cvaas-oob.auth=token-secure,/tmp/cv-onboarding-token -cvopt cvaas-oob.vrf=MGMT -cvopt cvaas-oob.sourceintf=Management1
this is a corner case of a corner case. I don't think we need to keep digging into this. Few people stream to multiple cluster. Fewer even stream to multiple of each type.

2025-06-27 13:49 UTC, gmuloc approved these changes

2025-06-27 14:08 UTC, merged