Feat(eos_designs): Add RD and RT override for VRFs
aristanetworks/ansible-avd pull request #3419
Opened 2023-12-12 11:10 UTC by bjmeuer

## Change Summary

Added the possibility to override the RD and RT values for VRFs. 

## Related Issue(s)

Fixes #3296

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes
Added RD and RT override for VRFs in similar way it was already available for l2vlans

```
tenants:
  - name: TENANT1
    mac_vrf_vni_base: 10000
    vrfs:
      - name: VRF1
        vrf_id: 1
        rd_override: 111:222
        rt_override: 333:444
        ...
      - name: VRF2
        vrf_id: 2
        rd_override: 999
        rt_override: 999
        ...
```

## How to test
```
tenants:
  - name: TENANT1
    mac_vrf_vni_base: 10000
    vrfs:
      - name: VRF1
        vrf_id: 1
        rd_override: 111:222
        rt_override: 333:444
        ...
      - name: VRF2
        vrf_id: 2
        rd_override: 999
        rt_override: 999
        ...
```

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2023-12-13 12:49 UTC, ClausHolbechArista approved these changes

2023-12-14 14:49 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_designs/schemas/schema_fragments/defs_network_services.schema.yml
> +                  By default the VRF RD will be derived from overlay loopback and vrf_id.
```suggestion
                  By default, the VRF RD will be derived from a pattern defined in `overlay_rd_type`.
```

2023-12-14 14:50 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_designs/schemas/schema_fragments/defs_network_services.schema.yml
> +                  By default the VRF RT will be derived from the vrf_id.
```suggestion
                  By default, the VRF RD will be derived from a pattern defined in `overlay_rt_type`.
```

2023-12-14 14:52 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_designs/schemas/schema_fragments/defs_network_services.schema.yml
> +                    - A single number which will be used in the RD assigned number field instead of vrf_id (see 'overlay_rd_type' for details).
```suggestion
                    - A single number that will be used in the RD assigned number field.
```

2023-12-14 14:57 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_designs/schemas/schema_fragments/defs_network_services.schema.yml
> +                    - A single number which will be used in the RT fields instead of vrf_id (see 'overlay_rt_type' for details).
```suggestion
                    - A single number will be used in the RT assigned number subfield (second part of the RD).
```

2023-12-14 16:59 UTC, philippebureau approved these changes
Tested, LGTM
I would commit Carl`s suggestions on the documentation

2023-12-14 18:02 UTC, carlbuchmann requested changes
LGTM, small suggestion on the documentation

2023-12-14 19:04 UTC, bjmeuer commented
> LGTM, small suggestion on the documentation

Thanks for the review, I commited your suggestions

2023-12-14 20:59 UTC, carlbuchmann approved these changes
LGTM

2023-12-14 20:59 UTC, merged

2023-12-15 09:34 UTC, forcecity commented
I have 2 points to double check with you:
1. You have added rt_override, but for the logic of it, I’m just a little bit confused from your source code (router_bgp.py):
`def get_vrf_rt(self, vrf: dict) -> str:
        """
        Return a string with the route-target for one VRF
        """
        rt_override = default(vrf.get("rt_override"))

        if ":" in str(rt_override):
            return rt_override

        if rt_override is not None:
            return f"{rt_override}:{rt_override}"
        elif self._vrf_rt_admin_subfield is not None:
            admin_subfield = self._vrf_rt_admin_subfield
        elif self.shared_utils.overlay_rt_type["vrf_admin_subfield"] == "vrf_vni":
            admin_subfield = self.get_vrf_vni(vrf)
        else:
            # Both for 'id' and 'vrf_id' options.
            admin_subfield = self.get_vrf_id(vrf)
        return f"{admin_subfield}:{self.get_vrf_id(vrf)}"
`
On this line: return f"{rt_override}:{rt_override}", would it be return f”{ admin_subfield }:{ rt_override }”? Or you could define a new var like “assigned_number_subfield” and assign the rt_override value to it.

If I understand correctly from the eos_designs.schema, A single number will be used in the RT assigned number subfield (second part of the RT). But if you specify like the yellow line, the result will be different. By default, the “admin_subfield” will be vrf_id, and if I set different vrf_id and rt_override. In our deployment, it should be OK, but other customers may confuse about this behavior. What do you think?
2. I think there is a typo in schema (arista/avd/roles/eos_designs/schemas/schema_fragments/defs_network_services.schema.yml), line 308, it should be "the VRF **RT** will be derived"

2023-12-15 09:37 UTC, ClausHolbechArista commented
@forcecity very good catch! We should also be respecting the admin_subfield setting if you give rt_override (without colon). I will fix this in a new PR.