Feat(eos_designs): Single uplink to mlag pair, mlag_on_orphan_port_channel_downlink
aristanetworks/ansible-avd pull request #3495
Opened 2024-01-15 15:14 UTC by jrecchia1029

## Change Summary

Fixes an existing bug in designs where there is a standalone switch with just a single link to just one switch of an mlag pair where AVD will unnecessarily make the port-channel created on the mlag pair towards the standalone switch an MLAG port-channel which prevents LACP on the link between the standalone switch and the single switch of the mlag pair from forming.

## Related Issue(s)

Fixes #3459 

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

Add the logic to make a fabric port-channel an MLAG port-channel only if the switch where we are configuring the port-channel or its mlag peer connect to a single logical switch.

## How to test

Added a molecule test with a topology that triggers this condition
## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-01-26 09:35 UTC, ClausHolbechArista requested changes
Reviewed configs and they seem correct. The change to an existing test case is also correct, *but* that shows that existing deployments may be impacted by this. I have tested in lab, and single connected port-channels with mlag configured still function. The mlag command will not do anything and can be removed without impact. But since this is changing existing config - causing concern, I think we need to put this behavior behind a knob `single_uplink_switch_mlag: <bool; default=True>` which we can then flip to default False in AVD 5.0

2024-01-29 16:41 UTC, jrecchia1029 reviewed
LGTM

2024-01-29 18:53 UTC, ClausHolbechArista approved these changes

2024-01-31 12:28 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/underlay/port_channel_interfaces.py
> +            if self.shared_utils.mlag is True and (get(self._hostvars, "mlag_on_orphan_port_channel_downlink", default=True) or link.get("mlag", True)):
This is tricky to link the comment and the boolean expressions underneath as all of them are inverted and the comment is incomple (it also requires `self.shared_utils.mlag` to be True to configure MLAG

Maybe using `any` would make it clearer (disclaimer this was handtyped in Github, python code may need adjusting)

```suggestion
        # Configure MLAG on MLAG switches if either 'mlag_on_orphan_port_channel_downlink' or 'link.mlag' is True
        if self.shared_utils.mlag is True and any([get(self._hostvars, "mlag_on_orphan_port_channel_downlink", default=True), link.get("mlag", True)]):
```

2024-01-31 12:28 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_designs/docs/tables/fabric-settings.md
> +    # If `false` an MLAG ID will only be configured on Port-Channel Downlinks dual-homed to two MLAG switches.
```suggestion
    # If `true` (default) an MLAG ID will always be configured on a Port-Channel downlink even if the downlink is only on one MLAG switch.
    # If `false` an MLAG ID will only be configured on Port-Channel downlinks dual-homed to two MLAG switches.
```

2024-01-31 12:28 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/SINGLE_LINK_TO_MLAG_PAIR.yml
> +mlag_on_orphan_port_channel_downlink: false
is the behavior with`true` being tested anywhere? (I mean explicitly tested to check the difference between true and false)

2024-01-31 12:28 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/SINGLE_LINK_TO_MLAG_PAIR.yml
> +      uplink_interfaces: ['Ethernet27']
looking at the code it would be interesting to test a single switch in an MLAG pair connected twice to the same uplink switch

```
- group: SL-LEAF2
   uplink_interfaces: [Ethernet41, Ethernet42]
   uplink_switches: [SL-LEAF0B, SL-LEAF0B]
      nodes:
        - name: SL-LEAF2A
          id: 3
          uplink_switch_interfaces:[Ethernet41, Ethernet42]
        - name: SL-LEAF2B
          id: 4
          uplink_switch_interfaces:[Ethernet43, Ethernet44]
```

as it would probably trigger the `uplink["peer_mlag"] = len(unique_uplink_switches) > 1`

2024-01-31 15:36 UTC, jrecchia1029 commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/SINGLE_LINK_TO_MLAG_PAIR.yml
> +      uplink_interfaces: ['Ethernet27']
Just ran that test case and the port-channel on SL-LEAF0B is configured properly without the `mlag` statement but the actual ethernet interfaces are members of the wrong port-channel

**SL-LEAF0B**
```
interface Port-Channel41
   description SL-LEAF2_Po41
   no shutdown
   switchport
   switchport trunk allowed vlan none
   switchport mode trunk
!
interface Ethernet41
   description SL-LEAF2A_Ethernet41
   no shutdown
   channel-group 41 mode active
!
interface Ethernet42
   description SL-LEAF2A_Ethernet42
   no shutdown
   channel-group 41 mode active
!
interface Ethernet43
   description SL-LEAF2B_Ethernet41
   no shutdown
   channel-group 41 mode active
!
interface Ethernet44
   description SL-LEAF2B_Ethernet42
   no shutdown
   channel-group 41 mode active
!
```

However, the port-channels on SL-LEAF2A and SL-LEAF2B do have the `mlag` statement configured on them.

**SL-Leaf-2A**
```
interface Port-Channel41
   description SL-LEAF0_Po41
   no shutdown
   switchport
   switchport trunk allowed vlan none
   switchport mode trunk
   mlag 41
!
interface Ethernet41
   description SL-LEAF0B_Ethernet41
   no shutdown
   channel-group 41 mode active
!
interface Ethernet42
   description SL-LEAF0B_Ethernet42
   no shutdown
   channel-group 41 mode active
!
```

2024-01-31 16:25 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/SINGLE_LINK_TO_MLAG_PAIR.yml
> +      uplink_interfaces: ['Ethernet27']
as discussed offline - this actually works and does not trigger the stuff I was raving about :) closing this

2024-01-31 16:50 UTC, jrecchia1029 commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/SINGLE_LINK_TO_MLAG_PAIR.yml
> +mlag_on_orphan_port_channel_downlink: false
I don't think so

2024-01-31 17:22 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/SINGLE_LINK_TO_MLAG_PAIR.yml
> +mlag_on_orphan_port_channel_downlink: false
True is the default and before adding this we saw a change on another device, where our changes here removed mlag. After adding this knob, we no longer change that other leaf. So effectively yes, we are testing it there. I need to check commit history to figure out where it was.

2024-01-31 17:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/SINGLE_LINK_TO_MLAG_PAIR.yml
> +mlag_on_orphan_port_channel_downlink: false
![image](https://github.com/aristanetworks/avd/assets/48674677/19f210d3-05be-4993-9d44-5bbb8945ddbf)
This was the other switch being changed before we added the toggle for this behavioral change.

2024-02-02 13:32 UTC, emilarista approved these changes
Tested with double and single uplink to same parent and, LGTM!

2024-02-06 07:23 UTC, ClausHolbechArista commented
Approved. I will resolve the conflict once we have merged #3584

2024-02-06 13:58 UTC, merged