Add SVI Profile capability
aristanetworks/ansible-avd pull request #353
Opened 2020-11-06 08:21 UTC by titom73

## Change Summary

Implement profile management to apply on SVI interface

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #349 
Fixes #352

## Component(s) name

Role: `eos_l3ls_evpn`

## Proposed changes

Create a structure named `svi_profiles` to define a list of pre-configured parameters to apply on multiple SVI.

A new key is created at SVI level to apply profile.

Once PR #337 and #345 will be merged, these features will be applied as well.

## How to test

In Tenant Networks configuration, create `svi_profiles` structure:

```yaml
---
# SVI Profile
svi_profiles:
  GENERIC_DC_PROFILE:
    mtu: 1500
    enabled: false
```

In SVI configuration, apply profile when required:

```yaml
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      TENANT_A_PROJECT01:
        vrf_vni: 11
        svis:
          110:
            name: 'PR01-DMZ'
            tags: [DC1]
            enabled: true
            ip_address_virtual: 10.1.10.254/24
            igmp_snooping_enabled: false
          112:
            tags: [DC1]
            name: 'PR01-DMZ'
            profile: GENERIC
            ip_address_virtual: 10.1.11.254/24
```

## Todo

- [ ] Update documentation
- [ ] Implement keys related to #337 and #345 

## Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2020-11-12 21:05 UTC, carlbuchmann commented
Requires #345 to be merged and incorporated before proceeding.

2020-11-13 18:45 UTC, blemmenes commented
Is this expected to get backported in to v1.1.x or will we have to cherry-pick this to get the fix for #352 ?

2020-11-15 14:36 UTC, carlbuchmann commented
> Is this expected to get backported in to v1.1.x or will we have to cherry-pick this to get the fix for #352 ?

@blemmenes - I just updated the milestone, this will be targeted for release 1.1.1 - https://github.com/aristanetworks/ansible-avd/milestone/6

2020-11-16 18:45 UTC, titom73 commented
MKdocs issue seems to be a DNS resolution issue. Can be ignored since, after manual check, the link is working

2020-11-28 15:06 UTC, titom73 commented
Ready for review

2020-11-29 18:47 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/tenant_evpn_vxlan/leaf-tenant-vlan-interfaces.j2
> +    ip_virtual_router_address: {{ profile.per_svi.ip_virtual_router_address if profile.per_svi.ip_virtual_router_address is defined else profile.svi_profile.ip_virtual_router_address }}
ip_virtual_router_address needs to render only the address and not the mask
update logice to include ipaddr filter: {{ profile.per_svi.ip_virtual_router_address | ipaddr('address') if profile.per_svi.ip_virtual_router_address is defined else profile.svi_profile.ip_virtual_router_address | ipaddr('address') }}

2020-11-29 19:01 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/tenant_evpn_vxlan/leaf-tenant-vlan-interfaces.j2
> +{%                 set profile.exist = false %}
This doesn't appear to be used elsewhere in the code

2020-11-29 19:02 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/tenant_evpn_vxlan/leaf-tenant-vlan-interfaces.j2
> +{%                             set profile.exist = true %}
{% set profile.exist = true %} doesn't appear to be used elsewhere in the code.

2020-11-29 19:11 UTC, carlbuchmann requested changes
Some slight corrections before this can be merged, please in-line comments!

2020-11-29 19:20 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_l3ls_evpn/README.md
> +    ip_address_virtual: < IPv4_address/Mask >
add:
```yaml
ip_virtual_router_address: < IPv4_address/Mask >
ip_address_virtual_secondary: < IPv4_address/Mask >
```

2020-11-29 21:33 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/tenant_evpn_vxlan/leaf-tenant-igmp-snooping.j2
> +{%                      set profile.exist = false %}
Update with new namespace format
`per_svi.values` & `profiles.values`

2020-11-30 01:03 UTC, carlbuchmann approved these changes
LGTM - please validate my updates!

2020-11-30 08:23 UTC, merged