Feat(eos_cli_config_gen): Add support for monitor layer1
aristanetworks/ansible-avd pull request #3540
Opened 2024-01-24 13:42 UTC by Shivani-gslab

## Change Summary

Adding monitor_layer1 data-model

## Related Issue(s)

Fixes #3338 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

## How to test

molecule converge -s eos_cli_config_gen

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-01-31 07:11 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/monitor-layer1.j2
> +| transceiver communication | {{ monitor_layer1.logging_transceiver.communication | arista.avd.default(false) }} |
```suggestion
| MAC fault | {{ monitor_layer1.logging_mac_fault | arista.avd.default(false) }} |
| Transceiver DOM | {{ monitor_layer1.logging_transceiver.dom | arista.avd.default(false) }} |
| Transceiver communication | {{ monitor_layer1.logging_transceiver.communication | arista.avd.default(false) }} |
```

2024-01-31 07:11 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/monitor-layer1.md
> +| transceiver communication | True |
```suggestion
| MAC fault | True |
| Transceiver DOM | True |
| Transceiver communication | True |
```

2024-02-09 15:01 UTC, emilarista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/tables/monitor-layer1.md
I think this table needs to get inserted into the docs/input-variables.md file so it actually gets featured in the generated documentation on avd.arista.com and the CI-generated docs site. Apart from this, LGTM!

2024-02-13 12:37 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/tables/monitor-layer1.md
Good catch. @Shivani-gslab please make sure to add the table to the input-variables.md file. I think there is a `monitoring` section or similar.

2024-02-13 13:22 UTC, Shivani-gslab commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/tables/monitor-layer1.md
Added, please check the sequence once.

2024-02-15 12:30 UTC, emilarista approved these changes
LGTM!

2024-02-15 15:47 UTC, chetryan requested changes
We should remove the pickle file. Otherwise looks good.

2024-02-15 15:47 UTC, chetryan commented on ansible_collections/arista/avd/roles/eos_designs/schemas/eos_designs.schema.pickle
I think the pickles should no longer be added to PRs.

2024-02-15 15:47 UTC, chetryan commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/eos_cli_config_gen.schema.pickle
I don't think the pickle should be included in a PR

2024-02-16 09:41 UTC, Shivani-gslab commented on ansible_collections/arista/avd/roles/eos_designs/schemas/eos_designs.schema.pickle
Removed it. thanks

2024-02-16 09:41 UTC, Shivani-gslab commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/eos_cli_config_gen.schema.pickle
Removed!

2024-02-16 09:58 UTC, chetryan approved these changes
LGTM!

2024-02-16 09:59 UTC, merged