Refactor(eos_designs): Simplify WAN policies
aristanetworks/ansible-avd pull request #3719
Opened 2024-03-07 13:46 UTC by gmuloc

## Change Summary

Code for WAN policies is getting more and more complex. This PR aims to simplify it, it introduces a level where all the policy is being resolved down to the load balance policy and then a level of rendering to pick only what is required depending on AUtoVPN or CV Pathfinder.

This refactor brings two new error scenarios:
* not possible to deploy a WAN router if it has no common path-group with any of the RRs it should connect to (this can be relaxed later when implementing import path-groups, or how to connect to a pathfinder in a different path-group though some intermediate hop)
* the rendered policies can omit some Applicaiton profile match if said match is limited to only non local path-group (e.g. you have only INET and the policy states that AUDIO can only be on MPLS)

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

* limitation: if a policy defines a match statement but no local path-group exist (which would lead to an empty load-balance policy) then the match statement is not render and so traffic may be caught in a subsequent class.

## How to test

no change in molecule except for reordering of the LAN_HA path-group

## Checklist

### User Checklist

- [x] documentation
- [x] add test for match statement removed

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-03-08 07:23 UTC, ClausHolbechArista requested changes

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-pathfinder-edge-no-common-path-group.cfg
Should we remove this device now, since the name suggest we have it to test no common group, but that is no longer the case.

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/CV_PATHFINDER_TESTS.yml
> +              description: TEMPORARY FOR PR SAKE
does this mean we should remove it again or?

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/router_adaptive_virtual_topology.py
>          Return the policies generated by _augmented_cv_pathfinder_policies popping the `_id` key
A bit more happening now.

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
>      def _wan_policies(self) -> list:
We have a lot of similar named methods now. Should we name these after the input path so `_wan_virtual_topologies_policies`?

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +        This returns a structure where every policy
Missing something?

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +        Update the policy dict with two keys
Either we should add much more detail here, or add some comments throughout this beast :)

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +        if get(policy, "is_default", default=False):
since `is_default` is an internal flag set in the policy, you can use `if policy.get("is_default")` if you like. You know the type.

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +    def _update_policy_match_statements(self, policy: dict) -> None:
Missing something around wan and virtual topology in the name here. (utils neutral to all network services)

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +                raise AristaAvdError("TODO ERROR")
TODO

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +                # Empty load balance policy so skipping
```suggestion
                # Empty load balance policy so skipping
                # TODO: Add "nodes" or similar under the profile and raise here
                # if the node is set and there are no matching path groups.
```

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +                profile_id = get(application_virtual_topology, "id")
If we are not running pathfinder, do we need an ID at all?

A simpler implementation could be to have `required=self.shared_utils.is_cv_pathfinder_router`

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +                    # Storing id as _id to avoid schema validation and be able to pick up in VRFs
I don't think this is true any longer, since we pop the _id.

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +    def _wan_control_plane_profile(self) -> str:
```suggestion
    def _wan_control_plane_profile_name(self) -> str:
```

2024-03-08 07:23 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/utils.py
> +    def _wan_control_plane_application_profile(self) -> str:
```suggestion
    def _wan_control_plane_application_profile_name(self) -> str:
```

2024-03-08 09:35 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-pathfinder-edge-no-common-path-group.cfg
we are using it in HA so probably will just change the name

2024-03-08 12:49 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/cv-pathfinder-edge-no-common-path-group.cfg
removed in 61e331e8

2024-03-08 12:49 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/CV_PATHFINDER_TESTS.yml
> +              description: TEMPORARY FOR PR SAKE
61e331e8

2024-03-12 09:48 UTC, gmuloc commented on ansible_collections/arista/avd/roles/eos_designs/docs/wan-preview.md
> +  - For a given application profile match in a WAN policy, if the path-groups in the input data have an empty intersection with the path-groups on the device (no common path-group), the match stateme
```suggestion
  - For a given application profile match in a WAN policy, if the path-groups in the input data have an empty intersection with the path-groups on the device (no common path-group), the match statement / AVT profile is **NOT** configured on the device. This implies that the traffic could be matched in one of the following application profiles or the default virtual topology. Note that the default virtual topology can be configured to drop traffic.
```

2024-03-12 12:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/python_modules/network_services/application_traffic_recognition.py
> +                            f"The application profile {application_profile} used in policy {policy['name']}  "
```suggestion
                            f"The application profile {application_profile} used in policy {policy['name']} "
```

2024-03-12 12:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/docs/wan-preview.md
> +- All the WAN router must have a common path-group with at least one WAN route server to be able to inject the default control-plane match statement in the VRF default WAN policy.
```suggestion
- All the WAN routers must have a common path-group with at least one WAN route server to be able to inject the default control-plane match statement in the VRF default WAN policy.
```

2024-03-12 12:54 UTC, ClausHolbechArista approved these changes

2024-03-12 16:22 UTC, carlbuchmann approved these changes
LGTM, testing with scenario in lab.
Only observed changes to order in the structured configuration.
No changes to EOS configuration.

2024-03-12 16:22 UTC, merged