Fix(eos_cli_config_gen): make monitor_sessions.[].<sources | destinations> required keys
aristanetworks/ansible-avd pull request #3823
Opened 2024-04-08 17:18 UTC by carlbuchmann

## Change Summary

Make monitor_sessions.[]. sources and  monitor_sessions.[]. destinations required keys in the schemas

```

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.<role-name>`

## Proposed changes

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-04-30 07:50 UTC, ClausHolbechArista approved these changes

2024-04-30 12:50 UTC, gmuloc commented
As discussed on chat with @ClausHolbechArista, this PR could trigger some changes for existing deployment with only source pr destination that will suddenly start to generate config (hence a "breaking change").

I would be in favor of:
1/ Adding a `!` indicating it is breaking (to our output) but it is a bug fix so it is allowed by SemVer
2/ maybe pushing this to 5.0.0 or if we believe we can't wait then making it a patch with an addition in the release notes but we may be argued that we don't follow SemVer stricto sensu

2024-04-30 13:11 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/monitor-sessions.j2
> +| Destinations | {{ monitor_session.destinations | arista.avd.default("-") | join(', ') }} |
```suggestion
| Destinations | {{ monitor_session.destinations | arista.avd.default(["-"]) | join(', ') }} |
```

2024-04-30 18:14 UTC, sugetha24 approved these changes
LGTM

2024-07-31 12:28 UTC, gmuloc commented
@carlbuchmann I think this one should be marked as breaking right? (`!` in the PR title)

2024-08-13 12:46 UTC, ClausHolbechArista approved these changes

2024-08-28 12:56 UTC, gmuloc commented
@carlbuchmann we need to add something in the release notes for the change of behavior for 5.x.x

2024-08-28 12:56 UTC, gmuloc requested changes
blocking until release notes are updated and conflict resolved

2024-09-24 09:41 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +
```suggestion
As of avd 5.0.0 `monitor_sessions` configuration will be generated even if `monitor_sessions.sources` or `monitor_sessions.destinations` are not defined. To revert this behavior update your inventory to remove the configuration.

```

2024-09-24 09:42 UTC, gmuloc approved these changes

2024-09-24 09:43 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/docs/release-notes/5.x.x.md
> +### `monitor_sessions` no longer requires both `monitor_sessions.sources` and `monitor_sessions.destinations` to be defined for generating configuration
```suggestion
#### `monitor_sessions` no longer requires both `monitor_sessions.sources` and `monitor_sessions.destinations` to be defined for generating configuration
```

2024-09-24 11:01 UTC, merged