missing tables script
aristanetworks/ansible-avd pull request #3896
Opened 2024-04-23 14:12 UTC by FrederikOHolbech

script to catch schema tables not covered in role docs

## Change Summary

Script to catch schema table files not covered in role docs files

## Related Issue(s)

Fixes #3025 

## Component(s) name

`arista.avd.<role-name>`

## Proposed changes

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-04-24 06:49 UTC, ClausHolbechArista commented
- Let's add this to `.pre-commit-config.yaml` to run after the schema regeneration steps.
- Print some header and the files missing tables with one table file per line.
- Avoid running the function twice.

2024-04-24 07:04 UTC, ClausHolbechArista commented
Please add an option to ignore certain files.

2024-04-25 13:26 UTC, ClausHolbechArista requested changes

2024-04-25 13:26 UTC, ClausHolbechArista commented on python-avd/scripts/find_missing_tables.py
> +root_path = Path(*args.root_path)
```suggestion
root_path = args.root_path
```

2024-04-25 13:26 UTC, ClausHolbechArista commented on python-avd/scripts/find_missing_tables.py
> +    nargs="*",
```suggestion
```

2024-04-25 13:26 UTC, ClausHolbechArista commented on python-avd/scripts/find_missing_tables.py
> +parser.add_argument("--ignore_files", dest="ignore_files", nargs="*", type=Path, help="The table files to be ignored, when checking for missing table files")
```suggestion
parser.add_argument("--ignore_files", dest="ignore_files", nargs="*", type=Path, help="The table files to be ignored, when checking for missing table files",)
```

2024-04-25 13:26 UTC, ClausHolbechArista commented on python-avd/scripts/find_missing_tables.py
> +ignored_files = list((args.ignore_files))
```suggestion
ignored_files = list(args.ignore_files)
```

2024-04-25 13:51 UTC, ClausHolbechArista commented on .pre-commit-config.yaml
> +        files: ansible_collections/arista/avd/roles/eos_cli_config_gen/docs+/tables
```suggestion
        files: ansible_collections/arista/avd/roles/[a-z_]+/docs
        pass_filenames: false
```

2024-04-25 13:51 UTC, ClausHolbechArista commented on .pre-commit-config.yaml
> +        entry: find_missing_tables.py --table_files_glob "ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/tables/*.md" --markdown_files_glob "ansible_collections/arista/avd/roles/eos_cli
```suggestion
        entry: sh -c 'exec python-avd/scripts/find_missing_tables.py'
        args:
         - '--table_files_glob "ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/tables/*.md"'
         - '--markdown_files_glob "ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/*.md"'
         - '--table_files_glob "ansible_collections/arista/avd/roles/eos_designs/docs/tables/*.md"'
         - '--markdown_files_glob "ansible_collections/arista/avd/roles/eos_designs/docs/*.md"'
         - '--root_path "ansible_collections/arista/avd"'
         - '--ignore_files "roles\eos_cli_config_gen\docs\tables\service-unsupported-transceiver.md"'
```

2024-04-29 06:40 UTC, ClausHolbechArista commented
Please fix issues reported by pre-commit. I will move to draft, so please mark "ready for review" when it is passing CI.

2025-02-19 08:35 UTC, gmuloc commented
Let's close this one and it can be addressed later with the latest changes to the repo

2025-02-19 08:35 UTC, closed without merging