Feat(eos_cli_config_gen): Support for configuring logging facilities
aristanetworks/ansible-avd pull request #3944
Opened 2024-05-06 05:30 UTC by MaheshGSLAB

## Change Summary

Support for configuring logging facilities. Added the function for logging level, facility and severity. 

## Related Issue(s)

Fixes #3740 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Added the support for logging level and severity on facility. 

## How to test
Run molecule

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-05-06 07:24 UTC, Shivani-gslab requested changes

2024-05-06 07:24 UTC, Shivani-gslab commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/logging.j2
> +{%     endif %}
```suggestion
{%     for level in logging.level | arista.avd.natural_sort('facility_name') %}
{%         if level.severity is arista.avd.defined %}
logging level {{ level.facility_name }} {{ level.severity }}
{%         endif %}
{%     endfor %}
```

2024-05-06 07:27 UTC, Shivani-gslab commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +              description: Facility name.
```suggestion
```

2024-05-06 07:27 UTC, Shivani-gslab commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +              description: Facility name.
No need to add the description here as the key name tells the same.

2024-05-06 07:38 UTC, Shivani-gslab reviewed
Please update the documentation template also.

2024-05-07 10:26 UTC, Vibhu-gslab commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/logging.cfg
> +logging level BGP 0
In CLI the output changes to `logging level BGP emergencies`.
May be we can map the numbers with its corresponding values in J2 file (using dict).

2024-05-07 10:26 UTC, Vibhu-gslab commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/logging.j2
> +{%         if level.severity is arista.avd.defined %}
Something like..
```
{%             set severity_mapping = {'0': 'emergencies', '1': 'alerts'} %}
{%             set severity = level.severity %}
{%             if severity in severity_mapping %}
{%                 set severity = severity_mapping[severity] %}
{%             endif %}
logging level {{ level.facility_name }} {{ severity }}
```

2024-05-07 11:32 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/logging.cfg
> +logging level BGP 0
I would prefer not to have such mapping in `eos_cli_config_gen`. Just add valid values for both the names and the numbers and then let the user decide.

2024-05-07 11:45 UTC, Vibhu-gslab commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/logging.cfg
> +logging level BGP 0
Okay :)

2024-05-07 11:45 UTC, Vibhu-gslab approved these changes

2024-05-08 05:16 UTC, Shivani-gslab approved these changes
LGTM

2024-05-08 05:59 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +                warnings       Warning conditions                (severity=4)
```suggestion
                emergencies    System is unusable                (severity=0)
                alerts         Immediate action needed           (severity=1)
                critical       Critical conditions               (severity=2)
                errors         Error conditions                  (severity=3)
                warnings       Warning conditions                (severity=4)
                notifications  Normal but significant conditions (severity=5)
                informational  Informational messages            (severity=6)
                debugging      Debugging messages                (severity=7)
```

2024-05-08 06:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/logging.md
> +| Level Facility | Severity |
```suggestion
| Facility | Severity |
```

2024-05-08 06:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/logging.j2
> +| Level Facility | Severity |
```suggestion
| Facility | Severity |
```

2024-05-08 06:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/logging.j2
> +{%         for level in logging.level | arista.avd.natural_sort('facility_name') %}
```suggestion
{%         for level in logging.level | arista.avd.natural_sort('facility') %}
```

2024-05-08 06:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/logging.j2
> +| {{ level.facility_name }} | {{ level.severity }} |
```suggestion
| {{ level.facility }} | {{ level.severity }} |
```

2024-05-08 06:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/logging.j2
> +logging level {{ level.facility_name }} {{ level.severity }}
```suggestion
logging level {{ level.facility }} {{ level.severity }}
```

2024-05-08 06:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/logging.j2
> +{%     for level in logging.level | arista.avd.natural_sort('facility_name') %}
```suggestion
{%     for level in logging.level | arista.avd.natural_sort('facility') %}
```

2024-05-08 06:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +            facility_name:
```suggestion
            facility:
```

2024-05-08 06:03 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/logging.schema.yml
> +        primary_key: facility_name
```suggestion
        primary_key: facility
```

2024-05-08 06:04 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/logging.j2
> +| -------------- | -------- |
```suggestion
| Facility | Severity |
| -------- | -------- |
```

2024-05-08 06:04 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/logging.md
> +| -------------- | -------- |
```suggestion
| Facility | Severity |
| -------- | -------- |
```

2024-05-08 06:27 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/logging.yml
> +      severity: critical
```suggestion
    - facility: BGP
      severity: 0
    - facility: AAA
      severity: warnings
    - facility: ACL
      severity: critical
```

2024-05-08 06:43 UTC, ClausHolbechArista approved these changes

2024-05-08 07:03 UTC, merged