Fix(cv_workflow): verify if devices have duplicate information
aristanetworks/ansible-avd pull request #3957
Opened 2024-05-07 07:27 UTC by sugetha24

## Change Summary

verify if devices have duplicate information

## Related Issue(s)

Fixes #

## Component(s) name

`arista.avd.cv_workflow`

## Proposed changes

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-05-08 05:54 UTC, ClausHolbechArista requested changes

2024-05-08 05:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/verify_devices_on_cv.py
> +    sysMacToHostname = {}
Please use snake case.

2024-05-08 05:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/verify_devices_on_cv.py
> +    for e in devices:
avoid short variables. It is more clear to use `device` instead of `e`

2024-05-08 05:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/verify_devices_on_cv.py
> +                serialNumToHostname[e.serial_number] = [e.hostname]
```suggestion
            serialNumToHostname.setdefault(e.serial_number, []).append(e.hostname)
```
Same elsewhere.

2024-05-08 05:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/verify_devices_on_cv.py
> +def return_duplicates(found_device_dict_by_serial: dict, found_device_dict_by_system_mac: dict, found_devices: list[Device]) -> Exception:
The code in here is duplicate of the code above. Please work out a good arrangement of the code, where the flow is easy to follow and we avoid deep indentations and repetitions.

2024-05-08 05:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/verify_devices_on_cv.py
> +def return_duplicates(found_device_dict_by_serial: dict, found_device_dict_by_system_mac: dict, found_devices: list[Device]) -> Exception:
You could move this input validation into a function like `validate_input` or similar. Also remember docstring to describe what you are doing in the the function.

2024-05-08 05:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/verify_devices_on_cv.py
> +        return existing_devices
Please remember to revert the indentation of this section. You only reverted the first part.

2024-05-08 05:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/verify_devices_on_cv.py
> +    # This also helps if the same object is used in multiple lists (like interface_tags and device_tags).
This comment was moved from it's place.

2024-05-08 05:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/verify_devices_on_cv.py
> +    hostnamesSameMac = [hostnames for mac, hostnames in sysMacToHostname.items() if len(hostnames) > 1]
Maybe a list is not the best form inside the dict. A set would be better, since we should allow multiple entries with the same information.

2024-05-08 05:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/cv_client/workflows/verify_devices_on_cv.py
> +    # Finding entries with same serialNum or same mac address
Move all this to a function. Maybe it can be shared with the check of the data from CV.

2025-01-09 06:13 UTC, alexeygorbunov commented
Taking over this activity

2025-04-30 18:05 UTC, ClausHolbechArista commented
implemented in another PR

2025-04-30 18:05 UTC, closed without merging