Creating Jinja template and documentation
aristanetworks/ansible-avd pull request #397
Opened 2020-11-27 18:48 UTC by xaviramon

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #37 
## Component(s) name

## Proposed changes

## How to test

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2020-11-28 09:01 UTC, titom73 requested changes
Please update code to remove LACP fallback (https://github.com/aristanetworks/ansible-avd/pull/368) and Storm-control (#306)

2020-11-28 09:01 UTC, titom73 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ethernet-interfaces.j2
> +{%             elif ethernet_interfaces[ethernet_interface].spanning_tree_portfast is defined and ethernet_interfaces[ethernet_interface].spanning_tree_portfast is not none %}
Maybe we can check user configured correct value with a test like:

```jinja2
{% if ethernet_interfaces[ethernet_interface].spanning_tree_portfast in ['auto', 'edge', ''network, 'normal'] %}
```

2020-11-28 09:01 UTC, titom73 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/port-channel-interfaces.j2
> +{%         elif port_channel_interfaces[port_channel_interface].spanning_tree_portfast is defined and port_channel_interfaces[port_channel_interface].spanning_tree_portfast is not none %}
Maybe we can check user configured correct value with a test like:

```jinja2
{% if ethernet_interfaces[ethernet_interface].spanning_tree_portfast in ['auto', 'edge', ''network, 'normal'] %}
```

2020-11-28 09:01 UTC, titom73 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/port-channel-interfaces.j2
> +{%         if port_channel_interfaces[port_channel_interface].storm_control is defined and port_channel_interfaces[port_channel_interface].storm_control is not none %}
Change already covered by PR https://github.com/aristanetworks/ansible-avd/pull/306

2020-11-28 09:01 UTC, titom73 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ethernet-interfaces.j2
> +{%             if ethernet_interfaces[ethernet_interface].storm_control is defined and ethernet_interfaces[ethernet_interface].storm_control is not none %}
Change already covered by PR https://github.com/aristanetworks/ansible-avd/pull/306

2020-11-28 09:01 UTC, titom73 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/port-channel-interfaces.j2
> +{%         if port_channel_interfaces[port_channel_interface].lacp_fallback is defined and port_channel_interfaces[port_channel_interface].lacp_fallback is not none %}
Already covered by https://github.com/aristanetworks/ansible-avd/pull/368

2020-12-11 10:52 UTC, titom73 commented
PR to be updated with:

- [ ] Edge STP modes
- [ ] Storm control for port-channel (to be tested)

2021-01-11 14:55 UTC, carlbuchmann commented
closing due to stale PR

2021-01-11 14:55 UTC, closed without merging