Feat(eos_cli_config_gen): router ospf dont render vrf keyword when de…
aristanetworks/ansible-avd pull request #3976
Opened 2024-05-09 23:32 UTC by pvinci-arista

…fault

## Change Summary

This change changes the rendering of `router ospf <x> vrf default` to `router ospf <x>`

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
added test for default vrf

## How to test
tested with molecule

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-05-10 06:38 UTC, ClausHolbechArista approved these changes
LGTM

2024-05-10 06:41 UTC, ClausHolbechArista requested changes
On second thought, since EOS accepts the current behavior, we should not change this in a minor release. If you don't want the default VRF, you should not set it in the input. So maybe the bug here is in eos_designs. Nevertheless we would have to wait for 5.0.

2024-05-10 13:30 UTC, pvinci-arista commented
This is an artifact of configuring `ospf` under `network services` in the `default` vrf.  Based on where it is configured, I don't see how to not set it.  To remove it would seem to require structured_config on each node.

```
default:
  - name: "default"
    vrfs:
       - name: "default"       
          ospf:
            enabled: true

            process_id: 123
            nodes:
              - SW1
              - SW2
              - SW3
              - SW4
```
  
I agree that this is cosmetic.  Eos does accept the existing rendered config.  Feel free to tag this to the appropriate SemVer release.

2024-05-13 09:02 UTC, ClausHolbechArista commented
@pvinci-arista This should be addressed in `eos_designs` so please adjust the fix accordingly. In parallel we will discuss if this can be merged in a minor or will have to wait for 5.0. @aristanetworks/avd-maintainers

2024-08-08 09:52 UTC, ClausHolbechArista commented
Replaced with #4334

2024-08-08 09:52 UTC, closed without merging