Feat(eos_cli_config_gen): Add support for MACsec fallback to unprotected traffic
aristanetworks/ansible-avd pull request #4028
Opened 2024-05-23 07:36 UTC by Shivani-gslab

## Change Summary

Add support for MACsec fallback to unprotected traffic.

## Related Issue(s)

Fixes #3696 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Adding `traffic_unprotected` to `mac_security` data-model-
```
mac_security:
       traffic_unprotected:

            # Allow/drop the transmit/receive of unprotected traffic.
            action: <str; "allow" | "drop"; required>

            # Allow transmit/receive of encrypted traffic using operational SAK and block otherwise.
            allow_active_sak: <bool>
```

## How to test
Molecule test and test on EOS.

## Checklist

### PR Checklist

- [x] Check the command ordering on EOS.

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-05-23 12:29 UTC, Vibhu-gslab requested changes

2024-05-23 12:29 UTC, Vibhu-gslab commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/mac_security.schema.yml
> +                allow:
`drop` key is missing

2024-05-23 12:29 UTC, Vibhu-gslab commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/mac-security-eth-po-entropy.md
> +      traffic unprotected allow active-sak
table missing for `traffic unprotected`

2024-05-24 13:13 UTC, Shivani-gslab commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/mac-security-eth-po-entropy.md
> +      traffic unprotected allow active-sak
Added

2024-05-24 13:14 UTC, Shivani-gslab commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/mac_security.schema.yml
> +                allow:
Updated the data-model schema.

2024-05-28 13:19 UTC, Vibhu-gslab approved these changes

2024-05-29 07:21 UTC, ClausHolbechArista requested changes
Minor comments. Otherwise looks good to me.

2024-05-29 07:21 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mac-security.j2
> +| Cipher | Key-Server Priority | Rekey-Period | SCI | Traffic Unprotected |
```suggestion
| Cipher | Key-Server Priority | Rekey-Period | SCI | Traffic Unprotected Fallback |
```

2024-05-29 07:21 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/mac-security.j2
> +{%             if profile.traffic_unprotected.action is arista.avd.defined("allow") and profile.traffic_unprotected.allow_active_sak is arista.avd.defined(true) %}
```suggestion
{%             if profile.traffic_unprotected.action == "allow" and profile.traffic_unprotected.allow_active_sak is arista.avd.defined(true) %}
```

2024-05-30 10:57 UTC, MaheshGSLAB approved these changes

2024-05-30 10:59 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/mac-security-eth-po-entropy.md
> +| ------ | ------------------- | ------------ | --- | ------------------- |
```suggestion
| ------ | ------------------- | ------------ | --- | ---------------------------- |
```

2024-05-30 11:01 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/mac-security-eth-po-entropy.md
> +| ------ | ------------------- | ------------ | --- | ------------------- |
```suggestion
| Cipher | Key-Server Priority | Rekey-Period | SCI | Traffic Unprotected Fallback |
| ------ | ------------------- | ------------ | --- | ---------------------------- |
```

2024-05-30 11:02 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mac-security.j2
> +| ------ | ------------------- | ------------ | --- | ------------------- |
```suggestion
| Cipher | Key-Server Priority | Rekey-Period | SCI | Traffic Unprotected Fallback |
| ------ | ------------------- | ------------ | --- | ---------------------------- |
```

2024-05-30 12:32 UTC, Shivani-gslab commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/mac-security.j2
> +| ------ | ------------------- | ------------ | --- | ------------------- |
Fixed

2024-06-03 11:06 UTC, MaheshGSLAB approved these changes

2024-06-03 12:40 UTC, gmuloc approved these changes

2024-06-03 14:07 UTC, ClausHolbechArista approved these changes

2024-06-03 14:37 UTC, merged