Feat(eos_designs): Disable per interface MTU for platforms not suppor…
aristanetworks/ansible-avd pull request #4053
Opened 2024-05-30 08:12 UTC by xaviramon

…ting it.

## Change Summary

On changed platforms, not using the `per_interface_mtu: false` setting, will generate an incorrect MTU configuration in some interfaces, which is not supported on T3.x1, x2 and x4. This brakes MLAG configuration on these devices.

This is not considered a breaking change since using the defined platforms today generates a broken configuration.

## Related Issue(s)

Fixes #4037 

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes
Changing `per_interface_mtu` variable to false  in 750 platforms, 710P, 720DP, 722XPM and creating new platforms for 7010TX and 720DT with the variable set to false.

## How to test
molecule

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-05-30 10:41 UTC, xaviramon commented
Also solving #3123 here

2024-05-30 11:00 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/plugins/plugin_utils/eos_designs_shared_utils/platform.py
>          "platforms": ["720DP", "722XP", "710P"],
Last I checked some platforms in this group was using a different chip. It is unfortunately not the whole family we should enforce this on. This is why we have not addressed the issue. We needed someone to map out all the affected platforms.

2024-05-31 07:53 UTC, ClausHolbechArista requested changes

2024-05-31 07:53 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/intended/configs/750-LEAF.cfg
Please remove the 750 related test, since this is only for 7010TX now.

2024-06-03 13:47 UTC, ClausHolbechArista approved these changes

2024-06-03 13:55 UTC, gmuloc approved these changes

2024-06-03 13:56 UTC, merged