Refactor(plugins): Move jinja filter code for arista.avd.generate_esi to PyAVD
aristanetworks/ansible-avd pull request #4114
Opened 2024-06-13 12:20 UTC by Vibhu-gslab

## Change Summary

Move jinja filter code for arista.avd.generate_esi to PyAVD

## Related Issue(s)

Fixes #4113 

## Component(s) name

`arista.avd.generate_esi`

## Proposed changes
Moving the code and unit tests for arista.avd.generate_esi filter to PyAVD

## How to test
CI should catch things.

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-06-13 17:20 UTC, laxmikantchintakindi commented on python-avd/tests/pyavd/j2filters/test_esi_management.py
> +        esi_prefix = esi_prefix if esi_prefix else DEFAULT_ESI_PREFIX
```suggestion
        esi_prefix = esi_prefix or DEFAULT_ESI_PREFIX
```

2024-06-14 05:10 UTC, Vibhu-gslab commented on python-avd/tests/pyavd/j2filters/test_esi_management.py
> +        esi_prefix = esi_prefix if esi_prefix else DEFAULT_ESI_PREFIX
Fixed!

2024-06-14 06:09 UTC, MaheshGSLAB submitted a review, later dismissed

2024-06-14 06:16 UTC, MaheshGSLAB commented on python-avd/pyavd/j2filters/generate_esi.py
> +def generate_esi(esi_short: str, esi_prefix: str = "0000:0000:") -> str:
please add a doc string

2024-06-14 07:42 UTC, Vibhu-gslab commented on python-avd/pyavd/j2filters/generate_esi.py
> +def generate_esi(esi_short: str, esi_prefix: str = "0000:0000:") -> str:
DOne!

2024-06-14 09:22 UTC, ClausHolbechArista requested changes

2024-06-14 09:22 UTC, ClausHolbechArista commented on python-avd/pyavd/j2filters/generate_esi.py
> +        esi_prefix (str): ESI prefix value, will be concatenated with the `short_esi`
```suggestion
        esi_short: Short ESI value as per AVD definition in eos_designs
        esi_prefix: ESI prefix value, will be concatenated with the `short_esi`
```

2024-06-14 09:22 UTC, ClausHolbechArista commented on python-avd/pyavd/j2filters/generate_esi.py
> +        str: Concatenated string of `esi_prefix` and `short_esi` like `0000:0000:0303:0202:0101`
```suggestion
        Concatenated string of `esi_prefix` and `short_esi` like `0000:0000:0303:0202:0101`
```

2024-06-14 09:22 UTC, ClausHolbechArista commented on python-avd/tests/pyavd/j2filters/test_esi_management.py
> +        assert resp == esi
please add this in it's own test_ file instead of renaming the existing one.

2024-06-14 09:22 UTC, ClausHolbechArista commented on python-avd/Makefile
> +	find $(PACKAGE_DIR) -name '*.py' -exec sed -i -e 's/ansible_collections\.arista\.avd\.plugins\.filter.generate_esi/$(PYAVD_FILTER_IMPORT)\.generate_esi/g' {} +
please sort the alphabetically to make it easier to keep track.

2024-06-14 11:32 UTC, Vibhu-gslab commented on python-avd/pyavd/j2filters/generate_esi.py
> +        esi_prefix (str): ESI prefix value, will be concatenated with the `short_esi`
Fixed!

2024-06-14 11:32 UTC, Vibhu-gslab commented on python-avd/pyavd/j2filters/generate_esi.py
> +        str: Concatenated string of `esi_prefix` and `short_esi` like `0000:0000:0303:0202:0101`
Fixed!

2024-06-14 11:32 UTC, Vibhu-gslab commented on python-avd/tests/pyavd/j2filters/test_esi_management.py
> +        assert resp == esi
Fixed!

2024-06-14 11:32 UTC, Vibhu-gslab commented on python-avd/Makefile
> +	find $(PACKAGE_DIR) -name '*.py' -exec sed -i -e 's/ansible_collections\.arista\.avd\.plugins\.filter.generate_esi/$(PYAVD_FILTER_IMPORT)\.generate_esi/g' {} +
Fixed!

2024-06-14 12:54 UTC, ClausHolbechArista approved these changes

2024-06-14 13:33 UTC, carlbuchmann approved these changes
LGTM

2024-06-14 13:33 UTC, merged