Feat(eos_designs): Underlay OSPF authentication
aristanetworks/ansible-avd pull request #4169
Opened 2024-07-01 20:36 UTC by jonxstill

## Change Summary

Automatic encryption of underlay OSPF message digest keys for use in underlay.

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes

Because OSPF message-digest keys are encrypted in EOS configurations, using the interface name as the key, it requires inline Jinja2 (or offline encryption of keys) to generate the type 7 passwords required.  This PR automates this process.

Schema Changes:
```
underlay_ospf_authentication:
  enabled: true
  message_digest_keys:
    - id: 1
      hash_algorithm: sha512
      key: arista123
```

## How to test
Molecule tests added in `eos_designs_unit_tests` and `evpn_underlay_ospf_overlay_ebgp`.
Test manually by adding above YAML at fabric level with ospf configured as the underlay.

## Checklist

### Repository Checklist

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [X] My change requires a change to the documentation and documentation have been updated accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-07-22 11:11 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/underlay_ospf_authentication_schema.yml
> +                Only plaintext passwords are supported here as the password will need to be encrypted for every underlay interface.
Are we sure we need this? The key could be set under the ospf process instead of per-interface. I think the process id is then used in the hash, so the user could leverage our encrypt filter to generate the correct hash.

2024-07-25 08:45 UTC, jonxstill commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/underlay_ospf_authentication_schema.yml
> +                Only plaintext passwords are supported here as the password will need to be encrypted for every underlay interface.
As discussed just now, EOS only supports per-interface authentication, not per-process or per-area.

2024-07-25 08:53 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/underlay_ospf_authentication_schema.yml
> +                Only plaintext passwords are supported here as the password will need to be encrypted for every underlay interface.
Can we reword this to state that AVD is doing the job of encrypting the password? here it feels like `will need to be encrypted` implies extra work required.

Something like:
```suggestion
                Only plaintext passwords are supported here, the per inteerface hashed password is automatically created by `eos_designs` using the relevant keys.
```

2024-07-26 06:18 UTC, ClausHolbechArista requested changes

2024-07-26 06:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/structured_config/underlay/ethernet_interfaces.py
> +                                        passwd_type="ospf_message_digest",
```suggestion
                                        passwd_type="ospf_message_digest",  # NOSONAR
```

2024-07-26 06:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/underlay_ospf_authentication_schema.yml
> +        type: list
Should we add some min length and max length on this list? As far as I understand the doc, EOS supports one or two keys.
```suggestion
        type: list
        required: true
        primary_key: id
        min_length: 1
        max_length: 2
```

2024-07-26 06:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/underlay_ospf_authentication_schema.yml
> +              type: str
```suggestion
              type: str
              required: true
              convert_types:
                - int
```

2024-07-26 06:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/underlay_ospf_authentication_schema.yml
> +        type: bool
```suggestion
        type: bool
        required: true
```

2024-07-26 11:09 UTC, ClausHolbechArista approved these changes
Looks good to me overall. Suggesting improving the test a bit for two keys but otherwise all good.

2024-07-26 11:09 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/MLAG_OSPF_TESTS.yml
> +      key: arista123arista123
please add two keys here

2024-07-26 11:09 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/underlay_ospf_authentication_schema.yml
> +              description: |
```suggestion
              description: |-
```

2024-07-26 13:33 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/underlay_ospf_authentication_schema.yml
> +              required: true
```suggestion
              required: true
              max_length: 16
              min_length: 1
```

2024-07-26 14:43 UTC, gmuloc approved these changes
LGTM

2024-07-26 15:08 UTC, merged