Doc: Fix incorrect keys specified in default_mgmt_method
aristanetworks/ansible-avd pull request #4206
Opened 2024-07-11 16:10 UTC by carlbuchmann

## Change Summary

Documentation fix of incorrect keys specified in `default_mgmt_method`

2024-07-12 07:32 UTC, gmuloc approved these changes
Indeed these two keys are pending PRs from @ClausHolbechArista which have not merged yet: #3301 and #3283 respectively

2024-07-22 10:56 UTC, ClausHolbechArista requested changes
The proposed changes are misleading, since the keys in question do *not* take this setting into account. Only their new replacements would.

2024-07-22 13:14 UTC, gmuloc commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/default_mgmt_method.schema.yml
> +        - `name_servers`
```suggestion
```

2024-07-23 05:39 UTC, ClausHolbechArista approved these changes

2024-07-23 08:05 UTC, merged