Fix: Incorrect default value for 720XP for trident_forwarding_table_partition
aristanetworks/ansible-avd pull request #4215
Opened 2024-07-15 17:57 UTC by carlbuchmann

## Change Summary

`trident_forwarding_table_partition: "flexible exact-match 16384 l2-shared 98304 l3-shared 131072"` command on the 720XP is no valid because the table sizes differ from the 7050X platforms the original default was based on.

New suggested default: `trident_forwarding_table_partition: "flexible exact-match 16000 l2-shared 18000 l3-shared 22000`.

2024-07-22 10:52 UTC, ClausHolbechArista requested changes

2024-07-22 10:52 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/evpn_multicast.schema.yml
> +        The Following default platform setting will be configured on 7050X3 and 7300X2: "platform trident forwarding-table partition flexible exact-match 16384 l2-shared 98304 l3-shared 131072"
```suggestion
        The Following default platform setting will be configured on 7050X3 and 7300X3: "platform trident forwarding-table partition flexible exact-match 16384 l2-shared 98304 l3-shared 131072"
```

2024-07-22 13:33 UTC, gmuloc approved these changes

2024-07-23 05:09 UTC, ClausHolbechArista approved these changes

2024-07-23 05:30 UTC, merged