Feat(eos_cli_config_gen): Add MPLS Tunnel Support for Traceroute and PMTU Discovery
aristanetworks/ansible-avd pull request #4219
Opened 2024-07-16 12:30 UTC by Shivani-gslab

## Change Summary

Add MPLS Tunnel Support for Traceroute and PMTU Discovery

## Related Issue(s)

Fixes #4185

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Implementing schema and template for - 
```
mpls icmp fragmentation-needed tunneling
mpls icmp ttl-exceeded tunneling 
```

## How to test
Test in EOS CLI and the molecule tests in this PR.

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-07-18 05:56 UTC, laxmikantchintakindi commented
LGTM

2024-07-18 15:20 UTC, gmuloc commented
@dgonzalez85 can you please confirm thats what is needed. Also I found indication that
Command `mpls icmp fragmentation-needed tunneling` is not implemented in all platforms. Can you please confirm as it probably should go in the description

2024-07-18 15:20 UTC, gmuloc requested changes

2024-07-18 15:20 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/mpls.cfg
> +   mpls icmp ttl-exceeded tunneling
wrong indentation
```suggestion
mpls icmp fragmentation-needed tunneling
mpls icmp ttl-exceeded tunneling
```

2024-07-18 15:20 UTC, gmuloc commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/mpls.j2
> +{%     endif %}
```suggestion
mpls icmp fragmentation-needed tunneling
{%     endif %}
{%     if mpls.icmp.ttl_exceeded_tunneling is arista.avd.defined(true) %}
mpls icmp ttl-exceeded tunneling
{%     endif %}
```

2024-07-18 15:32 UTC, dgonzalez85 commented
> m thats what is needed. Also I found indication th

Looks good! I will test. As we've discussed, MPLS support was mainly in Jericho-based platforms, but seems there are some basic in strata as well: https://www.arista.com/en/support/toi/eos-4-23-0f/14327-mpls-support-on-x-series-switches. So good to add a note to review platform support. thanks!

2024-07-19 12:05 UTC, gmuloc commented
> > m thats what is needed. Also I found indication th
> 
> Looks good! I will test. As we've discussed, MPLS support was mainly in Jericho-based platforms, but seems there are some basic in strata as well: https://www.arista.com/en/support/toi/eos-4-23-0f/14327-mpls-support-on-x-series-switches. So good to add a note to review platform support. thanks!

Thanks @dgonzalez85 - @Shivani-gslab after some thought we are not putting everywhere "this is platform dependent" (e.g. for the command only supported on CloudEOS) so I would leave it as it is.

2024-07-22 06:30 UTC, Shivani-gslab commented on python-avd/tox.ini
> +    coverage html --rcfile=pyproject.toml
```suggestion  
```

2024-07-22 10:46 UTC, ClausHolbechArista requested changes

2024-07-22 10:46 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/mpls-and-ldp.j2
> +| ICMP TTL-Exceeded Tunneling Enabled | {{ mpls.icmp.ttl_exceeded_tunneling | arista.avd.default('-') }} |
```suggestion
{%     if mpls.icmp.fragmentation_needed_tunneling is arista.avd.defined %}
| ICMP Fragmentation-Needed Tunneling Enabled | {{ mpls.icmp.fragmentation_needed_tunneling }} |
{%     endif %}
{%     if mpls.icmp.ttl_exceeded_tunneling is arista.avd.defined %}
| ICMP TTL-Exceeded Tunneling Enabled | {{ mpls.icmp.ttl_exceeded_tunneling }} |
{%     endif %}
```

2024-07-23 05:35 UTC, ClausHolbechArista approved these changes

2024-07-23 11:37 UTC, MaheshGSLAB approved these changes

2024-07-23 12:21 UTC, gmuloc approved these changes

2024-07-23 12:29 UTC, merged