Refactor(eos_cli_config_gen): Deprecate Upper case letter Vxlan1 to vxlan1 for vxlan_interface schema
aristanetworks/ansible-avd pull request #4250
Opened 2024-07-24 06:56 UTC by MaheshGSLAB

## Change Summary

Deprecate Upper case letter Vxlan1 to vxlan1 for vxlan_interface schema

## Related Issue(s)

Fixes #4244 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Deprecate Upper case letter Vxlan1 to vxlan1 for vxlan_interface schema

## How to test
Run molecule

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-07-24 07:55 UTC, ClausHolbechArista requested changes, later dismissed

2024-07-24 07:55 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/vxlan-interface.j2
> +{% set vxlan_config = vxlan_interface.vxlan1 if vxlan_interface.vxlan1 is arista.avd.defined else vxlan_interface.Vxlan1 %}
```suggestion
{% set vxlan_config = vxlan_interface.vxlan1 | arista.avd.default(vxlan_interface.Vxlan1) %}
```

2024-07-24 07:55 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/vxlan-interface.j2
> +{% set vxlan_config = vxlan_interface.vxlan1 if vxlan_interface.vxlan1 is arista.avd.defined else vxlan_interface.Vxlan1 %}
```suggestion
{% set vxlan_config = vxlan_interface.vxlan1 | arista.avd.default(vxlan_interface.Vxlan1) %}
```

2024-07-24 08:00 UTC, ClausHolbechArista commented
This deprecation will need to wait for 5.0.0 since it would trigger deprecation warnings for eos_designs run. In 5.0.0 we should change output of eos_designs to use this new key and deprecate the old for removal in 6.0.0. Too bad.

2024-08-08 12:35 UTC, ClausHolbechArista approved these changes

2024-08-08 13:39 UTC, Shivani-gslab approved these changes
LGTM!

2024-08-09 08:12 UTC, merged