Refactor(eos_cli_config_gen): Remove the deprecated keys for event-handlers
aristanetworks/ansible-avd pull request #4279
Opened 2024-07-29 09:18 UTC by Shivani-gslab

## Change Summary

Remove the deprecated keys for event-handlers.

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Remove the deprecated keys for event-handlers and remove the test from molecule scenario eos_cli_config_gen_deprecated_vars

## Checklist

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-07-29 11:23 UTC, MaheshGSLAB approved these changes

2024-07-29 11:43 UTC, laxmikantchintakindi approved these changes

2024-07-29 12:02 UTC, Vibhu-gslab approved these changes

2024-07-29 13:51 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_deprecated_vars/documentation/devices/host1.md
> -### Event Handler
Why are we loosing all test coverage?

2024-07-29 13:52 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_deprecated_vars/documentation/devices/host1.md
> -### Event Handler
nvm. this is deprecated vars

2024-07-29 13:55 UTC, ClausHolbechArista approved these changes

2024-07-29 14:02 UTC, ClausHolbechArista requested changes, later dismissed
Please update table in porting guide with the removed key and it's replacement (need to rebase first)

2024-07-30 09:55 UTC, ClausHolbechArista approved these changes

2024-07-30 09:56 UTC, merged