Refactor(eos_cli_config_gen): Mark deprecated key MIB_family_name as removed in snmp_server data model
aristanetworks/ansible-avd pull request #4289
Opened 2024-07-30 09:24 UTC by laxmikantchintakindi

## Change Summary

Mark deprecated key MIB_family_name as removed in snmp_server data model.

## Related Issue(s)

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Mark deprecated key MIB_family_name as removed in snmp_server data model. Remove the code for deprecated key from eos and documentation templates.

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-07-30 10:55 UTC, Vibhu-gslab submitted a review, later dismissed

2024-07-30 10:55 UTC, Vibhu-gslab commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +| snmp_server.local_interfaces[].MIB_family_name | snmp_server.local_interfaces[].mib_family_name |
```suggestion
| snmp_server.views.MIB_family_name | snmp_server.views.mib_family_name |
```

2024-07-30 12:37 UTC, ClausHolbechArista requested changes

2024-07-30 12:37 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_deprecated_vars/inventory/host_vars/host1/snmp-server.yml
> -      MIB_family_name: iso
you should only remove tline 27-31 from the test, since the parts above test other aspects

2024-07-30 12:37 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/snmp_server.schema.yml
>              MIB_family_name:
Please move the removed key to the bottom of the dict.

2024-07-31 04:51 UTC, laxmikantchintakindi commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_deprecated_vars/inventory/host_vars/host1/snmp-server.yml
> -      MIB_family_name: iso
snmp_server schema has only one key under deprecation. So removed the file from deprecation host.

2024-07-31 05:36 UTC, laxmikantchintakindi commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/snmp_server.schema.yml
>              MIB_family_name:
The deprecated key is at the bottom of key snmp_server.views. Do I need to move snmp_server.views to the bottom in snmp_server schema?

2024-07-31 09:13 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_deprecated_vars/inventory/host_vars/host1/snmp-server.yml
> -      MIB_family_name: iso
but if you keep other part and run the molecule it still generate the config and doc so this is something to dict of dict to dict of list which is not deprecated yet.
Can you please take a look again

2024-07-31 13:14 UTC, laxmikantchintakindi commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen_deprecated_vars/inventory/host_vars/host1/snmp-server.yml
> -      MIB_family_name: iso
Restored the input file and removed deprecated key.

2024-07-31 13:36 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/snmp_server.schema.yml
>              MIB_family_name:
no all good.

2024-07-31 13:36 UTC, ClausHolbechArista approved these changes

2024-07-31 15:10 UTC, gmuloc approved these changes

2024-07-31 15:11 UTC, merged