Cut((eos_cli_config_gen): Remove deprecated keys enable_vrfs and octa  from management_api_gnmi data model
aristanetworks/ansible-avd pull request #4296
Opened 2024-07-31 06:54 UTC by Vibhu-gslab

## Change Summary

Remove deprecated keys enable_vrfs and octa  from management_api_gnmi data model

## Related Issue(s)

Fixes #

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
added removed: true in schema and removed j2 code also made modifications to deprecated_vars molecule

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-07-31 09:27 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +| octa | provider |
```suggestion
| management_api_gnmi.enable_vrfs | management_api_gnmi.transport.grpc |
| management_api_gnmi.octa | management_api_gnmi.provider |
```

2024-07-31 13:48 UTC, laxmikantchintakindi commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/management-api-gnmi.j2
>  {# new table view using the new flags #}
```suggestion
```

2024-08-01 07:33 UTC, laxmikantchintakindi approved these changes

2024-08-01 07:40 UTC, laxmikantchintakindi commented
We can remove lines 124-139 from schema file and its documentation.

2024-08-01 07:46 UTC, laxmikantchintakindi commented
line 148 too.

2024-08-01 08:51 UTC, MaheshGSLAB requested changes, later dismissed
You should remove the below files
python-avd/pyavd/_eos_cli_config_gen/schema/eos_cli_config_gen.jsonschema.json
python-avd/pyavd/_eos_designs/schema/eos_designs.jsonschema.json

2024-08-02 14:40 UTC, gmuloc approved these changes
LGTM

2024-08-02 15:23 UTC, merged