Feat(plugins): Add strict mode and ignore_case flags to natural_sort filter
aristanetworks/ansible-avd pull request #4298
Opened 2024-07-31 09:44 UTC by gmuloc

## Change Summary

This PR adds two new flags to the `natural_sort` filter
1. a `strict` flag to be able to raise when the `sort_key` is missing in one item in the iterable dict or Namespace (default is `False` for backward compatibility). 
2. a `ignore_case` flag to be able to not ignore the case. Today natural_sort calls `lower` by default on some strings and this leads to AVD generating config not in the same order as EOS which does not use `lower`.

## Related Issue(s)

Fixes #4242

## Component(s) name

`plugins`

## Proposed changes

Adding two flags to the function, with backward compatible default values to avoid impacting the rest of AVD
The goal is then to review the config ordering we have today against EOS and to use the flags where appropriate.

## How to test

pytests have been added

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-07-31 11:42 UTC, ClausHolbechArista approved these changes

2024-07-31 11:42 UTC, ClausHolbechArista commented on python-avd/pyavd/j2filters/natural_sort.py
> +        strict (bool, optional): If strict is True, raise an error is the sort_key is missing.
I think strict should be default. Since we are introducing this in a major version, we can just document the change

2024-07-31 11:44 UTC, ClausHolbechArista requested changes
approved by mistake

2024-07-31 12:03 UTC, gmuloc commented on python-avd/pyavd/j2filters/natural_sort.py
> +        strict (bool, optional): If strict is True, raise an error is the sort_key is missing.
may need to change a couple of things around - let's see what breaks

2024-07-31 13:22 UTC, ClausHolbechArista commented
The special catch in the template of `hardware_counters` should be removed in 5.0.0. The negative test of that is causing the tests here to fail.

2024-08-02 13:55 UTC, ClausHolbechArista approved these changes

2024-08-02 14:29 UTC, carlbuchmann approved these changes
LGTM

2024-08-02 14:54 UTC, merged

2024-11-25 11:23 UTC, gellis713 commented
Sorry but I feel like there is a better way to name this. "ignore_case" flag would naturally imply that we're ignoring case, which would further imply the default behavior is being case-sensitive. The fact that "ignore_case" must be set so that we would NOT ignore_case is odd behavior in my opinion.