Test(eos_cli_config_gen): Added test in molecule for `monitor_connectivity` to improve the coverage
aristanetworks/ansible-avd pull request #4362
Opened 2024-08-14 11:13 UTC by MaheshGSLAB

## Change Summary

Added test in molecule for `monitor_connectivity` to improve the coverage

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Added test in molecule for `monitor_connectivity` to improve the coverage

## How to test
Run molecule

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-08-14 11:46 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +### `monitor_connectivity.address_only`, `monitor_connectivity.hosts[].address_only`, `monitor_connectivity.vrfs[].address_only` and `monitor_connectivity.vrfs[].hosts[].address_only` default options
```suggestion
### `address_only` options under `monitor_connectivity` no longer have a default value of `true`
```

2024-08-14 11:46 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +As of AVD 5.0.0 we have to define the `monitor_connectivity.address_only`, `monitor_connectivity.hosts[].address_only`, `monitor_connectivity.vrfs[].address_only` and `monitor_connectivity.vrfs[].hos
The suggestion tool is not able to provide the closing tripple backticks, so add that manually.

```suggestion
The default value `true` of data models `monitor_connectivity.hosts[].address_only`, `monitor_connectivity.vrfs[].address_only` and `monitor_connectivity.vrfs[].hosts[].address_only` has been removed, so it is now required to set `address_only: true` to render `address-only` in the EOS configuration.

```diff
 monitor_connectivity:
   hosts:
     - name: server1
       description: server1_connectivity_monitor
       ip: 10.10.10.1
       local_interfaces: HOST_SET
+      address_only: true
       url: https://server1.local.com
   vrfs:
     - name: red
+      address_only: true
       ...
     - name: blue
       ...
       hosts:
         - name: server4
           description: server4_connectivity_monitor
           ip: 10.10.20.1
+          address_only: true
           local_interfaces: VRF_HOST_SET
           url: https://server2.local.com
```

```

2024-08-14 11:46 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/monitor-connectivity.md
> +#### Vrf yellow Configuration
why is this added?

2024-08-14 11:46 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/monitor-connectivity.cfg
> +   host server4
not sure why this one is added?

2024-08-14 11:55 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/monitor-connectivity.md
> +#### Vrf yellow Configuration
Help to improve the coverage by not defining some params

2024-08-14 11:55 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/monitor-connectivity.cfg
> +   host server4
same as above to improve the coverage

2024-08-14 12:32 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +### `monitor_connectivity.address_only`, `monitor_connectivity.hosts[].address_only`, `monitor_connectivity.vrfs[].address_only` and `monitor_connectivity.vrfs[].hosts[].address_only` default options
updated

2024-08-14 12:32 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +As of AVD 5.0.0 we have to define the `monitor_connectivity.address_only`, `monitor_connectivity.hosts[].address_only`, `monitor_connectivity.vrfs[].address_only` and `monitor_connectivity.vrfs[].hos
updated with addition of `monitor_connectivity.address_only`

2024-08-16 08:48 UTC, ClausHolbechArista approved these changes

2024-08-16 09:01 UTC, laxmikantchintakindi approved these changes

2024-08-16 09:36 UTC, Shivani-gslab reviewed
.

2024-08-16 09:37 UTC, Shivani-gslab requested changes
Please remove `default: true` from schema also

2024-08-16 10:02 UTC, Shivani-gslab approved these changes
LGTM!

2024-08-16 10:48 UTC, MaheshGSLAB commented
Need to discuss with @gmuloc

2024-08-29 10:14 UTC, gmuloc approved these changes

2024-08-29 10:18 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/monitor-connectivity.yml
> +    - name: server4
Hmm probably best to not use the same name in a VRF and outside a VRF for our examples

2024-08-29 13:15 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/monitor-connectivity.yml
> +    - name: server4
it is supported in EOS cli

2024-08-29 16:04 UTC, merged