Feat(eos_validate_state): Add validation for BGP IPv4 peers in VRFs
aristanetworks/ansible-avd pull request #4538
Opened 2024-10-01 15:48 UTC by carl-baillargeon

## Change Summary

`AvdTestBGP` now checks for BGP IPv4 peers in all VRFs.

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_validate_state`

## Proposed changes

## How to test
- Add BGP peers in a VRF under network services
- Run eos_designs + eos_validate_state

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [X] My change requires a change to the documentation and documentation have been updated accordingly.
- [X] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-10-01 20:30 UTC, philippebureau approved these changes
LGTM
Tested with lab and customer repo

2024-10-02 08:01 UTC, ClausHolbechArista requested changes
This should be done as a separate test id, so we can disable it and have it mentioned in the porting guide how to disable it. It will add thousands of tests for scaled customers.

2024-11-11 08:09 UTC, ClausHolbechArista commented
Moving to draft until comment has been addressed.

2025-01-10 18:46 UTC, carl-baillargeon commented
Will be implemented in #4196

2025-01-10 18:46 UTC, closed without merging