Fix(eos_cli_config_gen): Fix the maximum-routes, next-hop resolution v4-mapped-v6 translation commands in `router_bgp.address_family_ipv4_labeled_unicast`
aristanetworks/ansible-avd pull request #4567
Opened 2024-10-09 07:28 UTC by MaheshGSLAB

## Change Summary

Fix the maximum-routes, next-hop resolution v4-mapped-v6 translation commands in `router_bgp.address_family_ipv4_labeled_unicast` and removed the j2 logic for redistribute rip from `router_bgp.address_family_ipv6`

## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Fix the maximum-routes, next-hop resolution v4-mapped-v6 translation commands in `router_bgp.address_family_ipv4_labeled_unicast` and removed the j2 logic for redistribute rip from `router_bgp.address_family_ipv6`

## How to test
Run molecule

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-10-09 12:50 UTC, Shivani-gslab approved these changes
LGTM

2024-10-10 07:17 UTC, Vibhu-gslab approved these changes
LGTM!

2024-10-10 08:29 UTC, ClausHolbechArista requested changes

2024-10-10 08:29 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/router_bgp.schema.yml
>                        type: bool
You can remove the `keys` here since the parent var is removed.

```suggestion
```

2024-10-10 08:29 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/router_bgp.schema.yml
>                        type: bool
```suggestion
```

2024-10-10 09:54 UTC, ClausHolbechArista approved these changes

2024-10-10 09:54 UTC, merged