Feat(eos_cli_config_gen): Add support for deadtime configuration to radius_server
aristanetworks/ansible-avd pull request #4614
Opened 2024-10-18 12:10 UTC by Shivani-gslab

## Change Summary

Add support for deadtime configuration to radius_server

## Related Issue(s)

Fixes #4268 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
```
radius_server:
      # Time to skip a nonresponsive server
      deadtime: <int; 1-1000>
```

## How to test
Molecule test or check the EOS CLI.

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-10-21 09:01 UTC, MaheshGSLAB approved these changes

2024-10-22 15:38 UTC, laxmikantchintakindi approved these changes

2024-10-23 06:10 UTC, ClausHolbechArista submitted a review, later dismissed
Blocking merge until 5.0.0 has been released.

2024-10-28 09:39 UTC, gmuloc requested changes

2024-10-28 09:39 UTC, gmuloc commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/radius_server.schema.yml
> +      deadtime:
move it before dynamic_authorization in the schema

2024-11-04 10:34 UTC, gmuloc approved these changes
LGTM - can merge once CI completes

2024-11-04 10:41 UTC, merged