Fix(eos_designs)!: Endpoints PoE and 802.1x configuration for port-channel members
aristanetworks/ansible-avd pull request #4627
Opened 2024-10-22 08:26 UTC by ClausHolbechArista

## Change Summary

Endpoints PoE and 802.1x configuration for port-channel members

## Related Issue(s)

Fixes #4600

## Component(s) name

`arista.avd.<role-name>`

## Proposed changes

### Connected endpoints and network ports now renders PoE and 802.1x configuration for port-channel members and ignores PoE and 802.1x from LACP fallback individual profile

With AVD version 5.0.0, port-channel members generated from connected endpoints or `network_ports` will now include 802.1x (`dot1x`) and PoE (`poe`) configuration.
Previously the member interface configuration only included `dot1x` or `poe` if it was defined under the port profile set in `lacp_fallback.individual.profile`.
The LACP fallback individual profiles now ignores any `dot1x` or `poe` settings.

It may be required to move the `dot1x` and `poe` settings from the fallback profile to the adapter profile:

```diff
 port_profiles:
   - name: MY_LACP_INDIVIDUAL_FALLBACK_PROFILE
     <...>
-    poe:
-      <...>
-    dot1x:
-      <...>
   - name: MY_SERVER_PROFILE
     <...>
+    poe:
+      <...>
+    dot1x:
+      <...>

servers:
  - name: MYSERVER1
    adapters:
      - <...>
        profile: MY_SERVER_PROFILE
        port_channel:
          <...>
          lacp_fallback:
            mode: individual
            individual:
              profile: MY_LACP_INDIVIDUAL_FALLBACK_PROFILE
```

No changes are needed if the LACP fallback individual profile is the same as the adapter profile

## How to test

Existing + new molecule coverage. Verified updated artifacts.

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-10-22 08:44 UTC, gmuloc approved these changes

2024-10-22 09:28 UTC, Shivani-gslab requested changes

2024-10-22 09:28 UTC, Shivani-gslab commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +Previously the member interface configuration only included `dot1x` or `poe` if it was defined under the port profile set in `lacp_fallback.individual.profile`.
```suggestion
Previously, the member interface configuration only included `dot1x` or `poe` if it was defined under the port profile set in `lacp_fallback.individual.profile`.
```

2024-10-22 09:28 UTC, Shivani-gslab commented on ansible_collections/arista/avd/docs/porting-guides/5.x.x.md
> +No changes are needed if the LACP fallback individual profile is the same as the adapter profile
```suggestion
No changes are needed if the LACP fallback individual profile is the same as the adapter profile.
```

2024-10-22 13:09 UTC, Shivani-gslab approved these changes

2024-10-23 01:33 UTC, carlbuchmann approved these changes
LGTM

2024-10-23 01:33 UTC, merged