Global ARP timer option
aristanetworks/ansible-avd pull request #479
Opened 2020-12-11 20:23 UTC by onurgashi

## Change Summary

Knob to change ARP timer globally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #477 

## Component(s) name
eos_cli_config_gen

## Proposed changes

Added knob
Added doc
Tested in DUT and molecule (wrong title for doc, fixed it in later commit.)

## How to test

Molecule

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly

2020-12-15 16:04 UTC, titom73 approved these changes
Looks good to me.

Just need to confirm with @aphillipps if the data model is OK

2020-12-15 18:02 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/arp.j2
> +{% endif %}
Missing newline?

2020-12-15 18:02 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/arp.j2
> +{% endif %}
Missing newline

2020-12-15 18:05 UTC, ClausHolbechArista requested changes
Missing newlines at the end of the new templates

2020-12-18 21:16 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/arp.j2
> +{% endif %}
Resolved, thank you!

2020-12-18 21:16 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/arp.j2
> +{% endif %}
Resolved, thank you!

2020-12-18 21:17 UTC, onurgashi commented
Resolved the discrepancies.

2020-12-19 15:43 UTC, ClausHolbechArista approved these changes
LGTM

2020-12-21 07:31 UTC, titom73 approved these changes
LGTM!

2020-12-21 07:31 UTC, merged