PTP capability
aristanetworks/ansible-avd pull request #481
Opened 2020-12-11 21:59 UTC by onurgashi

## Change Summary

Allows implementation of PTP in the eos_cli_config_gen

Next step add more knobs and maybe create data model for boradcast & media.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #440
 
## Component(s) name
eos_cli_config_gen

## Proposed changes

Interface level and global ptp.j2

## How to test

Successful venv and molecule tests.

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly

2020-12-14 07:40 UTC, ClausHolbechArista commented
Please rebase this PR since project branch was rebased before it merged into devel.

2020-12-14 11:11 UTC, ClausHolbechArista requested changes
Small formatting changes required for readability, but functionality looks good.
Would be good to add more ptp interface knobs at some point (could just submit issue)

2020-12-14 11:11 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ptp.j2
> +ptp clock-identity {{ ptp.clock_identity }}
Indention is only 2 here. Should be 4.

2020-12-14 11:11 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ptp.j2
> +{%   if ptp.clock_identity is defined and ptp.clock_identity is not none %}
indention only 2. Should be 4.

2020-12-14 11:11 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ptp.j2
> +{%             endif %}
indented more than matching `if`

2020-12-14 11:11 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ptp.j2
> +{%             endif %}
indented more than matching `if`

2020-12-18 21:34 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ptp.j2
> +ptp clock-identity {{ ptp.clock_identity }}
Fixed, thanks man!

2020-12-18 21:34 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ptp.j2
> +{%   if ptp.clock_identity is defined and ptp.clock_identity is not none %}
Fixed, thanks man!

2020-12-18 21:34 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/ptp.j2
> +{%             endif %}
Fixed, thanks man!

2020-12-18 21:34 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ptp.j2
> +{%             endif %}
Fixed, thanks man!

2020-12-18 21:35 UTC, onurgashi commented
Fixed em.

2020-12-19 15:41 UTC, ClausHolbechArista approved these changes
LGTM

2020-12-22 19:00 UTC, carlbuchmann approved these changes
LGTM - tested with avd-validation lab.

2020-12-22 19:00 UTC, merged

2020-12-24 00:08 UTC, sundayN commented
This is great news. Looks like Christmas has come early!
Now we just need to add some more options to `ethernet_interfaces`
```
ptp:
  announce:
    interval: < integer>
  sync-message:
    interval: <-integer>
  delay-req: <-integer>
  role: < master | slave >
```