Feat(eos designs): Only enable PTP on certain uplinks
aristanetworks/ansible-avd pull request #4819
Opened 2024-12-17 07:43 UTC by laxmikantchintakindi

## Change Summary

Only enable PTP on certain uplinks.

```
  node_groups:
    - group: leaf1
      nodes:
        - name: leaf1a
          ptp:
            enabled: true
	    uplinks: [...] # restrict ptp config on these uplinks only
```
## Related Issue(s)

Fixes #<ISSUE ID>

## Component(s) name

`arista.avd.<role-name>`

## Proposed changes
Provide a mechanism to control which uplinks are enabled for PTP.
Could be either a list of uplink interfaces or maybe an algorithm like modulus on the node ID.

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2025-01-07 12:20 UTC, Vibhu-gslab commented on python-avd/pyavd/_eos_designs/eos_designs_facts/uplinks.py
> +        elif self.shared_utils.ptp_enabled and (not (ptp_uplinks := self.shared_utils.ptp_uplinks) or (ptp_uplinks and (uplink_interface in ptp_uplinks))):
```suggestion
        elif self.shared_utils.ptp_enabled and (not (ptp_uplinks := self.shared_utils.ptp_uplinks) or (uplink_interface in ptp_uplinks)):
```

2025-01-07 12:26 UTC, Vibhu-gslab commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_UPLINKS.yml
> +        enabled: true
Can we add a testcase where "ptp: enabled" is not defined but `uplinks`is defined.

2025-01-07 12:31 UTC, Vibhu-gslab reviewed
request changes

2025-01-08 06:34 UTC, laxmikantchintakindi commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_UPLINKS.yml
> +        enabled: true
`ptp_settings` in PTP_TESTS.yml group vars is set to true. So even `ptp:enabled` is not set, there will be no change in configs.

2025-01-09 08:03 UTC, Vibhu-gslab commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_UPLINKS.yml
> +        enabled: true
I understand, but having a testcase for it would make it more clear. 
You can mention in comment above testcase that what it is for.

2025-01-10 07:07 UTC, MaheshGSLAB commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_UPLINKS.yml
> +        enabled: true
Can you add more tests like uplinks under defaults and node group

2025-01-10 10:16 UTC, laxmikantchintakindi commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_UPLINKS.yml
> +        enabled: true
Addressed both comments.

2025-01-13 12:21 UTC, Vibhu-gslab commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_L2LEAFS.yml
> +      ptp:
Please write a comment to describe what this testcase is for.

2025-01-13 14:24 UTC, laxmikantchintakindi commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_L2LEAFS.yml
> +      ptp:
Done.

2025-01-15 15:34 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/shared_utils/ptp.py
> +
I don't think we need this extra property. Just refer to `self.node_config.ptp.uplinks` directly where you need it. Thanks

2025-01-15 15:34 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/defs_node_type.schema.yml
> +                  description: Limit PTP to the specified uplink interfaces.
```suggestion
                  description: |-
                    Limit PTP to the specified uplink interfaces.
                    Only considered when `uplink_type` is `p2p`.
```

2025-01-15 15:42 UTC, laxmikantchintakindi commented on python-avd/pyavd/_eos_designs/shared_utils/ptp.py
> +
When `self.node_config.ptp.uplinks` referred in eos_designs_facts >uplinks.py. It is throwing below error.
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'EosDesignsFacts' object has no attribute 'node_config'
fatal: [relaxed-structured-config-validation -> 127.0.0.1]: FAILED! => {"msg": "Unexpected failure during module execution: 'EosDesignsFacts' object has no attribute 'node_config'", "stdout": ""}
```

2025-01-15 15:46 UTC, laxmikantchintakindi commented on python-avd/pyavd/_eos_designs/schema/schema_fragments/defs_node_type.schema.yml
> +                  description: Limit PTP to the specified uplink interfaces.
Done.

2025-01-16 09:07 UTC, emilarista approved these changes
Tested, looks good from my perspective!

2025-01-17 07:37 UTC, Vibhu-gslab commented on python-avd/pyavd/_eos_designs/shared_utils/ptp.py
> +
We can use self.shared_utils.node_config.ptp.uplinks

2025-01-17 08:42 UTC, Vibhu-gslab approved these changes
LGTM!

2025-01-17 08:43 UTC, laxmikantchintakindi commented on python-avd/pyavd/_eos_designs/shared_utils/ptp.py
> +
done.

2025-01-20 05:39 UTC, MaheshGSLAB approved these changes

2025-01-20 08:49 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_L2LEAFS.yml
> +        uplinks: [ Ethernet1 ]
Testing this on an l2leaf will not test the feature at all, since we don't enforce it on l2 uplinks.

2025-01-20 08:51 UTC, ClausHolbechArista requested changes
.

2025-01-20 08:56 UTC, laxmikantchintakindi commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_L2LEAFS.yml
> +        uplinks: [ Ethernet1 ]
Removed the input.

2025-01-20 09:21 UTC, gmuloc commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_L2LEAFS.yml
> +        uplinks: [ Ethernet1 ]
should be done on l3leaf

2025-01-20 09:40 UTC, laxmikantchintakindi commented on ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/group_vars/PTP_TESTS_L2LEAFS.yml
> +        uplinks: [ Ethernet1 ]
Done.

2025-01-29 10:05 UTC, ClausHolbechArista approved these changes

2025-01-29 12:41 UTC, merged