Feat(eos_cli_config_gen): Additional interface TE options
aristanetworks/ansible-avd pull request #4823
Opened 2024-12-17 14:49 UTC by emilarista

## Change Summary

Implements additional interface TE options.

## Related Issue(s)

Fixes part of #https://github.com/aristanetworks/avd-internal/issues/149

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

```yaml
interfaces:
  - name: ...
    traffic_engineering:
      srlg: < int >
      metric: < int >
      bandwidth:
        number: < int >
        unit: < str >
      min_delay_static:
        number: < int >
        unit: < str >
```

## How to test

Tested with molecule and on device.

## Checklist

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [x] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2025-01-06 07:12 UTC, ClausHolbechArista requested changes

2025-01-06 07:12 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/host1.cfg
> +   traffic-engineering min-delay static 2 milliseconds
This interface has no `traffic-engineering` command. Is that possible/valid? Is there a difference in EOS behavior having or not having that command? (If it is possible to not have it, I would expect it to be the "enabler" for the whole feature, and if so, we should keep the enabled flag in the doc table and set it properly depending on this.
We should also add a TODO for AVD 6.0.0 to set the `enabled` key as required in the schema.

2025-01-06 07:12 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/ethernet_interfaces.schema.yml
> +                  valid_values:
```suggestion
                unit:
                  type: str
                  required: true
                  valid_values:
```

2025-01-06 07:12 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/ethernet_interfaces.schema.yml
> +                  convert_types:
```suggestion
                  type: int
                  required: true
                  convert_types:
```

2025-01-06 07:12 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/ethernet_interfaces.schema.yml
> +                  convert_types:
```suggestion
                  type: int
                  required: true
                  convert_types:
```

2025-01-06 07:12 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/ethernet_interfaces.schema.yml
> +                  valid_values:
```suggestion
                  type: str
                  required: true
                  valid_values:
```

2025-01-06 07:12 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/port_channel_interfaces.schema.yml
> +                  convert_types:
```suggestion
                  type: int
                  required: true
                  convert_types:
```

2025-01-06 07:12 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/port_channel_interfaces.schema.yml
> +                  valid_values:
```suggestion
                  type: str
                  required: true
                  valid_values:
```

2025-01-06 07:12 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/port_channel_interfaces.schema.yml
> +                  convert_types:
```suggestion
                  type: int
                  required: true
                  convert_types:
```

2025-01-06 07:12 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/port_channel_interfaces.schema.yml
> +                  valid_values:
```suggestion
                  type: str
                  required: true
                  valid_values:
```

2025-01-14 06:55 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/host1.cfg
> +   traffic-engineering min-delay static 2 milliseconds
EOS accepts this, so we will keep the data model as is. The doc could still contain the enabled.

2025-01-14 07:02 UTC, ClausHolbechArista requested changes

2025-01-14 07:02 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/host1.md
> +| Ethernet81/3 | 3,15-29,testgrp | 4 | 10 percent | 5 microseconds | TEST-SRLG |
```suggestion
| Interface | Enabled | Administrative Groups | Metric | Max Reservable Bandwidth | Min-delay | SRLG |
| --------- | ------- | --------------------- | ------ | ------------------------ | --------- | ---- |
| Ethernet81/3 | True | 3,15-29,testgrp | 4 | 10 percent | 5 microseconds | TEST-SRLG |
```

2025-01-14 07:02 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/host1.md
> +| Port-Channel136 | 7 | - | - | - | - |
```suggestion
| Interface | Enabled | Administrative Groups | Metric | Max Reservable Bandwidth | Min-delay | SRLG |
| --------- | ------- | --------------------- | ------ | ------------------------ | --------- | ---- |
| Port-Channel136 | - | 7 | - | - | - | - |
```

2025-01-14 07:02 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/ethernet-interfaces.j2
> +| --------- | --------------------- | ------ | ------------------------ | --------- | ---- |
```suggestion
| Interface | Enabled | Administrative Groups | Metric | Max Reservable Bandwidth | Min-delay | SRLG |
| --------- | ------- | --------------------- | ------ | ------------------------ | --------- | ---- |
```

2025-01-14 07:02 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/ethernet-interfaces.j2
> +{%             set te_srlg = te_interface.traffic_engineering.srlg | arista.avd.default("-") %}
```suggestion
{%             set te_enabled = te_interface.enabled | arista.avd.default("-") %}
{%             set te_srlg = te_interface.traffic_engineering.srlg | arista.avd.default("-") %}
```

2025-01-14 07:02 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/ethernet-interfaces.j2
> +| {{ te_interface.name }} | {{ admin_groups }} | {{ te_metric }} | {{ te_bandwidth }} | {{ te_min_del }} | {{ te_srlg }} |
```suggestion
| {{ te_interface.name }} | {{ te_enabled }} | {{ admin_groups }} | {{ te_metric }} | {{ te_bandwidth }} | {{ te_min_del }} | {{ te_srlg }} |
```

2025-01-14 07:02 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/port-channel-interfaces.j2
> +| --------- | --------------------- | ------ | ------------------------ | --------- | ---- |
```suggestion
| Interface | Enabled | Administrative Groups | Metric | Max Reservable Bandwidth | Min-delay | SRLG |
| --------- | ------- | --------------------- | ------ | ------------------------ | --------- | ---- |
```

2025-01-14 07:02 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/port-channel-interfaces.j2
> +| {{ po_te_interface.name }} | {{ admin_groups }} | {{ te_metric }} | {{ te_bandwidth }} | {{ te_min_del }} | {{ te_srlg }} |
```suggestion
| {{ po_te_interface.name }} | {{ enabled }} | {{ admin_groups }} | {{ te_metric }} | {{ te_bandwidth }} | {{ te_min_del }} | {{ te_srlg }} |
```

2025-01-14 07:02 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/port-channel-interfaces.j2
> +{%             set te_srlg = po_te_interface.traffic_engineering.srlg | arista.avd.default("-") %}
```suggestion
{%             set te_enabled = po_te_interface.enabled | arista.avd.default("-") %}
{%             set te_srlg = po_te_interface.traffic_engineering.srlg | arista.avd.default("-") %}
```

2025-01-14 07:04 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/host1.md
> +| Port-Channel136 | - | 7 | - | - | - | - |
```suggestion
| Port-Channel136 | True | 7 | - | - | - | - |
```

2025-01-14 07:18 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/port-channel-interfaces.j2
> +| {{ po_te_interface.name }} | {{ enabled }} | {{ admin_groups }} | {{ te_metric }} | {{ te_bandwidth }} | {{ te_min_del }} | {{ te_srlg }} |
```suggestion
| {{ po_te_interface.name }} | {{ te_enabled }} | {{ admin_groups }} | {{ te_metric }} | {{ te_bandwidth }} | {{ te_min_del }} | {{ te_srlg }} |
```

2025-01-14 08:14 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/ethernet-interfaces.j2
> +{%             set te_enabled = te_interface.enabled | arista.avd.default("-") %}
```suggestion
{%             set te_enabled = te_interface.traffic_engineering.enabled | arista.avd.default("-") %}
```

2025-01-14 08:14 UTC, ClausHolbechArista commented on python-avd/pyavd/_eos_cli_config_gen/j2templates/documentation/port-channel-interfaces.j2
> +{%             set te_enabled = po_te_interface.enabled | arista.avd.default("-") %}
```suggestion
{%             set te_enabled = po_te_interface.traffic_engineering.enabled | arista.avd.default("-") %}
```

2025-01-14 09:18 UTC, ClausHolbechArista approved these changes

2025-01-14 13:56 UTC, gmuloc requested changes

2025-01-14 13:56 UTC, gmuloc commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/ethernet_interfaces.schema.yml
> +              description: SRLG name or number
```suggestion
              description: SRLG name or number.
```

2025-01-14 13:56 UTC, gmuloc commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/ethernet_interfaces.schema.yml
> +              description: Interface maximum reservable bandwidth
```suggestion
              description: Interface maximum reservable bandwidth.
```

2025-01-14 13:56 UTC, gmuloc commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/port_channel_interfaces.schema.yml
> +              description: SRLG name or number
```suggestion
              description: SRLG name or number.
```

2025-01-14 13:56 UTC, gmuloc commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/port_channel_interfaces.schema.yml
> +              description: Interface maximum reservable bandwidth
```suggestion
              description: Interface maximum reservable bandwidth.
```

2025-01-14 13:56 UTC, gmuloc approved these changes
LGTM once CI reruns after pre-commit does its work

2025-01-14 14:27 UTC, merged