Feat(eos_designs): Added rack, pod, dc, fabric information in the structured_config metadata
aristanetworks/ansible-avd pull request #4827
Opened 2024-12-18 05:49 UTC by MaheshGSLAB

## Change Summary

Added rack, pod, dc, fabric information in the structured_config metadata.

## Related Issue(s)

Fixes #4805 

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes
Added rack, pod, dc, fabric information in the structured_config metadata.

## How to test
Run molecule

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-12-31 12:13 UTC, carl-baillargeon approved these changes
LGTM. Thanks Mahesh

2025-01-03 15:01 UTC, gmuloc requested changes

2025-01-03 15:01 UTC, gmuloc commented on python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/metadata.schema.yml
> +        type: str
lets move these above cv_tags so that it is easier to find in the doc

2025-01-03 16:22 UTC, gmuloc approved these changes
LGTM once CI passes

2025-01-03 17:03 UTC, merged