Refactor(eos_cli_config_gen): Add `default: default` for `ip_name_servers[].vrf`
aristanetworks/ansible-avd pull request #4842
Opened 2024-12-23 10:27 UTC by laxmikantchintakindi

## Change Summary

Add `default: default` for `ip_name_servers[].vrf`

## Related Issue(s)

Fixes #4788 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes
Add `default: default` for `ip_name_servers[].vrf`

## How to test

## Checklist

### User Checklist

- N/A

### Repository Checklist

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contribution/overview.html) document.
- [ ] My change requires a change to the documentation and documentation have been updated accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly. (check the box if not applicable)

2024-12-31 12:37 UTC, Shivani-gslab submitted a review, later dismissed
In doc template also the default value for vrf should be "default"

```
{%     for name_server in ip_name_servers | arista.avd.default([]) %}
| {{ name_server.ip_address }} | {{ name_server.vrf | arista.avd.default(**'default')** }} | {{ name_server.priority | arista.avd.default('-') }} |
{%     endfor %}
```

2025-01-02 11:06 UTC, laxmikantchintakindi commented
> In doc template also the default value for vrf should be "default"
> 
> {% for name_server in ip_name_servers | arista.avd.default([]) %} | {{ name_server.ip_address }} | {{ name_server.vrf | arista.avd.default(**'default'**) }} | {{ name_server.priority | arista.avd.default('-') }} | {% endfor %}

Done.

2025-01-03 14:20 UTC, Shivani-gslab approved these changes
LGTM!

2025-01-06 06:17 UTC, ClausHolbechArista requested changes
This is a breaking change since you are changing the generated configuration. I don't think we really need this change. If people want the default VRF to show up in the generated config, they can just give it on input.

2025-01-06 06:32 UTC, laxmikantchintakindi commented
> This is a breaking change since you are changing the generated configuration. I don't think we really need this change. If people want the default VRF to show up in the generated config, they can just give it on input.

Okay. Shall I use just variable `default` to sort the commands as per EOS and not generate the `default` word in the output?

2025-01-07 03:16 UTC, closed without merging

2025-01-07 03:17 UTC, laxmikantchintakindi commented
Closing the PR as adding default vrf is not necessary. The vrf key will be required starting from AVD 6.0.0.