QOS support
aristanetworks/ansible-avd pull request #521
Opened 2020-12-20 17:57 UTC by onurgashi

## Change Summary

This is a draft for QOS. Covers QOS profile, QOS mappings, and QOS rewrite.

Would be great to have some feedback on data model. I.e QOS profile and QOS mappings are not in the same location in cfg file.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #439 

## Component(s) name
eos_cli_config_gen
molecule

## Proposed changes

## How to test

Molecule and HW

## Checklist:

- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly

2020-12-21 09:26 UTC, onurgashi commented
Added interface level support. There is a small thing we need to look into with the location of qos profile and qos the rest of the global knobs. Might be we need to refactor into two templates so we can facilitate the change of location in the running-config.

2020-12-23 01:36 UTC, carlbuchmann commented
- [ ] update eos_cli_config_gen documentation

2020-12-31 13:09 UTC, titom73 requested changes, later dismissed
Seems there is no documentation generated for QOS settings. We should provide at least a basic doc generated for a QOS summary

2021-01-04 19:21 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +    qos_trust: < dscp defualt(L3) | cos default(L2) >
typo, def**au**lt(L3)

2021-01-04 19:21 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +    qos_trust: < dscp defualt(L3) | cos default(L2) >
typo, def**au**lt(L3)

2021-01-04 19:21 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +    qos_trust: < dscp defualt(L3) | cos default(L2) >
These defaults are not AVD defaults are they? We do not need to describe EOS defaults here.

2021-01-05 16:21 UTC, onurgashi commented
I have updated the QOS as:
- Reflect the comments
- Separate profiles with general QOS
- Interface level updated for port-channels and ethernet interfaces from qos_feature to qos.feature
- Documentation has been added for global QOS and QOS profiles
- Molecule tests successful

2021-01-05 17:13 UTC, ClausHolbechArista reviewed
Small change required re empty lines. I will try to fix.

2021-01-05 17:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/errdisable.cfg
> +
These extra empty lines should be removed

2021-01-05 17:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/intended/configs/errdisable.cfg
> +
These extra empty lines should be removed

2021-01-05 17:13 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos-intended-config.j2
> +{# management qos #}
Not management. Just qos

2021-01-05 18:33 UTC, ClausHolbechArista approved these changes
LGTM

2021-01-05 18:39 UTC, merged