Add options to configure SSH ciphers and algorithms for the eos_cli_config_gen role
aristanetworks/ansible-avd pull request #656
Opened 2021-01-26 14:39 UTC by dominikrappaport

## Change Summary

Added options to configure ciphers and algorithms for SSH

Add option to configure
  - ciphers
  - key-exchange methods
  - MAC algorithms
  - Hostkey server algorithms

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

## Component(s) name

`arista.avd.eos_cli_config_gen role`

## Proposed changes

Added new parameters for `management ssh` so users can configure ciphers and other algorithms.

## How to test

Tested options (partial and full) and generated configlets.

## Checklist:

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-01-26 17:01 UTC, onurgashi requested changes
I added some comments, if you could fix them it would be awesome! 👍

2021-01-26 17:01 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/management-ssh.j2
> +{%     if management_ssh.hostkey.server is arista.avd.defined %}
This needs 4 spaces indentation, as it's a nested if.

2021-01-26 17:01 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/management-ssh.j2
> +{%     endif %}
This needs 4 spaces indentation, as it's a nested if.

2021-01-26 17:01 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +    - cipher1
< cipher1 > instead of cipher1 and so on

2021-01-26 17:01 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +    - method1
< method1 > and so on

2021-01-26 17:01 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +    - mac_algorithm1
< mac_algorithm1 > and so on :D

2021-01-26 17:01 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +      - algorithm1
< algorithm1 >

2021-01-26 17:01 UTC, onurgashi commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/management-ssh.j2
> +   cipher {{ management_ssh.cipher|join(" ") }}
cipher | join(" "), spacing for all filters please.

2021-01-26 17:26 UTC, dominikrappaport commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/management-ssh.j2
> +{%     if management_ssh.hostkey.server is arista.avd.defined %}
Sure thing!

2021-01-27 10:17 UTC, onurgashi approved these changes
Thank you @dominikrappaport LGTM!

2021-01-29 09:10 UTC, onurgashi approved these changes

2021-01-29 11:56 UTC, titom73 approved these changes
LGTM!

2021-01-29 11:56 UTC, merged