Fixed extra newline in documentation added in PR#641
aristanetworks/ansible-avd pull request #659
Opened 2021-01-26 22:07 UTC by emilotep

## Change Summary
Removed extra newline inadvertently added while rendering BGP neighbor documentation. Bug introduced in PR#641.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)
None.

## Component(s) name

`arista.avd.eos_cli_config_gen

## Proposed changes
Removed newline at line 95 in router-bgp.j2 documentation template.

## How to test
Ran molecule to ensure extra linebreak is gone.

## Checklist:
- [ ] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-01-27 18:00 UTC, ClausHolbechArista requested changes
Please refactor the condition for the case where you only have vrf neighbors.

2021-01-27 18:00 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/router-bgp.j2
> +{%             if router_bgp.neighbors is not arista.avd.defined %}
It would be more elegant to add a check for vrf neighbors in the section above in line 66, to avoid repeating headers like this. This is very confusing to read.
So just do a for loop for bgp_neighbors and another for loop for the vrf neighbors.

2021-01-29 08:59 UTC, emilotep commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/router-bgp.j2
> +{%             if router_bgp.neighbors is not arista.avd.defined %}
Fixed in commit 00c400b.

2021-01-29 21:57 UTC, ClausHolbechArista approved these changes
LGTM!

I have updated all molecule CI artifacts and fixed some rebase issue, so it is ready to merge.

2021-01-29 22:01 UTC, merged