Management security for TLS and certs added
aristanetworks/ansible-avd pull request #677
Opened 2021-02-02 18:30 UTC by xaviramon

## Change Summary
-Management security update to include tls version and certificates under a SSL Profile
-Management API HTTPS update to include SSL Profile
-Code modification for proper order in configuration and use of arista.avd.defined

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes issue #662 

## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

## How to test

## Checklist:

- [ ] My code has been rebased from devel before I start
- [ ] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-02-08 08:42 UTC, titom73 requested changes

2021-02-08 08:42 UTC, titom73 commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/management-api-http.j2
> +{%  if management_api_http.enable_https is arista.avd.defined and management_api_http.enable_https == true and management_api_http.https_ssl_profile is arista.avd.defined %}
This block `management_api_http.enable_https is arista.avd.defined and management_api_http.enable_https == true` can be reduced to `management_api_http.enable_https is arista.avd.defined(true)`

2021-02-10 15:24 UTC, titom73 commented
CI MKDOCS issue is related to a link change and will be fixed in #698

2021-02-10 15:27 UTC, titom73 approved these changes
LGTM!

2021-03-08 18:33 UTC, ClausHolbechArista commented
we should add
```yaml
protocol_https_certificate:
  certificate: < full certificate as multi-line PEM string >
  private_key: < full private key as multi-line PEM string >
```

Should be rendered as:
```eos
management api https-commands
   protocol https certificate
   {{ protocol_https_certificate.certificate }}
   EOF
   {{ protocol_https_certificate.private_key }}
   EOF
```

2021-03-09 03:46 UTC, carlbuchmann commented
replaced by PR #780

2021-03-09 03:46 UTC, closed without merging