Adding Fabric MTU test for 9214 bytes
aristanetworks/ansible-avd pull request #762
Opened 2021-03-03 00:39 UTC by xaviramon

## Change Summary
Adding 2 new tests on ansible to generate a ping with df-bit for 9214 bytes. CSV results file is updated with MTU tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes issue #676 

## Component(s) name

`arista.avd.validation`

## Proposed changes

## How to test

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-03-09 11:47 UTC, ClausHolbechArista approved these changes
LGTM

2021-03-10 01:08 UTC, carlbuchmann requested changes
I would recommend updating to do the MTU test with physical interfaces,
add MTU to `ip_reachability.yml` since the proposed implementation would only work if leveraging the eos_design role.

2021-03-10 01:08 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_validate_state/tasks/loopback0_reachability.yml
> +- name: Validate MTU is {{ p2p_uplinks_mtu }} bytes between devices (loopback0 <-> loopback0)
Tests should all be build leveraging structure configuration data only i.e. not using `{{ p2p_uplinks_mtu }}
`, so they work across various use cases, including deployments not leveraging the eos_design role.

I would suggest doing this test on the physical P2P interfaces and leveraging the `ethernet_interfaces[interface].mtu`  value.

2021-06-30 13:11 UTC, carlbuchmann commented
Closing PR as this has been stale for several months!

2021-06-30 13:11 UTC, closed without merging