feat(eos_designs): Add routed interfaces to VRF
aristanetworks/ansible-avd pull request #854
Opened 2021-03-30 20:29 UTC by mpergament

## Change Summary

Add routed interfaces to VRF

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #836 

## Component(s) name

`arista.avd.eos_designs`

## Proposed changes
```
    Tenant_A_WAN_Zone:
        vrf_vni: 14
        l3_interfaces:
          - interfaces: [ Ethernet7, Ethernet7 ]
            ip_addresses: [10.10.10.10/24, 10.10.20.20/24]
            nodes: [DC1-BL1A, DC1-BL1B]
            mtu: 9000
            description: "test"
```
## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-03-31 10:54 UTC, ClausHolbechArista reviewed
One comment so far. I will review more thoroughly tonight.

2021-03-31 10:54 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/evpn_underlay_ebgp_overlay_ebgp/documentation/devices/DC1-BL1A.md
> +!
Missing no shutdown in generated config. I think you need to add `enabled: true`

2021-03-31 11:12 UTC, emilotep commented on ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/tenant_evpn_vxlan/l3leaf-logic.j2
> +{%                         do entry.update( {'ip_address':entry.ip_addresses[node_index]})%}
Really minor but some inconsistent spacing after closing "}" and between closing ")" and "%}".

2021-03-31 11:46 UTC, emilotep commented on ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/tenant_evpn_vxlan/l3leaf-logic.j2
> +{%                         do entry.update( {'ip_address':entry.ip_addresses[node_index]})%}
Approved.

2021-03-31 12:00 UTC, ankudinov approved these changes
LGTM

2021-03-31 12:40 UTC, daanvdsanden commented
Does not seem to work is there are only l3 interfaces in the VRF on a switch. Either always_include_vrfs_in_tenants has to be defined for that switch or an SVI also needs to be present in the VRF else the vrf will not be in leaf.vrfs:
https://github.com/aristanetworks/ansible-avd/blob/7ce00e648d3ee8b7dc28839650874d5927710b82/ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/tenant_evpn_vxlan/l3leaf-logic.j2#L66

If below code block is moved to line 30 and a line is added to add the vrf to the leaf.vrfs array, it behaves more like an svi (and always_include_vrfs_in_tenants doesn't need to be set)
https://github.com/aristanetworks/ansible-avd/blob/7ce00e648d3ee8b7dc28839650874d5927710b82/ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/tenant_evpn_vxlan/l3leaf-logic.j2#L67-L77

2021-03-31 13:32 UTC, mpergament commented
> Does not seem to work is there are only l3 interfaces in the VRF on a switch. Either always_include_vrfs_in_tenants has to be defined for that switch or an SVI also needs to be present in the VRF else the vrf will not be in leaf.vrfs:
> https://github.com/aristanetworks/ansible-avd/blob/7ce00e648d3ee8b7dc28839650874d5927710b82/ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/tenant_evpn_vxlan/l3leaf-logic.j2#L66
> 
> If below code block is moved to line 18 and a line is added to add the vrf to the leaf.vrfs array, it behaves more like an svi (and always_include_vrfs_in_tenants doesn't need to be set)
> https://github.com/aristanetworks/ansible-avd/blob/7ce00e648d3ee8b7dc28839650874d5927710b82/ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/tenant_evpn_vxlan/l3leaf-logic.j2#L67-L77

Good catch!!! Thanks a lot for your review!

2021-03-31 14:05 UTC, daanvdsanden commented
When the node names are not unique, only the first interface on that node is used. Not sure if you want to support below configuration (might mention it in the documentation). 

e.g. the following will only configure interface Ethernet7 and not Ethernet8
```
    Tenant_A_WAN_Zone:
        vrf_vni: 14
        l3_interfaces:
          - interfaces: [ Ethernet7, Ethernet8 ]
            ip_addresses: [10.10.10.10/24, 10.10.20.20/24]
            nodes: [DC1-BL1A, DC1-BL1A]
            mtu: 9000
            description: "test"
```

2021-03-31 14:15 UTC, mpergament commented
> When the node names are not unique, only the first interface on that node is used. Not sure if you want to support below configuration (might mention it in the documentation).
> 
> e.g. the following will only configure interface Ethernet7 and not Ethernet8
> 
> ```
>     Tenant_A_WAN_Zone:
>         vrf_vni: 14
>         l3_interfaces:
>           - interfaces: [ Ethernet7, Ethernet8 ]
>             ip_addresses: [10.10.10.10/24, 10.10.20.20/24]
>             nodes: [DC1-BL1A, DC1-BL1A]
>             mtu: 9000
>             description: "test"
> ```

Let me add note to the documentation

2021-03-31 15:05 UTC, carlbuchmann commented
> > When the node names are not unique, only the first interface on that node is used. Not sure if you want to support below configuration (might mention it in the documentation).
> > e.g. the following will only configure interface Ethernet7 and not Ethernet8
> > ```
> >     Tenant_A_WAN_Zone:
> >         vrf_vni: 14
> >         l3_interfaces:
> >           - interfaces: [ Ethernet7, Ethernet8 ]
> >             ip_addresses: [10.10.10.10/24, 10.10.20.20/24]
> >             nodes: [DC1-BL1A, DC1-BL1A]
> >             mtu: 9000
> >             description: "test"
> > ```
> 
> Let me add note to the documentation

2021-03-31 15:09 UTC, carlbuchmann requested changes, later dismissed
See comment in the "Conversation" board!

2021-03-31 17:00 UTC, mpergament commented
> See comment in the "Conversation" board!

Done

2021-03-31 17:29 UTC, titom73 approved these changes
LGTM!

2021-03-31 18:29 UTC, ClausHolbechArista requested changes
A few changes requested.

2021-03-31 18:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/evpn_underlay_ebgp_overlay_ebgp/documentation/fabric/DC1_FABRIC-topology.csv
> +l3leaf,DC1-BL1A,Ethernet7,,,
These CSVs reflect the topology. We should at least add some static "peer_type" key on the generated structured config. Ex. "l3_interface"

2021-03-31 18:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/evpn_underlay_ebgp_overlay_ebgp/inventory/group_vars/DC1_TENANTS_NETWORKS.yml
> +        l3_interfaces:
to cover more scenarios, could we change this section to be one list item per interface, so we also test the outer loop over l3_interfaces ?

2021-03-31 18:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/tenant_evpn_vxlan/l3leaf-logic.j2
> +{%                                 do entry_node.update( {'l3_interface':entry.interfaces[loop.index - 1]} ) %}
use loop.index0 to simplify.

2021-03-31 18:29 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/tenant_evpn_vxlan/leaf-tenant-vrf-interfaces.j2
> +{%         if interface.enabled is arista.avd.defined(true) %}
I suppose the default should be enabled? If so we should test for `false` and set `shutdown: true` and the `else -> shutdown: false`. Please don't rely on EOS defaults, as things like shutdown can be easily reversed with global command.

2021-04-01 09:11 UTC, ClausHolbechArista approved these changes
LGTM

2021-04-01 09:11 UTC, merged

2021-04-13 09:55 UTC, kmueller68 commented
Thank you very much to all of you for your effort implementing this.
This helps me very much to setup things more effective for my current project.

2021-09-16 11:19 UTC, gusmb commented
> > > When the node names are not unique, only the first interface on that node is used. Not sure if you want to support below configuration (might mention it in the documentation).
> > > e.g. the following will only configure interface Ethernet7 and not Ethernet8
> > > ```
> > >     Tenant_A_WAN_Zone:
> > >         vrf_vni: 14
> > >         l3_interfaces:
> > >           - interfaces: [ Ethernet7, Ethernet8 ]
> > >             ip_addresses: [10.10.10.10/24, 10.10.20.20/24]
> > >             nodes: [DC1-BL1A, DC1-BL1A]
> > >             mtu: 9000
> > >             description: "test"
> > > ```
> > 
> > 
> > Let me add note to the documentation
> 
> Please update the j2 template to handle this scenario, so it's consistent with similar data models

How did this end up being resolved? I would expect to manage "non-uniqueness" this way:

 ```
Tenant_A_WAN_Zone:
   vrf_vni: 14
   l3_interfaces:
     - interfaces: [ Ethernet7, Ethernet8 ]
        ip_addresses: [10.10.10.10/24, 10.10.20.20/24]
        nodes: [DC1-BL1A, DC1-BL2A]
        mtu: 9000
        description: "test"
     - interfaces: [ Ethernet9 ]
       ip_addresses: [10.10.30.30/24]
       nodes: [DC1-BL1A]
       mtu: 9000
       description: "test"
```

Since `l3_interfaces` is a list, it should support multiple list elements with unique keys. Like in the example above, Ethernet9 l3 interface is configured on the same node as Ethernet7. In general for this case, wouldn't it be simpler to have one interface per list item? This would probably provide more clarity. Example:

 ```
Tenant_A_WAN_Zone:
   vrf_vni: 14
   l3_interfaces:
     - interface: Ethernet7
        ip_address: 10.10.10.10/24
        node: DC1-BL1A
        mtu: 9000
        description: "test"
     - interface: Ethernet8
        ip_address: 10.10.20.20/24
        node: DC1-BL2A
        mtu: 9000
        description: "test"
     - interface: Ethernet9
        ip_address: 10.10.30.30/24
        node: DC1-BL1A
        mtu: 9000
        description: "test"
```

Then there is no conflict about the uniqueness, as every list element can be uniquely identified by it's key (ip_address, which is unique per VRF)