EVPN host-flap settings
aristanetworks/ansible-avd pull request #915
Opened 2021-04-29 16:22 UTC by mpergament

## Change Summary

EVPN host-flap settings

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #914 

## Component(s) name

`arista.avd.eos_designs`
`arista.avd.eos_cli_config_gen`

## Proposed changes
```YML
evpn_hostflap_detection:
  window: 20
  threshold: 30
```

## How to test

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-04-30 05:30 UTC, ClausHolbechArista requested changes

2021-04-30 05:30 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/overlay/ebgp/router-bgp.j2
> +{%     if switch.evpn_role != "server" and evpn_hostflap_detection.window is arista.avd.defined and evpn_hostflap_detection.threshold is arista.avd.defined %}
Why not on a server? Remember that server role can be on a leaf where we services are also deployed. Maybe use `if switch.configure_tenants is arista.avd.defined(true)` or `if switch.vtep_ip is arista.avd.defined` ?

2021-04-30 05:30 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/router-bgp.j2
> +#### EVPN Host Flapping Settings
Please add an empty line between line 157 and 158. To give a consistent MD output.

2021-04-30 13:30 UTC, ClausHolbechArista requested changes
Current tests are not working with the quotes around 'false'.

2021-04-30 13:30 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_designs/templates/designs/l3ls-evpn/overlay/ebgp/router-bgp.j2
> +      enabled: 'false'
Remove quotes. Maybe even refactor so line 34-38 could be replaced with `enabled: {{ evpn_hostflap_detection.enabled | arista.avd.default(true) }}

2021-05-03 11:46 UTC, ClausHolbechArista requested changes
We need to redo the documentation. Let me know if I can help.

2021-05-03 11:46 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/molecule/evpn_underlay_ebgp_overlay_ebgp/documentation/devices/DC1-SPINE1.md
> +#### EVPN Host Flapping Settings
Should not be generated for devices where it is not configured.
Problem is that documentation looks at wrong variables.

2021-05-03 11:46 UTC, ClausHolbechArista commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/router-bgp.j2
> +{%     if evpn_hostflap_detection.window is arista.avd.defined or evpn_hostflap_detection.threshold is arista.avd.defined or  evpn_hostflap_detection.enabled is arista.avd.defined(false) %}
device documentation should only look at structured_config variables. So we need to adjust this documentation to use the same vars as you use in the eos config template. I can help if you like.

2021-05-03 16:34 UTC, ClausHolbechArista approved these changes
LGTM

2021-05-03 16:34 UTC, carlbuchmann approved these changes
LGMT!

2021-05-03 16:36 UTC, merged