NTP authentication
aristanetworks/ansible-avd pull request #916
Opened 2021-04-29 23:23 UTC by anavazio

## Change Summary

Added NTP authentication for one or more sha1 or md5 keys.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [x] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #820

## Component(s) name

`arista.avd.eos_cli_config-gen`

## Proposed changes
Add NTP authentication using either SHA1 or MD5 hashes, with the ability to add trusted and untrusted keys.

Defining "keys" within ntp_server activates NTP authentication.
An arbitrary id from 1 to 65534 inclusive is required.
A key is assumed to be trusted unless defined otherwise.

`keys:
    <id>:
      hash: <md5 or sha1 hashed password>
      hash_algorithm: < md5 | sha1 >
      trusted: < true | false > (optional)`

## How to test

## Checklist:

- [x] My code has been rebased from devel before I start
- [x] I have read the [**CONTRIBUTING**](https://www.avd.sh/docs/contributing/) document.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [x] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-04-30 00:49 UTC, carlbuchmann requested changes
@anavazio thanks for submitting this PR!

Need to adjust data model to follow our standards for eos_cli_config_gen which provides no abstraction.

```yaml
ntp_authenticate: <true | false >

ntp_authentication_keys:
  <key_identifier | 1-65534>:
    hash_algorithm: < md5 | sha1 >
    key:  "< encypted_key >"

ntp_trusted_keys: "< list of trusted-keys as string >"
```
@onurgashi can you please review and commend if you agree?

2021-04-30 00:51 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/ntp.md
>  | 10.1.1.1 | true |
you submitted generate artifacts, but the PR doesn't include the augmented test case -> https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/ntp.yml

2021-04-30 06:49 UTC, titom73 reviewed
I can't see the generated configuration file in molecule. So I expect CI to fail as it will generate diffs with current version.

Could you also run molecule and update artifacts in this PR ?

Also, some trailing whitespaces are present in your README section. So you should remove them to pass the CI.

2021-04-30 18:17 UTC, anavazio commented
@titom73 I'm currently having an issue installing the container for development, so I'll get on that once I have it installed. Thanks.

2021-05-01 14:23 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/documentation/devices/ntp.md
> +
This is more cosmetic, but try to have the render CLI output match as close as possible the order on EOS device. Also, remove the new line introduced.

2021-05-01 14:26 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/ntp.yml
> +  ntp_trusted_keys:
`ntp_trusted_keys` should be a simple string containing multiple keys and not a list.

example of possible values:

```yaml
 ntp_trusted_keys: "10"
 ntp_trusted_keys: "10-12,15"
 ntp_trusted_keys: "10,12,15"
```

2021-06-08 07:56 UTC, ClausHolbechArista commented
@anavazio We will release 2.2 very soon, so to get this PR merged in time, we need to get it finished today or tomorrow. I can help get it over the finish line if it is okay with you. I would submit fixes directly to your branch. Please let me know.

2021-06-08 12:02 UTC, anavazio commented
@ClausHolbechArista Of course! Thank you!

2021-06-10 18:18 UTC, carlbuchmann approved these changes
LGMT!

2021-06-11 07:54 UTC, merged