draft services-routing update
aristanetworks/ansible-avd pull request #961
Opened 2021-05-17 20:27 UTC by ryanmerolle

## Change Summary

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [X] Documentation content changes
- [ ] Other (please describe):

## Related Issue(s)

Fixes #195
## Component(s) name

`arista.avd.eos_cli_config_gen`

## Proposed changes

Update and expand service routing data model and templates to account for addition of BGP no equals default.

## How to test

## Checklist:

- [X] My code has been rebased from devel before I start
- [X] I have read the [**CONTRIBUTING**](https://avd.sh/en/latest/docs/contributing/) document.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have updated [molecule CI](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/molecule) testing accordingly
- [ ] All new and existing tests passed ([`pre-commit`](https://www.avd.sh/docs/installation/development/#python-virtual-environment), `make linting` and `make sanity-lint`).

2021-05-17 20:31 UTC, ryanmerolle commented
This will break anyone's automation using `service_routing_protocols_model` as it is now replaced with `service_routing.protocols_model `

I am happy to revert that if needed.  It just made more sense if anyone wanted to add additional service routing templates to the module.

I can also add some simple molecule tests as well.

2021-05-18 00:43 UTC, carlbuchmann commented
@ryanmerolle thank you for this PR.
From a data model perspective, these are all different section in the CLI, see extract from EOS 4.24.5M:

```
!
service routing configuration bgp no-equals-default
!
daemon TerminAttr
   exec /usr/bin/TerminAttr -ingestgrpcurl=192.168.200.11:9910 -cvcompression=gz                                                                                                                                                                                                                                             ip -ingestauth=key,telarista -smashexcludes=ale,flexCounter,hardware,kni,pulse,s                                                                                                                                                                                                                                             trata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -ingestvrf=MGMT -ta                                                                                                                                                                                                                                             illogs
   no shutdown
!
vlan internal order ascending range 1006 1199
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname CN-IT-BL1A
ip name-server vrf MGMT 192.168.200.5
ip name-server vrf MGMT 8.8.8.8
dns domain avd-lab.local
!
ntp local-interface vrf MGMT Management1
ntp server vrf MGMT 0.north-america.pool.ntp.org prefer
ntp server vrf MGMT 1.north-america.pool.ntp.org
!
service routing configuration route-map set-operations sequential
service routing configuration route-map no-set-community explicit-members
```

So I would suggest the following data model for configuration for `service routing`, with no change to current data model:

```yaml
service_routing_configuration_bgp:
  bgp_no_equals_default: < true | false >

service_routing_protocols_model: < multi-agent | ribd >

service_routing_configuration_route_map:
  set_operations: < merged | sequential >
  no_set_community: < explicit-members >
```

Let me know if you have questions!

2021-05-18 13:53 UTC, ryanmerolle commented
@carlbuchmann updated based on your feedback.

2021-05-18 20:18 UTC, carlbuchmann commented
> @carlbuchmann updated based on your feedback.

@ryanmerolle 
Please follow the suggested data model, this has also been reviewed and approved by @ClausHolbechArista 
Also note, the eos/documentation template should be named: service-routing-configuration-bgp.j2

Update the molecule scenario accordingly: 

- host_vars: service-routing-configuration-bgp.yaml
- update the hosts: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/hosts
- run the eos_cli_config_gen scenario: 

```bash
$ cd ansible_collections/arista/avd/molecule
$ make converge
```

2021-05-18 23:33 UTC, ryanmerolle commented
@carlbuchmann I have no problem updating as you suggest.  My contributions should get better as I further review the process.  I appreciate the guidance.

I do not see that @ClausHolbechArista offered any suggested data model in this ticket or the linked issue.  If you mean the existing that I change, I thought I reverted that already.

I'll make some updates tomorrow based on the new molecule feedback.  If you guys redirect me to some other suggested model, I will fold in as well.

2021-05-19 17:10 UTC, ryanmerolle commented
This should be good to go.

Thanks!

2021-05-19 18:54 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/service-routing-protocols-model.yml
> -#### service-routing-protocols-model ####
Please don't delete this test case.

2021-05-19 18:56 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/service-routing.yml
> +#### service-routing ####
rename this test case to service-routing-configuration-bgp.yml

2021-05-19 18:57 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/service-routing.yml
> +service_routing_configuration:
incorect data model, please upde to this:

```yaml
service_routing_configuration_bgp:
  no_equals_default: < true | false >
```

2021-05-19 18:58 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/service-routing.yml
> +service_routing_protocols_model: multi-agent
remove `service_routing_protocols_model: multi-agent` as it should stay in it's own dedicated test to avoid confusion as it's two separate templates.

2021-05-19 18:58 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/hosts
> -service-routing-protocols-model
keep this test case `service-routing-protocols-model`

2021-05-19 18:59 UTC, carlbuchmann commented on ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/hosts
> +service-routing
rename to `service-routing-configuration-bgp`

2021-05-19 19:00 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> -      - [Service Routing Protocols Model](#service-routing-protocols-model)
keep this section

2021-05-19 19:01 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
> +      - [Service Routing](#service-routing)
Create new section Service Routing Configuration BGP

2021-05-19 20:05 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/service-routing-configuration.j2
> +{% if service_routing_configuration.bgp_no_equals_default is arista.avd.defined %}
fix to match data model: `service_routing_configuration_bgp.no_equals_default

2021-05-19 20:08 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/service-routing-configuration.j2
> +!
remove the "!' delimiter only the top one is required!

2021-05-19 20:09 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/service-routing-configuration.j2
> +{% if service_routing_configuration.bgp_no_equals_default is arista.avd.defined %}
and test for true value: 
```jinja
{% if service_routing_configuration_bgp.no_equals_default is arista.avd.defined(true) %}
```

2021-05-19 20:10 UTC, carlbuchmann commented on ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/service-routing-configuration.j2
> +{# eos - Service Routing Configuration #}
update template name and description to service-routing-configuration-bgp.j2

2021-05-19 20:11 UTC, carlbuchmann requested changes
please see comments!

2021-05-19 23:22 UTC, ryanmerolle commented
I think all comments are resolved.

2021-05-28 10:32 UTC, carlbuchmann approved these changes
LGTM

2021-06-02 07:29 UTC, titom73 approved these changes
LGTM

2021-06-03 02:48 UTC, ryanmerolle commented
Seeing how @carlbuchmann and @titom73 reviewed/approved this.  I think we are good to merge correct?

2021-06-03 07:35 UTC, merged